### ISSUE TITLE
Purchase domain bioschemas.org

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#1]
By now redirect to https://github.com/BioSchemas/bioschemas

**Comment by martin-nc** [comment]
All done now.

**Comment by njall** [comment]
Should we try and buy bioschema.org too?

**Comment by njall** [comment]
It looks like bioschema.org is parked - but we could put in a request to buy it once it's available with a domain registrar

**Comment by martin-nc** [comment]
We looked at bioschema.org in Birmingham, if you remember. We could backorder it with GoDaddy for £18, if people felt it was worth it.
