### ISSUE TITLE
Create schema table for training materials

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#10]
Look at the [metadata fields](https://docs.google.com/spreadsheets/d/1cQ6mDbsG_cMX2EDAN8xH6-9yMRba8-rErlPeP8HTs8A/edit?usp=sharing) already collected and agreed by GOBLET and ELIXIR organisations and try to map it to schema.org

**Comment by rajido** [comment]
Follow schema table described in the [events spec](https://docs.google.com/document/d/1CzE_EGDp_II7skKCUFzZUQ7ZSkImkwcEPiQJVpX8YNk/edit?usp=sharing)

**Comment by anenadic** [comment]
2015-11-13 First draft of the table finished, need looking at by the other members of the group.

**Comment by AlasdairGray** [comment]
[Training Material profile](http://bioschemas.org/specifications/TrainingMaterial/) was published a long time ago.
