### ISSUE TITLE
Add contributors to specifications

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#100]
We should allow people to get credit for their work on the specifications. 

This will need to be captured in the mapping spreadsheet and then converted as part of the generation process.

**Comment by guicalman** [comment]
This functionality is available by the group link, for example the group for [Beacon specification](http://bioschemas.org/groups/Beacon/) is showed in the column next to the version in the [specification's web page](http://bioschemas.org/specifications/index.html).
Let me know if this works, if not we can find a different way.

Guillermo

**Comment by AlasdairGray** [comment]
We need this functionality in the mapping spreadsheet (as we discussed in person on 5 Oct – this is just so that we have a record).

The groups pages are proving too difficult to maintain and have been superseded by the new specification pages. We will be dropping them in the future.

**Comment by kcmcleod** [comment]
Contributors now appear in profile pages & group pages.
List of contributors based on their individual person page.
