### ISSUE TITLE
Allow same name for profile and type

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#103]
LabProtocol is both a proposal for a new type and a profile over that type. At the moment we can only show it as one or the other.

For now it is shown as a profile, but we need to have the type display as well.

**Comment by guicalman** [comment]
I suggest generate an additional collection called types, then we can have the same name for different files. I will make this change and let you know when is working.

**Comment by AlasdairGray** [comment]
That sounds sensible.

**Comment by kcmcleod** [comment]
done... we have collections for:
- specifications
- types
- draft specifications = _devSpecs
- draft types = _devTypes
