### ISSUE TITLE
Machine readable specification files

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#106]
It should be possible to get the machine readable version of the specification file from the html page

**Comment by guicalman** [comment]
Yes you can access it the specification.html by the GitHub icon in the [Specifications Page](http://bioschemas.org/specifications/). Would you prefer to show the code inside each specification's page?

**Comment by AlasdairGray** [comment]
I was thinking more the json-ld/schema files that would be needed for tools/validators.

We should specify what it is that we need in the machine readable files. @njall @kcmcleod @terazus

**Comment by terazus** [comment]
As far as I'm concerned I can work with both: the validator is json-schema based while the builder/editor is yml based. We just need to agree on the format at some point to harmonize applications between everyone.

**Comment by AlasdairGray** [comment]
For the new BioschemasGenerator we grab the yaml from the website GitHub repository and then generate a json-schema from the yaml.

**Comment by njall** [comment]
Having a json-ld file would be good to utilize existing RDFa libraries rather than tool developers needing to parse custom YAML each time. Something like what they have on schema.org e.g. schema.org/Course.jsonld would be very useful. Are there plans for this in bioschemas?

**Comment by AlasdairGray** [comment]
The json-ld for types proposed by Bioschemas are currently available. However, these serve a different role than the profiles. For the profiles we would need json-schema or ShEx descriptions.

**Comment by gtsueng** [comment]
JSON Schema/JSON-LD formatted files now available and can be used for profile validation.
