### ISSUE TITLE
Broken link in identifier background notes

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#114]
See [website issue 39](https://github.com/BioSchemas/bioschemas.github.io/issues/39) for more details.

**Comment by ljgarcia** [comment]
I am afraid that link is added by map2model as it corresponds to a schema.org term. The same problem is present on LabProtocol or any other specification generated with map2model. Please advice on what should be done in this case.

**Comment by AlasdairGray** [comment]
Ah, OK. I hadn't realised where the text had come from. I see that on schema.org they use a relative link ```<a href="/docs/datamodel.html#identifierBg">background notes</a>```

@kcmcleod @guicalman when we bring the terms in from schema.org can we replace relative URLs with full URLs?

**Comment by kcmcleod** [comment]
really a map2model issue, so moved there: BioSchemas/map2model#28
