### ISSUE TITLE
Create Biodiversity Group

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#115]
@frmichel has proposed the creation of a Biodiversity profile on the [mailing list](https://lists.w3.org/Archives/Public/public-bioschemas/2017Nov/0047.html).

**Comment by AlasdairGray** [comment]
@ricardoaat can you create the template for this group and make sure that the documents in the mailing list thread for a Taxon profile get linked in and added to the draft specification page.

**Comment by ricardoaat** [comment]
I have previously created a group _Taxon_ on this [branch](https://github.com/BioSchemas/bioschemas.github.io/tree/ric/feat/taxons-group), its necessary to improve the content i.e., description, abstract and objectives. In the meantime I will change its name to Biodiversity.

**Comment by frmichel** [comment]
Hi @ricardoaat, I just made a [PR](https://github.com/BioSchemas/bioschemas.github.io/pull/114) to update the group description:

**Comment by frmichel** [comment]
Hi, I just created another [PR](https://github.com/BioSchemas/bioschemas.github.io/pull/116) to create the _specifications/Taxon folder.
Franck.

**Comment by frmichel** [comment]
Thx @ricardoaat, now I guess everything is in place for discussing. 
Just one question: do I have to issue a PR any time I want to modify an example? 
Would it be possible to grant me write access on the Taxon folder and subfolders? (I'm afraid Github does not manage fine-grained rights, does it?).

**Comment by ricardoaat** [comment]
Hi @frmichel, I have added you as member, you will be able to modify it now. But as a good practice, every change to master on [bioschemas.github.io](https://github.com/BioSchemas/bioschemas.github.io) repository should be performed with a PR; as for the [specification](https://github.com/BioSchemas/specifications) repository I think you could push changes directly, but again, PR strategy helps to avoid issues.

I created a PR to merge the new Taxon specification and Biodiversity group to master https://github.com/BioSchemas/bioschemas.github.io/pull/117

**Comment by AlasdairGray** [comment]
This group has already been created. Closing this issue off.
