### ISSUE TITLE
Controlled vocabulary link in Tools->applicationCategory should be added

### ISSUE THREAD

**Issue by profgiuseppe** [BioSchemas/specifications#117]
The link should point to the list of terms either in [biotools documentation](https://biotools.readthedocs.io/en/latest/curators_guide.html#tool-type) or to [biotoolsSchema readme](https://github.com/bio-tools/biotoolsSchema) on github (containing a link to the previous page)

**Comment by kcmcleod** [comment]
went with biotools. now available on web.
