### ISSUE TITLE
Tools specification: mistake having "subjectOf" in mimimum and missing "url" 

### ISSUE THREAD

**Issue by profgiuseppe** [BioSchemas/specifications#119]
We think that there may be an issue with the automatically generated list of properties for the Tools specification.
In the mimimum set of properties, url is missing, while subjectOf is present.
This is probably a mistake in the spreadsheed. Ping @kcmcleod by @rajido suggestion.

**Comment by kcmcleod** [comment]
Fixed on spreadsheet. Waiting other issue fixes before pushing update to web.

**Comment by kcmcleod** [comment]
updated on web too
