### ISSUE TITLE
Complete specification text for training materials

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#12]
Use the text from [events spec](https://docs.google.com/document/d/1CzE_EGDp_II7skKCUFzZUQ7ZSkImkwcEPiQJVpX8YNk/edit?usp=sharing) as template as soon as #8 is finished

**Comment by anenadic** [comment]
2015-11-13 Text is written, needs looking at by this group before we can show it to the wider community

**Comment by AlasdairGray** [comment]
[TrainingMaterial profile](http://bioschemas.org/specifications/TrainingMaterial/) was published a long time ago.
