### ISSUE TITLE
Ontology vocabulary for featurelist property (Tools)

### ISSUE THREAD

**Issue by Federico77z** [BioSchemas/specifications#123]
A suggested ontology vocabulary and its URL should be added to the minimum property featurelist (Tools)

**Comment by profgiuseppe** [comment]
One possible vocabulary is made of the terms in EDAM ["Operation" class](http://edamontology.org/operation_0004), this was one of the original prposals during the Rome workshop when the Tools specification was created. More ontologies could be used. Anyways, they should be specified in the spreadsheet by @kcmcleod so they get imported in the specification page.

**Comment by AlasdairGray** [comment]
We need to think about how to express such optional suggestions in the final profile display. There are a few issues here:

- Listing all the ontology terms would be unwieldy, particularly when you consider all the subclasses of edam:Operations 
- How do convey to a non-semantic web expert that any of the terms under edam:Operations is acceptable and they should choose the most appropriate?

**Comment by albangaignard** [comment]
Use of EDAM Operation classes in ComputationalTool profile 0.6-DRAFT
