### ISSUE TITLE
Use of @id in DataCatalog

### ISSUE THREAD

**Issue by flaviolic** [BioSchemas/specifications#125]
Clarify the use and the format/content (url,text,...) of @id in DataCatalog specification cause it is present in some examples like uniprot.json (@ljgarcia ). If this is the recommended then we should use it consistently across examples.
Does it must be referred by includedInDataCatalog in Dataset as external reference (ex. "includedInDataCatalog": "http://www.uniprot.org")?

**Comment by ljgarcia** [comment]
@id is one of the JSON-LD keywords, see https://www.w3.org/TR/json-ld/#syntax-tokens-and-keywords

**Comment by AlasdairGray** [comment]
As @ljgarcia has stated @id is a JSON-LD keyword that allows you to point to other JSON-LD documents. 

I'm going to close this issue. Feel free to reopen if there is something more that needs to be done.
