### ISSUE TITLE
Improvement of description on "potentialAction (object of a ControlAction)" in tools specification

### ISSUE THREAD

**Issue by profgiuseppe** [BioSchemas/specifications#126]
There are two possible improvements for this property:
* the schema.org refers to "see potentialAction above... which has type of Action", however there is no potentialAction above in Bioschemas specifications, neither the type is Action
* there are two properties with the same name, labelled as input and output This may be confusing for the users, while it could be made clear that it is a single *ControlAction* object, containing two properties: **object** (for input) and **result** (for output). Please see [this example](https://github.com/BioSchemas/specifications/blob/master/Tool/examples/bar3.json) for a possible usage

**Comment by stain** [comment]
we did consider `potentialAction` for workflows in [earlier RO-Crate](http://www.researchobject.org/ro-crate/0.2/#workflows-and-scripts):

```
       {
            "@id": "workflow/retropath.knime",  
            "@type": "SoftwareSourceCode",
            "additionalType": {"@id": "Workflow"},
            "name": "RetroPath Knime workflow",
            "description": "KNIME implementation of RetroPath2.0 workflow",
            "author": {"@id": "#thomas"},
            "programmingLanguage": {"@id": "#knime"},
            "license": "https://spdx.org/licenses/BSD-2-Clause.html",
            "potentialAction": {
                "@type": "ActivateAction",
                "instrument": {"@id": "#knime"}
            }
        }

       {
            "@id": "#knime",
            "@type": [
                "ComputerLanguage",
                "SoftwareApplication"
            ],
            "name": "KNIME Analytics Platform",
            "alternateName": "KNIME",
            "url": {"@id": "https://www.knime.com/knime-software/knime-analytics-platform"},
            "version": "3.6"
        }
```

In here you can consider the workflow script as a becoming the `object` of a new https://schema.org/Action using the workflow engine as `instrument`

**Comment by albangaignard** [comment]
Not considered as suitable for now. It would need more use cases do be provided.
