### ISSUE TITLE
Clarify when a property should contain a Bioschemas type and when a schema.org type

### ISSUE THREAD

**Issue by profgiuseppe** [BioSchemas/specifications#127]
There are properties that should contain a structured type, like **includedInDataCatalog** in DataSet. However, the minimum required properties for the Bioschemas type may be overkill, e.g. someone may only want to put the URL for the homepage of the resource, and the full description could be retrieved from that page.

The current link in that specific case points to the schema.org type, it could be useful a Bioschemas description clearly stating the possible usage.

The same applies to **potentialAction** in Tool: **object** and **result** for *ControlAction* are of type *DataSet*, but it is quite easier to use the schema.org DataSet in this case than the Bioschemas one.

**Comment by ljgarcia** [comment]
I kind of remember that it is always possible to point to either the page containing the description (e.g., the DataCatalog) or use the link defined as @ id. @justinccdev maybe you know better?

**Comment by justinccdev** [comment]
Yes, you can use the @ id property by itself to point to a DataCatalog defined elsewhere. [Here's](https://stackoverflow.com/questions/34761970/schema-org-json-ld-reference/34776122#34776122) a good example.  The node object referenced should then validate to the corresponding Bioschemas profile if it exists.

**Comment by ljgarcia** [comment]
@profgiuseppe  does it clarify the way to point to an thing that has been described somewhere else without fully describing it? If so, please as add a "resolve" comment and close. Otherwise let us know if you still have doubts.

**Comment by AlasdairGray** [comment]
We should add an example of this usage to our tutorial material.

**Comment by AlasdairGray** [comment]
I believe that this issue has been resolved.
