### ISSUE TITLE
Clarify the usage of publication in DataSet and DataCatalog

### ISSUE THREAD

**Issue by profgiuseppe** [BioSchemas/specifications#128]
*DataCatalog* has a property **citation** and a property **publication**. The different usage of the two could be clarified in the Bioschemas description. My interpretation is that **citation** refers to the publication about the catalog, while **publication** is about the date and other information about the publication of the data in the catalog (e.g. UniprotKB release date and version).

Also, **citation** in *DataSet* has expected type *Text*, while in DataCatalog is either *Text* or *CreativeWork*. It should be noted that **citation** for *DataSet* in schema.org accepts both *Text* and *CreativeWork*, so my suggestion is to harmonize *DataCatalog* and *DataSet* **citation** types, for consistency.

**Comment by Drosophilic** [comment]
I agree. As I understand it:
**citation** -  "A citation or reference to another creative work, such as another publication, web page, scholarly article, etc." which accepts both _Text_ and _CreativeWork_ 

**publication** - "A publication event associated with the item.", which accepts _CreativeWork_.

Perhaps @sarala or @agbeltran would like to chime in with more.

**Comment by agbeltran** [comment]
@profgiuseppe indeed, [sdo:publication](http://schema.org/publication) associates a ```CreativeWork``` with a ```PublicationEvent```, which refers to the act of publication.

On the other hand, [sdo:citation](http://schema.org/citation) links a ```CreativeWork``` (in our case, ```Dataset``` or ```DataCatalog```) with another ```CreativeWork``` (the scholarly article/publication). 

You can see that I raised a discussion point about this in the [schema.org tracker](https://github.com/schemaorg/schemaorg/issues/1763).

In particular, [Richard Wallis's response](https://github.com/schemaorg/schemaorg/issues/1763#issuecomment-334440895) is very informative.

About the domain and ranges, the specifications in Bioschemas should match those defined in schema.org, unless some extension was proposed that should be feed back to schema.org.

So, I will revise the specifications and make sure that for ```Dataset```, for example,  the range for citation is ```Text``` or ```CreativeWork```.

**Comment by ljgarcia** [comment]
@agbeltran, @profgiuseppe, @sarala 

schema:citation is used to link to any other schema:CreativeWork so, in the context of schema:DataCatalog, it can be used to point to publications referenced by this schema:DataCatalog. Now, currently, schema:publication is the Bioschemas recommendation for "how to cite us", but schema:publication requires a PublicationEvent rather than a CreativeWork (e.g., a scholarly article). What if instead of schema:publication we use schema:subjectOf for "how to cite us"? See http://pending.3-2.schemaorgae.appspot.com/subjectOf

**Comment by profgiuseppe** [comment]
@ljgarcia your proposal is interesting.

That would allow us the following distinction:

- [publication](http://schema.org/publication) as the publication event of the DataCatalog (e.g. release date/version)
- [subjectOf](http://schema.org/subjectOf) as one or more articles recommended for "How to cite us", or in general papers about the DataCatalog
- [citation](http://schema.org/citation) for referencing a specific version of a third-party entity, e.g. something used to create part of the data inside the DataCatalog, like a tool (e.g. ClustalW, blast etc), or something containing identifiers that may change over time. This however is not something actually included in the DataCatalog 
- [hasPart](http://schema.org/hasPart) for referencing a specific version of a third-party DataCatalog, which is included (e.g. UniProtKB release used as basis for the data, PDB release used for generating profiles etc)

What do you think? Pinging also @agbeltran and @sarala

**Comment by ljgarcia** [comment]
What I propose is replacing schema:publication with schema:subjectOf for schema:DataCatalog and use it as "how to cite us" but I will leave this with @sarala and @agbeltran who have actually worked on the DataCatalog and Dataset profiles.

Regarding dataset1 hasPart dataset2, I would say that is true only if dataset1 includes completely dataset2. If dataset1 uses some information from dataset2 as a basis, maybe citation could work in this case.

**Comment by agbeltran** [comment]
@ljgarcia what you are proposing is exactly what I said before; sdo:citation should be used instead of sdo:publication

**Comment by agbeltran** [comment]
sorry! reading correctly I see that you propose to use sdo:subjectOf !

**Comment by ljgarcia** [comment]
@agbeltran Yes, I propose to use sdo:subjectOf for "how to cite us" while sdo:citation to point to any other CreativeWork (as suggested by the spec)

**Comment by sarala** [comment]
Shall we harmonise on sdo:publication and sdo:citation for now and discuss whether we really need sdo:subjectOf in the next meeting. Do you have a use case for this, where sdo:publication is not the same as sdo:subjectOf?

**Comment by ljgarcia** [comment]
@sarala sdo:publication requires a PublicationEvent while sdo:subjectOf goes directly to a CreativeWork (including scholarly articles) so it feels kind of more natural for "how to cite us". Also, sdo:subjectOf is inverse of sdo:about, used in CreativeWork to refer to the subject matter of the content of, for instance, a scholarly article. "how to cite us" is the current purpose of sdo:pùblication, is not it?

If you see sdo:publication is a better option for "how to cite us", it would be just a matter of having examples showing how to use it when there is not event associated but just a scholarly article.

**Comment by philbarker** [comment]
At the elixir hackathon, the publication property seems to be being misused & misunderstood. Perhaps there needs to be something added to the definition. FWIW I don't think a PublicationEvent is a good way to answer the question of 'how to cite us' or 'when was this published'; it's more suitable for events like book launches.

**Comment by AlasdairGray** [comment]
It seems that the appropriate usage in schema.org is to use `citation` to point to a CreativeWork which can be typed as a [ScholarlyArticle](https://schema.org/ScholarlyArticle) that is the publication or just include the text. 

This is also the usage recommended in the Google [profile](https://developers.google.com/search/docs/data-types/dataset) of a dataset.

@sarala is going to update the crosswalk document to remove the `publication` property and include an example of using `citation` to point to a `ScholarlyArticle`.

**Comment by AlasdairGray** [comment]
> Also, **citation** in _DataSet_ has expected type _Text_, while in DataCatalog is either _Text_ or _CreativeWork_. It should be noted that **citation** for _DataSet_ in schema.org accepts both _Text_ and _CreativeWork_, so my suggestion is to harmonize _DataCatalog_ and _DataSet_ **citation** types, for consistency.

Just reviewing the Dataset profile version 0.3-DRAFT with respect to this issue. The expected types are `CreativeWork` and `Text`. This harmonizes our usage with the changes proposed in DataCatalog 0.2-DRAFT.

**Comment by AlasdairGray** [comment]
This is fixed in Dataset version 0.3-DRAFT and DataCatalog 0.2-DRAFT
