### ISSUE TITLE
Controlled vocabulary of keywords property in Tool specification

### ISSUE THREAD

**Issue by profgiuseppe** [BioSchemas/specifications#129]
The *Tool* specification has a broken link i the controlled vocabulary link for the property **keywords**.
In the original spreadsheet created at the workshop in Rome, @martin-nc commented suggesting the [topic branch](http://edamontology.org/topic_0003) of the EDAM ontology. I used that for my implementation example. However, @rajido at the Italian workshop in Bologna pointed out that maybe this should be left open, given that different users may think that different keywords would be important.

**Comment by kcmcleod** [comment]
The gSheet simply has X for the value of controlled vocabularies. This is something for the editor to resolve.

**Comment by profgiuseppe** [comment]
Thanks @kcmcleod . Once an agreement is made, what kind of text should we add to the gSheet? Simply the link or something else?

**Comment by AlasdairGray** [comment]
This is related to the comment I have just put on #123
