### ISSUE TITLE
Enrich the specifications in the websites with bioschemas descriptions.

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#131]
At least the google doc where we had the original tools specification contains Bioschemas property descriptions complementing the Schema.org descriptions. We should check the Bioschemas descriptions appear in the website tools specification. Bioschemas descriptions complementing the generic Shchema.org description seem to be quite useful for developers.

**Comment by AlasdairGray** [comment]
I think the issue here is that the content has not been moved from the google document into the mapping file. If you look at [protein annotation](http://bioschemas.org/specifications/ProteinAnnotation/specification/) you will see that the bioschema comments are picked up by the mapping tool

**Comment by kcmcleod** [comment]
done. latest version available  on drafts page; see: http://bioschemas.org/devSpecs/Tool/specification/
