### ISSUE TITLE
Acknowledging Funding in Schema.org?

### ISSUE THREAD

**Issue by cboettig** [BioSchemas/specifications#133]
I am curious to hear opinions from this group on how to structure metadata regarding academic funding (e.g. grant support) in schema.org metadata.  The CrossRef / [FundRef standard](http://data.crossref.org/reports/help/schema_doc/4.4.0/fundref_xsd.html) is probably a good starting point, but doesn't have an obvious analog in Schema.org.  Modifying http://schema.org/Award is one possible starting point, but schemaorg developers appear to be thinking of `Award` to mean more like Grammy than Grant.  This issue is discussed in more detail in https://github.com/codemeta/codemeta/issues/160 (and links therein), with a few possible proposals, and in an open but stalled issue in schemaorg itself: https://github.com/schemaorg/schemaorg/issues/383.

**Comment by gtsueng** [comment]
per discussion in https://github.com/codemeta/codemeta/issues/160 and https://github.com/schemaorg/schemaorg/issues/383, `funding` is a pending property in schema.org. @cboettig, @kcmcleod please comment/reply by January 15th if you feel this issue should remain open, otherwise it will be closed.
