### ISSUE TITLE
DataRecord spelling error and broken link

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#134]
On http://bioschemas.org/specifications/DataRecord/specification/ you have written "isBasedon" instead of "isBasedOn", resulting in a broken link. Thanks to Martin Norling for spotting this error.

**Comment by kcmcleod** [comment]
Corrected in spreadsheet, so should be fixed at next generation

**Comment by rajido** [comment]
Great! thanks. BTW do you think we could also make the modification in ... https://github.com/BioSchemas/bioschemas.github.io/edit/master/_specifications/DataRecord/specification.html
... so it will also work in our site before the next generation?
