### ISSUE TITLE
Protein v0.4 is-related-to usage

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#139]
What do "value" and "hasEvidence" refer to in the following exert?

> Bioschemas: Used as short and direct alternative to additionalProperty. It represents the association between a protein and a disease. The disease should be modeled as a MedicalCondition. Whenever possible, use the MedicalCode to refer to an ontology term such as those in OMIM. If PropertyValue is used as the object, use the property "value" for the medical condition and the propererty "hasEvidence" for any evidence related to the association.

**Comment by ljgarcia** [comment]
hasEvidence has not been discussed yet but I hope to do so this week.

**Comment by ljgarcia** [comment]
Not an issue anymore. The whole protein profile has to be redone based on the Protein type.
