### ISSUE TITLE
Create a basic Phenotype profile

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#144]
We mentioned this during the Samples meeting last week. @ficolo was pointed as the one to lead this profile. Maybe @CarlosHorro could help as well?

**Comment by ficolo** [comment]
For our particular use case at the IMPC we need a PhenotypeCall type, that is a Gene Phenotype association. We could use the work of http://phenopackets.org/ as a starting point.

They have already defined some type and relations using proto files:

https://github.com/phenopackets/phenopacket-schema/blob/master/src/main/proto/org/phenopackets/schema/v1/phenopackets.proto

The fields they have consider so far for the Phenopacket are:

- id: An identifier specific for the phenopacket
- patient: The individual representing the focus of the packet - e.g. the proband in rare disease cases or cancer patient
- individuals: Individuals genetically related to the patient - e.g. mother, father, siblings or members of a cohort
- pedigree: The pedigree defining the relations between the patient and their relatives
- biosamples: Biosample(s) derived from the patient or a collection of biosamples in isolation
- genes: Placeholder for gene concepts - could be used for either describing candidate genes or causative genes. The resources using these fields should define what this represents in their context
- variants: Placeholder for genetic variants - could be used for either describing candidate variants or diagnosed causative variants. The resources using these fields should define what this represents in their context.
- diseases: Placeholder for disease concepts - could be used for either describing diagnosed or suspect conditions. The resources using these fields should define what this represents in their context
- genome_assembly: Reference genome assembly against which the sample was called. This is required as the VCF specification does not mandate this
- vcf: Pointer to the relevant VCF file for the patient
- metaData: Structured definitions of the resources and ontologies used within the phenopacket
- relationships: Relationships between entities described in the phenopacket

I took this information from [here](https://github.com/phenopackets/phenopacket-schema/blob/master/src/main/proto/org/phenopackets/schema/v1/phenopackets.proto) and [here](https://github.com/phenopackets/phenopacket-schema/blob/master/src/main/proto/org/phenopackets/schema/v1/core/base.proto).

**Comment by AlasdairGray** [comment]
First draft Phenotype profile was created in November 2018 at the Biohackathon.
