### ISSUE TITLE
Find a better way to communicate the selected type for profiles

### ISSUE THREAD

**Issue by kcmcleod** [BioSchemas/specifications#146]
Recently, rdf:type was added to the profile specifications but this seems to be confusing, we got questions about it during the Samples meeting last Thu & Fri. The rdf:type is not only the one for the profile, as the BioChemEntity type (or whichever corresponds to the actual type) is also an rdf:type.

Maybe somehow as part of the hierarchy?

**Comment by kcmcleod** [comment]
This was moved over from bioschemas.github.io repo issue number 58.

**Comment by AlasdairGray** [comment]
#250 is a duplication of this issue

Following is copied across from that issue

> The properties `rdf:type` and `schemaorg:additionalType` should be removed from profiles as they cause confusion or lead to incorrect usage.
> 
> We need to make clear that all markup needs to include an `@type` declaration, and JSON-LD supports multiple types being stated, e.g. `"@type": ["Sample", "OBI:0000747"] `.
> 
> `additionalType` is only included in schema.org to support multiple types in the microdata format which we are not advocating the use of in Bioschemas.

**Comment by orchid00** [comment]
I'm one confused person about rdf:type I still find it here: https://bioschemas.org/devSpecs/Event/ is it in the plans to be removed?

**Comment by orchid00** [comment]
Second question, now that "audience" is EDAM topic, the field "topic" seems to be not needed, or what should be the difference here?

**Comment by AlasdairGray** [comment]
Best practice is to have `@type` and `@id` on all JSON-LD encoded markup (equivalent syntax exists for other serialisations). 

We will be shortly undertaking a tidy up of all profiles and the associated training material. At this point we will remove `rdf:type` (`@type`) from the table of terms in the profiles.

this is related to issue #294

**Comment by gtsueng** [comment]
The JSON Schema `@type` and `@id` are now required properties and `@type` has replaced `rdf:type` for all profiles.
