### ISSUE TITLE
isContainedIn instead organism?

### ISSUE THREAD

**Issue by kcmcleod** [BioSchemas/specifications#147]
@otienoanyango BioChemEntity has a property isContainedIn (equivalent to isPartOf as described in the Relation Ontology) that can be used to link a protein structure to the corresponding organism. Also, if the protein structure corresponds to a protein and the proteins corresponds to an organism, do you need organism at this level?

**Comment by kcmcleod** [comment]
replaces https://github.com/BioSchemas/bioschemas.github.io/issues/55

**Comment by otienoanyango** [comment]
We do not need organism at this level.

**Comment by AlasdairGray** [comment]
The property `taxonomicRange` defined on [BioChemEntity](https://bioschemas.org/BioChemEntity) should be used for this purpose.
