### ISSUE TITLE
Create markdown for BioChemEntity

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#150]
I just updated the BioChemEntity spec at https://docs.google.com/spreadsheets/d/1Kbrej3YJDrrzTwJQ13EDP0hNy2Ey0-8RSndeeNfxZnk/edit#gid=1261485211

It would be nice to test @ricardoaat 's markdown converter with this spec and see how it looks and how it can be used as input for the spec on the github.io repo. For that I propose @ricardoaat as assignee.

Of course, the idea as well would be to update the current spec on our webpages. For that I propose @kcmcleod as assignee.

**Comment by AlasdairGray** [comment]
Have we made any progress on this?

**Comment by AlasdairGray** [comment]
Issue is now stale.
