### ISSUE TITLE
ProteinAnnotatoin. Move additionalType to recommended or optional

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#154]
hi @aurel-l. We have an official type for ProteinAnnotation, so the additionalType is no longer minimum, please update the mapping file and notify @ricardoaat or @kcmcleod so they can update the pages. Thanks

**Comment by gtsueng** [comment]
ProteinAnnotation has been deprecated and is now superceded by SequenceAnnotation. Per multiple issues surrounding the property `additionalType` (https://github.com/BioSchemas/specifications/issues/538), it should be avoided. I am closing this issue for these two reasons.
