### ISSUE TITLE
ProteinAnnotation: Add categoryCode as optional

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#155]
Hi @aurel-l. There is a new property in BioChemEntity named "categoryCode" so if the entity is coined in a well-know vocabulary, it can be specified. This is useful, for instance, to model organisms as we have taxonomies. This is also useful for ProteinAnnotation as we have annotations related to, for instance, GO terms.

I would use it in Protein to refer to a GO annotation like this:
{
  "@type": ["BioChemEntity", "Protein"],
  "involvedIn": {
    "@type": "ProteinAnnotation",
    "identifier": "GO:0000278",
    "**categoryCode**": {
      "@type": "CategoryCode",
      "url": "http://purl.obolibrary.org/obo/GO_0000278",
      "codeValue": "GO:0000278",
      "name": "mitotic cell cycle"
    }
  }
}

Whenever the change is ready in the mapping, please ask @ricardoaat or @kcmcleod to update the pages. Thanks!

**Comment by gtsueng** [comment]
ProteinAnnotation has been deprecated and is superceded by SequenceAnnotation. This issue has been marked as closed due to deprecation.
