### ISSUE TITLE
Tool Citation should only be CreativeWork

### ISSUE THREAD

**Issue by terazus** [BioSchemas/specifications#159]
The tool citation attribute should only be referring a CreativeWork and we should abandon the free text alternative.
This is from the point of a view of a developer. A citation isn't text, it's an object and programs will need to be able process it as such. If we allow free text here, applications that rely on a CreativeWork expected type will have inconsistencies.
You can use simple things like:
{"@type";"CreativeWork",
"name":"article's name",
"url":"PMID/DOI ect URL"}

**Comment by profgiuseppe** [comment]
Just to nota that this proposal will be a Bioschemas specific restriction of the possible values available for schema.org [SoftwareApplication](http://schema.org/SoftwareApplication) and its parent [CreateveWork](http://schema.org/CreativeWork).

Please also see #128 for an ongoing discussion about the Citation and other related fields.

**Comment by AlasdairGray** [comment]
Not all publications have a web page or DOI for them, e.g. ceur-ws publications. It would be good to still have the ability to include the citation as free text.

**Comment by terazus** [comment]
{ 
      "@type":"CreativeWork",
     "name":"article's name"
}
Would be equivalent of free text if I'm not wrong. You can even add a description and some other fields without relying on a webpage/DOI/...

**Comment by AlasdairGray** [comment]
While that is a way of creating the description, it is more work than just copy and pasting a citation text that I can grab from my scholar page

**Comment by albangaignard** [comment]
Fixed in ComputationalTool 0.6-DRAFT
