### ISSUE TITLE
Live Deploys: FAIRsharing have Dataset markup

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#162]
The FAIRsharing website has Dataset markup within it. 

@ricardoaat @kcmcleod This should be added to the live deploys page

@Drosophilic Are there other Bioschema's specifications that you have deployed markup for? Are there other pages on the site that have markup other than just the main front page?

**Comment by Drosophilic** [comment]
Thanks @AlasdairGray. We have marked up the homepage with datacatalog and dataset. We haven't added information to other pages yet.

**Comment by kcmcleod** [comment]
added to table
