### ISSUE TITLE
Linking people to events

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#163]
I really like how we display [people](http://bioschemas.org/people/) (ie. [Leyla](https://github.com/BioSchemas/bioschemas.github.io/edit/master/_people/LeylaGarcia.md)) inside [groups](http://bioschemas.org/groups/) (ie. [proteins](http://bioschemas.org/groups/Proteins/)) by providing group information in people's profiles.

What do you think about doing the same for [meetings](http://bioschemas.org/meetings/)?

We could add a field "meetings" in each profile identifying the events attended by every person. Then in the meeting pages (ie [Adoption meeting](http://bioschemas.org/meetings/2017-10_AdoptionMeeting/)) we could automatically display attendees.

I have recently collected some stats for Bioschemas. I did include an estimation of people involved checking the people that are participating in the WC3 group, GitHub and the Bioschemas website as well as people that participated in Bioschemas events. Results in this [spreadsheet](https://docs.google.com/spreadsheets/d/1-Mov3oPp6H9CaGyJ68QO0F-3SJyq6yGvUbzGfQG1rv8/edit?usp=sharing). Now that we have this data I think it would be easy to update people profiles to link them to meetings.

BTW with the stats I collected I created a slide with some numbers you can find in this [presentation](https://drive.google.com/file/d/1GBsY9SXyqu3Ba3wWl2T7CxjSk-uUS3AF/view?usp=sharing)

**Comment by AlasdairGray** [comment]
I like the idea, but not sure that the way we do groups is scalable and maintainable, and therefore not really appropriate for this.

@ricardoaat can you see if there is another way we could achieve this with Jekyll or some other form for the website?

**Comment by ricardoaat** [comment]
I will research a better approach for it, for now I have create a branch where people's profiles have details about the meetings they have attended stored on their respective markdown file.

The relation its being made by the name of the event. Please give it a look and tell me what you think.

https://github.com/BioSchemas/bioschemas.github.io/tree/ric/feat/people_meeting_relation

**Comment by ricardoaat** [comment]
I have updated the branch with the following:

- People are now included on the meetings as attendees.
- People are now included on the groups as members
- Updated person detail layout to show events they have attended and the groups they are members of
- Updated the way group detail layout fetches members information accordingly. 
- Added attendees information to meeting 

ToDo: Update all of the events with a list of attendees.

@rajido @AlasdairGray

**Comment by rajido** [comment]
thanks @ricardoaat ! I like the way you did it. Easier to maintain the list of people per group rather than the list of groups per people. Same for events. I think this will help the group lead(s) or the event organiser(s) to easily update participation.

**Comment by ricardoaat** [comment]
Thank you Rafa, it was your idea I just executed it :smiley:. Since the pull request is not merged I will proceed to close this issue. Reopen it if we are missing something.
