### ISSUE TITLE
Specification layout

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#164]
Just looked at the Data Catalog specification and there are some major issues with it. The issues seem to apply to all current specifications rather than draft ones.
![screen shot 2018-05-02 at 10 23 47](https://user-images.githubusercontent.com/1141265/39515799-0f5706fe-4df3-11e8-925c-0d41948a6744.png)

First it is missing the name, just saying specification.

Second it is missing the version number.

**Comment by ricardoaat** [comment]
@AlasdairGray Hello, the fix for this is on the pull request https://github.com/BioSchemas/bioschemas.github.io/pull/75

**Comment by AlasdairGray** [comment]
Great, sorry, I didn’t have time to check whether this was already a known issue.

My memory is that we had this previously and this has been lost. this is a major issue in terms of quality
________________________________

Heriot-Watt University is The Times & The Sunday Times International University of the Year 2018

Founded in 1821, Heriot-Watt is a leader in ideas and solutions. With campuses and students across the entire globe we span the world, delivering innovation and educational excellence in business, engineering, design and the physical, social and life sciences.

This email is generated from the Heriot-Watt University Group, which includes:

  1.  Heriot-Watt University, a Scottish charity registered under number SC000278
  2.  Edinburgh Business School a Charity Registered in Scotland, SC026900. Edinburgh Business School is a company limited by guarantee, registered in Scotland with registered number SC173556 and registered office at Heriot-Watt University Finance Office, Riccarton, Currie, Midlothian, EH14 4AS
  3.  Heriot- Watt Services Limited (Oriam), Scotland's national performance centre for sport. Heriot-Watt Services Limited is a private limited company registered is Scotland with registered number SC271030 and registered office at Research & Enterprise Services Heriot-Watt University, Riccarton, Edinburgh, EH14 4AS.

The contents (including any attachments) are confidential. If you are not the intended recipient of this e-mail, any disclosure, copying, distribution or use of its contents is strictly prohibited, and you should please notify the sender immediately and then delete it (including any attachments) from your system.

**Comment by ricardoaat** [comment]
@AlasdairGray Completely agree, thank you for spotting the error. I have just updated the pull request, shall i merge it?

**Comment by ricardoaat** [comment]
Fixed with Pull request BioSchemas/bioschemas.github.io#75.
