### ISSUE TITLE
Add PDBe to Live Deploys

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#165]
PDBe has protein markup on their records, see [4a7l](http://www.ebi.ac.uk/pdbe/entry/pdb/4a7l). We need to:
- [x] Find out how many pages are marked up with protein, protein annotation, and protein structure
- [x] Verify if they have DataCatalog and Dataset markup on their front page
- [x] Add to the live deploys page

**Comment by kcmcleod** [comment]
emailed Stephen to ask if he could estimate the number of pages marked up.

they do not appear to have any markup on the home page.

**Comment by kcmcleod** [comment]
Saqib Mir (saqib@ebi.ac.uk) responded...
* Protein Structure pages count: 140109
* Protein pages count: 214767

No DataCatalog or Dataset

**Comment by kcmcleod** [comment]
the number of live deploys updates weekly, so we may need to refresh this in 6 months. otherwise done for now.
