### ISSUE TITLE
Add contact person to the Bioschemas events we have in the meetings page

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#172]
http://bioschemas.org/meetings/

[title]
[date]
[location]
Contact: [contact person name. Ideally linked to its profile in Bioschemas ... http://bioschemas.org/people/]

**Comment by ricardoaat** [comment]
Hello Rafael,

I've created a PR adding contact information to the meeting details
https://github.com/BioSchemas/bioschemas.github.io/pull/95

**Comment by rajido** [comment]
Thanks @ricardoaat ... Contacts now displayed if available ... eg.  http://bioschemas.org/meetings/2018-09_ECCBathens/
