### ISSUE TITLE
Biosamples now has DataCatalog deployment

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#173]
Please add Biosamples home page https://www.ebi.ac.uk/biosamples/ to the list of live deploys for DataCatalog.

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fwww.ebi.ac.uk%2Fbiosamples%2F

**Comment by AlasdairGray** [comment]
Note that the Dataset URI in the listing does not resolve http://wp-p1m-40.ebi.ac.uk:8081/biosamples/samples

**Comment by ricardoaat** [comment]
Hello Alasdair,

I've created a pull request that adds Biosamples to the Live deploys list. 
https://github.com/BioSchemas/bioschemas.github.io/pull/97

**Comment by kcmcleod** [comment]
[PR97](https://github.com/BioSchemas/bioschemas.github.io/pull/97) has been merged. Now closing this issue.
