### ISSUE TITLE
Live deploys on specifications page out of date

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#174]
On the specifications page, the profiles listed with a live deploy (i.e. a green thunderbolt) is a subset of those that appear on the live deploys page.

**Comment by ricardoaat** [comment]
Hello Alasdair,

I have just created a PR with an update for this. https://github.com/BioSchemas/bioschemas.github.io/pull/98

I have added you as reviewer.

**Comment by AlasdairGray** [comment]
@ricardoaat  has this issue been resolved and merged in? If so, please close

**Comment by kcmcleod** [comment]
[PR98](https://github.com/BioSchemas/bioschemas.github.io/pull/98) has been merged, so closing.
