### ISSUE TITLE
Add examples to Training Material specification

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#185]
Each property should have a sample of its usage. See [Proteins profile](http://bioschemas.org/specifications/Protein/specification/) for an example.

**Comment by njall** [comment]
Sorry, I just noticed this. I'll get working on this for Training Materials and Events. 

Quick question - would I modify the specifcation.html file directly? Or is specifcation.html generated from map2model; and therefore I'd change the spreadsheet?

**Comment by ricardoaat** [comment]
I think its easier to update the spreadsheets [Event mapping](https://docs.google.com/spreadsheets/d/14xZeXfSO9I_cosZ-5jzLxiGB9OIgaOMmXmz19dBMNkw/edit#gid=1261485211) and [TrainingMaterial mapping](https://docs.google.com/spreadsheets/d/16qqCoLJfmqlmb4kE7rdEm2N-UoUD3LUr8BnY5Uj1Gyo/edit#gid=1261485211) and then to use [GoWeb](https://github.com/BioSchemas/bioschemas-goweb) to generate the YAML mapping for each specification.html.
I'll be happy to generate the YAML files.

Here's the [Gene mapping](https://docs.google.com/spreadsheets/d/1n_8nqlFiK_8dlqQX_ZWs_NlLjQPL3-fDopglhWu9ums/edit#gid=1261485211) spreadsheet that you can use as example.

**Comment by njall** [comment]
Ah, perfect. Thanks.

Do you have the Protein profile spreadsheet link for me to use as an example?

When I've generated the specification.html, do I just make a pull request to the Specs repo? https://github.com/BioSchemas/specifications/tree/master/Event

**Comment by ricardoaat** [comment]
Sure, here's the one for [Protein](https://docs.google.com/spreadsheets/d/1Lc6HNt_1PVBekVV2HfCmEVtQoEaxHeDWqKuvIk8-yL0/edit#gid=1261485211).

> When I've generated the specification.html, do I just make a pull request to the Specs repo? https://github.com/BioSchemas/specifications/tree/master/Event

No, it should be done to https://github.com/BioSchemas/bioschemas.github.io/blob/master/_specifications/Event/specification.html (bioschemas.github.io repo)
