### ISSUE TITLE
Add OmicsDI to Live Deploy page

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#186]
OmicsDI now has Dataset markup, e.g. [Array Express: E-MTAB-6481](https://www.omicsdi.org/#/dataset/arrayexpress-repository/E-MTAB-6481). 

@ricardoaat Please add to the Live Deploy page.

You may need to talk with the OmicsDI group to find out how many datasets they have marked up.

We should encourage them to add DataCatalog markup to their homepage.

**Comment by kcmcleod** [comment]
added OmicsDI Dataset to https://github.com/BioSchemas/bioschemas.github.io/tree/ld_omicsdi. @ricardoaat can you please ask team how many pages they have marked up?

**Comment by ricardoaat** [comment]
Sure thing, I will have that today.

**Comment by ricardoaat** [comment]
Information added on commit https://github.com/BioSchemas/bioschemas.github.io/commit/99ce127228d90c462ff6353de7cb288998e8f642
