### ISSUE TITLE
Adding events where bioschemas was presented in the meetings page?

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#188]
Bioschemas was presented in several events. At the moment many of these events are not listed in the Bioschemas website and maybe they should. So far I think we have two types of events: 1.- Events organised by Bioschemas which also includes Bioschemas tutorials or workshops organised within another event like NETTAB (well represented in the website) and 2.- events where Bioschemas was presented in the form of presentations or posters (not well represented in the website). I think we should have both in http://bioschemas.org/meetings/ and maybe make a distinction in the with a tag or having them in a list with a different header. What do you think? @ricardoaat @AlasdairGray

**Comment by ricardoaat** [comment]
This would be a great thing to have. I like the idea of having a tag to show wether the event was organised by Bioschemas or was part of a different event.

**Comment by AlasdairGray** [comment]
The other option is that we use a publications page to show events that are for dissemination purposes.

I started one of these a while back. Ken did you manage to take the page to completion?


http://www.macs.hw.ac.uk/~ajg33

________________________________
