### ISSUE TITLE
Acknowledge EU funding

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#189]
We need to ensure that we are explicitly acknowledging our funding sources, particularly the EU.

I propose that we add a link in the footer to an acknowledge our funders page. The page should also be available through the About menu

On the funders page we should list all the grants that have contributed to Bioschemas. This would include:
- EU H2020 ELIXIR-EXCELERATE
- ELIXIR Bioschemas Implementation Study https://www.elixir-europe.org/about-us/implementation-studies/bioschemas
- ELIXIR Integrating ELIXIR Italy into ELIXIR activities https://www.elixir-europe.org/about-us/implementation-studies/integrating-elixir-italy-elixir-activities
- ELIXIR Bioschemas: Community Adoption and Training https://www.elixir-europe.org/about-us/implementation-studies/bioschemas-community-adoption

@ricardoaat could you start drafting the page and the updated footer to link to it.

**Comment by ricardoaat** [comment]
Hello @AlasdairGray 

I have created a new branch [Acknowledge-EU-funding](https://github.com/BioSchemas/bioschemas.github.io/tree/ric/feat/Acknowledge-EU-funding) with a very draft version of the Funders page. Please let me know what you think.

**Comment by AlasdairGray** [comment]
Hi @ricardoaat 

Thanks for putting together the initial page. I've done some tidying up and improving of the text.

I'm happy for the page to go live. 

@rajido can you do a sanity check as well please?

@ricardoaat Should we be including schema markup on the page, e.g. organisations? (This does not need to be complete before that page goes live.

**Comment by ricardoaat** [comment]
Sure thing. I will work on it on a separate branch so I can do it to more pages.

**Comment by AlasdairGray** [comment]
I think most pages already include schema markup. @kcmcleod did that a while back.

**Comment by ricardoaat** [comment]
Excellent. I have created a PR now with this branch:  https://github.com/BioSchemas/bioschemas.github.io/pull/104

Waiting your approval for merging @AlasdairGray @kcmcleod @rajido

**Comment by ricardoaat** [comment]
Solved with PR https://github.com/BioSchemas/bioschemas.github.io/pull/104
