### ISSUE TITLE
Add MINT to live deploys

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#190]
MINT has DataCatalog and Dataset markup on their [homepage](http://mint.bio.uniroma2.it/), they should be added to the live deploys list.

We should check whether their content pages now have any mark up on them.

**Comment by kcmcleod** [comment]
> We should check whether their content pages now have any mark up on them.

They do not.

Adding MINT in PR: https://github.com/BioSchemas/bioschemas.github.io/pull/108
