### ISSUE TITLE
Add missing publications from Implementation Study report

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#192]
The following should be added to the publications page using the formatting of the publication page

- IB2018 Integrative Bioinformatics 2018 13-15 June 2018, Rothamsted Research, UK
  - Poster by Justin Clark-Casey
  - Featured in presentation by Justin Clark-Casey (Cambridge, ELIXIR-UK)
  - Featured in Keynote presentation by Carole Goble (UniMan, ELIXIR-UK)
- ELIXIR All Hands 4-7 June 2018, Berlin, Germany
  - Posters
  - Plenary lightning presentation and workshop presentation by Alasdair Gray (HWU, ELIXIR-UK)
  - Featured in Interop Platform Plenary presentation by Carole Goble (UniMan, ELIXIR-UK) 
  - Featured in several Use Case presentations
- Biodiversity Information Standards (TDWG) Conference August 2018 (http://spnhc-tdwg2018.nz/)
  - Poster by Franck Michael (CNRS)
- UK Ontology Network (UKON) Workshop 30 April 2018 (https://www.keele.ac.uk/scm/events/conferences/ukon2018/)
  - Presentation by Alasdair Gray (HWU, ELIXIR-UK)
  - Poster by Alasdair Gray (HWU, ELIXIR-UK)
  - Poster by Leyla Jael Garcia Casto (EMBL-EBI)
- Symposium: The Future of a Data-Driven Society, Maastricht University, 25 Jan 2018
  - Featured in invited keynote by Carole Goble (UniMan, ELIXIR-UK)
- Japanese National Bioscience Database Center - seminar December 2017
  - Seminar by Pete McQuilton (Oxford, ELIXIR-UK)
- 10th International SWAT4HCLS Conference 4-7 December 2017 (http://www.swat4ls.org/workshops/rome2017/programme/)
  - Featured in keynote presentation by Carole Goble (UniMan, ELIXIR-UK)
  - Poster by Leyla Jael García Castro (EMBL-EBI)
- ELIXIR-UK All Hands 2017, November 1-2 2017, Edinburgh, UK
  - Plenary presentation Alasdair Gray (HWU, ELIXIR-UK)
- Workshop on Managing Digital Research Objects in an Expanding Science Ecosystem, 15 Nov 2017, Bethesda, USA
  - Featured invited talk by Carole Goble (UniMan, ELIXIR-UK)
- UK Biobanking Showcase 2017, London, 18 October 2017
  - Featured invited talk by Carole Goble (UniMan, ELIXIR-UK)
- 16th International Semantic Web Conference (ISWC) 21-25 October 2017 (https://iswc2017.semanticweb.org/paper-579/)
  - Poster by Alasdair Gray (HWU ELIXIR-UK)
- EOSCpilot data interoperability technical workshop 4-5 October 2017
  - Overview presentation by Alasdair Gray (HWU, ELIXIR-UK), Carole Goble (UniMan, ELIXIR-UK) & Rafael C Jimenez (ELIXIR-Hub)
  - Tutorial by Leyla Jael Garcia Castro (EMBL-EBI), Sarala Wimalaratne (EMBL-EBI) & Alasdair Gray (HWU, ELIXIR-UK)
- Bio-Ontologies ISMB Community of Special Interest Workshop 24-25 July 2017 (https://www.iscb.org/cms_addon/conferences/ismbeccb2017/posterlist.php?cat=C)
  - Poster by Leyla Castro (EMBL-EBI)
- Bioschemas for Datasets - ELIXIR All Hands Meeting 23 March 2017
  - Presentation by Rafael C Jimenez (ELIXIR-Hub)

**Comment by kcmcleod** [comment]
In progress; see https://github.com/BioSchemas/bioschemas.github.io/pull/110

**Comment by kcmcleod** [comment]
closed by https://github.com/BioSchemas/bioschemas.github.io/pull/110
