### ISSUE TITLE
Tools group vs tools page

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#193]
Issue by @justinccdev (originally [issue 106 on website](https://github.com/BioSchemas/bioschemas.github.io/issues/106)

> Is the [tools page](http://bioschemas.org/tools/) linked anywhere?
> 
> Also, I'm now getting confused between the [Tools specification group](http://bioschemas.org/groups/Tools/) and the tools page, where only the former is linked from [the groups page](http://bioschemas.org/groups/).  Do we need to do something about this?

**Comment by AlasdairGray** [comment]
> Is the [tools page](http://bioschemas.org/tools/) linked anywhere?

Currently not, but it should be a top level menu item I think.
 
> Also, I'm now getting confused between the [Tools specification group](http://bioschemas.org/groups/Tools/) and the tools page, where only the former is linked from [the groups page](http://bioschemas.org/groups/).  Do we need to do something about this?

Certainly the terminology is confusing. We have 
- a tools specification being developed by the tools group
- a tools page that should be maintained by the technical group

Thoughts on renaming either of these? Probably easier to rename the tools page at this point.

**Comment by justinccdev** [comment]
>> Is the tools page linked anywhere?

> Currently not, but it should be a top level menu item I think.

Agreed.

>> Also, I'm now getting confused between the Tools specification group and the tools page, where only the former is linked from the groups page. Do we need to do something about this?

> Certainly the terminology is confusing. We have
> *    a tools specification being developed by the tools group
> *   a tools page that should be maintained by the technical group
> Thoughts on renaming either of these? Probably easier to rename the tools page at this point.

How about renaming the tools page to Software?

**Comment by AlasdairGray** [comment]
Can you make the changes on a branch and then circulate it as a PR for consideration?
