### ISSUE TITLE
Technical Group missing from list on Justin's page

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#195]
Justin is the lead of the Technical Group but this does not appear on his people page
http://bioschemas.org/people/JustinClark-Casey/

The technical group does appear on Alasdair's page who is a member of the technical group. The Validation group appear's on Alasdair's page, the group for which he is the lead
http://bioschemas.org/people/AlasdairGray/

**Comment by ricardoaat** [comment]
I am working on this now. I am thinking on changing the title "Other group members" to "All group members" on the group page. So we can have in one place all the group members. What do you think?

**Comment by AlasdairGray** [comment]
The group leads should not be repeated. 

This appears to be a problem with Justin's profile rather than anything to do with the group page template.

**Comment by AlasdairGray** [comment]
Justin's profile was missing membership of the technical group, which I have now added. 

However, I see that on the Validation page I appear as both the lead and a member which is not ideal. This is also true of Leyla on the BiologicalEntities group page.

@ricardoaat Can we omit the group leads from the group members?

**Comment by ricardoaat** [comment]
Yes, I will take that approach. It is a good idea to have a list for all the members in a group on the group md.

**Comment by AlasdairGray** [comment]
I think I see what is happening now. Is the information in the person's profile used any more? If not we should clear these out.

In the person profile display, you also need to include the leads.

**Comment by ricardoaat** [comment]
No, that field is not used anymore. I will clean that up. That's why I was proposing changing "Other group members" to "All group members" and including there the leads. Since that _member_ property is the one used to display the users groups he belongs to. 

> In the person profile display, you also need to include the leads.

You mean a section with the groups he leads?

**Comment by AlasdairGray** [comment]
Yes, why not have a section for groups they lead and another for groups that they are a member of.

We could also consider having details of the steering committee listed as well, but that is not so important.

**Comment by ricardoaat** [comment]
Excellent! I agree, Will work this on another PR in order to pollute no further the Biodiversity one.

**Comment by AlasdairGray** [comment]
Obsolete group array still exists in the profiles of individuals. These should be removed with the content being added to the respective group page.
