### ISSUE TITLE
Taxon specification missing Use Case document

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#196]
The use cases for the taxon specification need to be linked (related to #115).

**Comment by frmichel** [comment]
Hi Alasdair and Leyla, 

I just wrote a [first draft](https://docs.google.com/document/d/1bH9akvKzPh5SFPrxzGfYhKpZSzopzduGf-WQlHNlYAo/edit#) of the use cases with the ideas I could come up with. This should be enriched eventually.

It's in the [Taxon folder](https://drive.google.com/drive/folders/1Fp2AKbb07So7rVvUhnQIjpl8HLPSwpbP) on Google docs.

**Comment by AlasdairGray** [comment]
We'll need to get that captured into the useCase directory.

@kcmcleod can you let us know how to do this?

**Comment by AlasdairGray** [comment]
The use case has now been moved to the website. See pull request [139](https://github.com/BioSchemas/bioschemas.github.io/pull/139).
