### ISSUE TITLE
Website Menu Items

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#199]
The website menu is becoming cluttered again (https://github.com/BioSchemas/bioschemas.github.io/pull/115), and the `About` menu is a bit of a collect all. We also need to think about what will be coming with the training materials, etc.
 
How about the following reorganisation:
- Home
- Specifications
  - Recommendations (formally Current)
  - Drafts
  - Live Deploys
- Support 
  - Documentation
  - Tutorials
  - Software
- Community
  - Join
  - Meetings
  - People
  - Groups
  - Organisations (only details of the organisations, other content should be move to other pages)
- About
  - Governance
  - Publications
  - Funders
  - Logos

Not sure about the name of the `Support` item, please suggest alternatives.

Also not sure where the information about the Leadership team should go. Perhaps this should go back on the Governance page.

**Comment by rajido** [comment]
The new menu looks good.

I guess items in Community and About could be interchangeable or even in the same header.  Happy as you proposed it.

"Support" sounds good to me. I am not sure what will have in documentation though. Maybe it is "documentation and tutorials"? Or just tutorials?

At the moment governance section is mainly about the process to update the specs. If we do not change it then leadership maybe should be an independent item within About. 

@ricardoaat  worked on the menu a while ago. Adding him in case he wants to provide any feedback.

The structure you propose makes sense and makes things tidy, but I wonder if there is any important item within the proposed headers we would like people to see straight away that it worth promoting to the root level.

**Comment by ricardoaat** [comment]
Instead of Support we could use something like "Getting started" or "Usage":

- Getting started
  - Wiki
  - Tutorials
  - Software

Perhaps Governance could be included as a subsection of the Community page; which I realize now it will be removed.

**Comment by ljgarcia** [comment]
I like "Getting started"

**Comment by justinccdev** [comment]
I like "Usage" instead of "Getting Started" or "Usage" (ideally Using Bioschemas but I expect that's too long).  Software isn't really about getting started.

**Comment by AlasdairGray** [comment]
How about "Resources"?

**Comment by AlasdairGray** [comment]
@ricardoaat wrote

> Perhaps Governance could be included as a subsection of the Community page; which I realize now it will be removed.

These pages are doing two different things, which is why I separated them out. The Community page is saying which projects and external communities are engages with bioschemas while governance is going to be about the governance structures that we have. The Steering Committee are in the process of further developing these structures.

**Comment by ljgarcia** [comment]
So, we just need a consensus regarding 

- Getting started/Usage/Resources
  - Wiki
  - Tutorials
  - Software

and then we can close this issue?

So far we have 2 votes for "Getting started" (@ricardoaat and me), 1 vote for "Usage" (@justinccdev ), and 1 vote for "Resources" (@AlasdairGray). Could please @rajido, @sarala, @CaroleGoble and @nsjuty cast their vote so Ricardo can implement and then close this issue?

@ricardoaat anything else missing to close this issue?

**Comment by justinccdev** [comment]
Changing my vote to "resources", I like that suggestion better

**Comment by ricardoaat** [comment]
@ljgarcia @AlasdairGray I understand, we might need a link for the Community page then, and a different name for the Community group. Or perhaps something like:

- Community
  - Overview (Formerly "Community" link)
  - Join
  - Meetings
  - People
  - Groups
  - Organisations

**Comment by ljgarcia** [comment]
I like your proposal, overview sounds good to me

**Comment by ljgarcia** [comment]
I think all these changes have been implemented already, have not they @ricardoaat ? If not, which ones are still standing?

**Comment by ricardoaat** [comment]
@ljgarcia Not yet, the changes proposed here are:
- Home
- Specifications
  - Recommendation/Current
  - Drafts
  - Live Deploys
- Resources/Getting Started/Resources
  - Wiki/Documentation
  - Tutorials
  - Software
- Community
  - Overview
  - Join
  - Meetings
  - People
  - Groups
  - Organisations
- About
  - Governance
  - Publications
  - Funders
  - Logos

**Comment by njall** [comment]
I think Getting Started would be the right tab heading. A lot of people using Bioschemas (in my experience) aren't developers/techy. 

I looked at some websites that encourage non-techy people to use techy products/services (e.g. Wordpress, Wix, Disqus) and most use Get Started as an inviting/re-assuring tab header.

**Comment by AlasdairGray** [comment]
I agree with @njall, Getting Started is what we need

**Comment by justinccdev** [comment]
I agree a Getting Started would be good.  However, I don't think it's the right place for "Wiki" or "Software".  I still think a resources menu would be better for those, quite possibly replacing the current software menu.

On the sites you mention, the call to action button is slap back in the middle rather than in the top-level menus.  Or if one wanted to keep the number of top-level items constantly, you could fold Meetings into About (and rename to events).

**Comment by ricardoaat** [comment]
@justinccdev but that would mean we need to add a new group menu; the main goal is to have no more than 5 group menu (right now there is one to many). Having documentation/wiki on getting started sound just about right, since its where the instructions to get into Bioschemas will be and how to benefit from it i.e, software tools.

**Comment by ljgarcia** [comment]
Get started sounds perfect. It is a very common expression for all those documents, software, wikis, tutorials, etc. helping people to get the most of a website, Bioschemas in this case.
Resources is rather generic, I would avoid it.

**Comment by justinccdev** [comment]
@ricardoaat It wouldn't because "Resources" would replace "Software", "Meetings" would move to "About" and there would be a new "Getting Started" button.  I don't think software or wiki should be under "Getting Started", I simply wouldn't look in that place for that info.

If you can point me at existing websites that do so I can revise my opinion or nobody agrees with me then I can be outvoted.  It's only a website after all.

**Comment by ricardoaat** [comment]
@justinccdev Even with Meetings inside the group menu about, we would have 6 Group menus if we were to have "Resources" (former Software) as one of them.

Would this approach acceptable?:

- Home
- Specifications
  - Recommendation/Current
  - Drafts
  - Live Deploys
- Getting started
  - Documentation (Instead of wiki)
  - Tutorials
  - Resources (former Software)
- Community
  - Overview
  - Join
  - Meetings
  - People
  - Groups
  - Organisations
- About
  - Governance
  - Publications
  - Funders
  - Logos

Please vote

**Comment by justinccdev** [comment]
-1, having resources instead of software under getting started is even worse than software imo.

Why is it so critical to drop to 5 menus?  It looks fine on my browser.

**Comment by ricardoaat** [comment]
@justinccdev You are right, 6 looks just fine.

What about this approach:

- Home
- Specifications
  - Stable/Recommendation/Current
  - Drafts
  - Live Deploys
- [Getting started/Training Portal/Wiki](https://bioschemas.gitbook.io/training-portal/) (In progress)
- Support tools/Software/Support software
- Community
  - Overview
  - Join
  - Meetings
  - People
  - Groups
  - Organisations
- About
  - Governance
  - Publications
  - Funders
  - Logos

**Comment by justinccdev** [comment]
How about

* Getting started
* Resources
  * Software
  * Wiki

I can see where https://bioschemas.gitbook.io/training-portal/ could subsume the information in https://github.com/BioSchemas/specifications/wiki/Technical, but I still think you want a [wiki landing page|https://github.com/BioSchemas/specifications/wiki] for miscellanea such as meetings and minutes.

Perhaps the current software page can be divided into Creation Tools and Consumption Tools.

**Comment by AlasdairGray** [comment]
[Galaxy](https://galaxyproject.org/) have "Deploy & Develop" for what we are suggesting for "Resources".

I'll start a branch to make this last proposal so we can try and get this closed

**Comment by AlasdairGray** [comment]
I've created this structure on the [website-menu](https://github.com/BioSchemas/bioschemas.github.io/tree/website-menu) branch.

I wonder if 
- the contents of "Specifications" should be under "Develop & Deploy"
- Getting Started should be just a link to the Training Portal; the link to the wiki does not lead to a useful resource.

This would give
- Home
- Training Portal
- Develop & Deploy
  - Profiles
  - Draft Profiles
  - Software
  - Wiki
  - Live Deploys
- Community
  - Overview
  - Join
  - Meetings
  - People
  - Groups
- About
  - Governance
  - Publications
  - Funders
  - Logos
