### ISSUE TITLE
File name "Pscan:jsonld.json" not supported on Windows

### ISSUE THREAD

**Issue by frmichel** [BioSchemas/specifications#206]
Hi, 

Just a minor issue. I've cloned the repository on my Win10 system with Github desktop. Windows can't manage files with a ":" in the name, as a result "Pscan:jsonld.json" ends up renamed into "Pscan". What follows seems simply ignored.

It appears as a change. Not a big deal, but the risk is that someone commits this eventually.

Unless this name is a requirement from some tools you use, maybe it would be good to rename it, for instance to Pscan_jsonld.json.

Franck.

**Comment by AlasdairGray** [comment]
Is that the file in the tools example folder?
https://github.com/BioSchemas/specifications/tree/master/Tool/examples

I think it should be fine to change the name

**Comment by frmichel** [comment]
Yes, I forgot to provide the full path name, sorry about that.

**Comment by AlasdairGray** [comment]
@ricardoaat @justinccdev do you know of any reason we cannot just rename this file?

I don't believe that we are doing any automatic processing over the example folders.

**Comment by ricardoaat** [comment]
I think its safe to rename it, I'm not running any automated process on those folders.
