### ISSUE TITLE
Specification for container image, recipe?

### ISSUE THREAD

**Issue by vsoch** [BioSchemas/specifications#207]
hey bioSchemas! 

I am wondering if we could have discussion about adding a general specification for a container image, and recipe (and an instance would be instantiation of those things). For example, [the open container initiative](https://github.com/opencontainers/image-spec) (oci) image-spec would give a pretty good start to the valuable [fields](https://github.com/opencontainers/image-spec/blob/master/manifest.md) for the specification. My thoughts are something like:

```
Thing > CreativeWork > SoftwareApplication > Container > ContainerImage
```
And then attributes would be those in the image spec linked above, along with the (not described) that are important like the `ContainerRecipe` (Dockerfile). I think in that a container runtime is associated with an image, it would be a separate thing that can be a field of a `ContainerImage` (can I do that?) e.g.,

```
Thing > CreativeWork > SoftwareApplication > Container > ContainerImage
                                                                                            > ContainerRuntime
```

Then we would define them separately, but say "ContainerImage ubuntu:latest has ContainerRuntime entrypoint /bin/bash." What I'm not sure about is where to put the recipe (e.g., a Dockerfile or Singularity recipe) that is the text file to generate the container. Technically you don't need to have it (a container can be assembled in many ways) but it's always the case that a recipe generates a particular container image and runtime. We could possibly put it equally alongside

```
Thing > CreativeWork > SoftwareApplication > Container > ContainerImage
                                                                                            > ContainerRuntime
                                                                                            > ContainerRecipe
```

OR have it as an attribute? I'm thinking ahead - when we instantiate two different container technologies into the above, a "Container" could generally be called "ubuntu:latest" but be offered via two images from separate technologies (again Singularity vs. Docker) and this is an interesting use case:

```
singularity pull docker://ubuntu:latest
```
because for Docker you would have:

```
- Container: ubuntu:latest
   - ContainerRecipe: Dockerfile
   - ContainerImage: (this would be a list of layers associated with a sha, and we would probably represent the shasum but not the entire manifest list of layers)
  - ContainerRuntime:entrypoint = /bin/bash
```
and then for Singularity you would have almost the same thing:

```
- Container: ubuntu:latest
   - ContainerRecipe: Dockerfile
   - ContainerImage: A single binary
  - ContainerRuntime:entrypoint = /bin/bash
```

which is why I think recipe should not be a child of ContainerImage. 

I have a Dataset that I would use as an example to start, it's actually *just* the recipes for the containers.  http://github.com/vsoch/dockerfiles I'd like to first PR here to add some representation of a container, and then use it there. And one followup question - how do your users typically interact with schemas? For example, I'm looking for this --> https://github.com/schemaorg/schemaorg/issues/2061 Thanks!

**Comment by ypriverol** [comment]
I recommended to do this in collaboration with containers communities such as Biocontainers or Dockerstore

**Comment by vsoch** [comment]
Thanks! Discussion (after I do some work) I hope to at least start here https://github.com/opencontainers/image-spec/issues/751 and I’ve chat with @rajido a bit and will also be talking with Guha. The specifications I already created a home for that is (working on it now!) to have clean testing and it mirrors exactly what bios chem as has set up (thanks @ricardoaat!) I have a nice set of things on my plate so I don’t need feedback atm but will post with updates for sure.

**Comment by vsoch** [comment]
Quick update: started [ContainerRecipe](https://openschemas.github.io/spec-container/specifications/ContainerRecipe/) draft. I'll be doing the Image/Distribution and others soon, will post here when I do.

**Comment by vsoch** [comment]
[ContainerImage](https://github.com/openschemas/specifications) and ContainerRecipe are added, going to close here to continue discussion with OCI. Thanks for your feedback!
