### ISSUE TITLE
From which field in a Mapping do we derive the parent?

### ISSUE THREAD

**Issue by vsoch** [BioSchemas/specifications#209]
For example, for "DataCatalog" I would want to know it's under "CreativeWork." There are a few instances in the mapping, and I'm wondering which one is used to derive this field? I was looking for something in one of the sheets along the lines of "parent" but didn't see anything. Thanks!

**Comment by AlasdairGray** [comment]
The type hierarchies are shown either on the schema.org page or the bioschemas page. The display of all profiles and types show the hierarchy at the top.

The crosswalk spreadsheets do not make the information readily available. This is not something that we can fix at this point.
