### ISSUE TITLE
Unify training and training materials and add CourseInstance to specs

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#211]
Hi @njall 

I saw you created a new group Training. I suppose the previous one Training Materials can be removed, could not it? Also, CourseInstance is not listed as one of the specs that group is working on. And, when you update those pages, could you please add @ricardoaat and me to the list of contributors? We are working on training material for Bioschemas and FAIRness for training materials, both of them related to the training group and the training materials spec.

And, may I suggest using PR next time?

Thanks!

**Comment by njall** [comment]
Hey @ljgarcia, sure - The logic was to extend the existing TrainingMaterial group into a broader Training group which would include the new Course and CourseInstance specs. 

Sorry about the direct push - someone said I could push directly, but it would make more sense to do PRs. 

We really could do with two very distinguishing names for the group of people interested in developing the training specifications, and the people creating new training resources.

Weere you planning on using Training as the group name?

**Comment by ljgarcia** [comment]
Hi @njall 

It totally makes sense to have a Training group working on specs TrainingMaterial, Course and CourseInstance as they are highly related. I woud say just one group is enough, and Training sounds good to me, what to do you think?

All the listed groups refer to people working on specifications. We do not have groups for people developing tools or creating training materials, but it makes sense to have them actually. I will ask about it.

Thanks!

**Comment by AlasdairGray** [comment]
I agree that we only really need the one group for this. Can we just rename the existing TrainingMaterial Group to Training?

**Comment by njall** [comment]
Sure, I can sort it out. I've already copied TrainingMaterial into the new Training group, I just need to delete the old TrainingMaterial group now... The longer version of renaming :P
 
Do you mind also if I go ahead and add all the members of GOBLET who have been helping us construct the Training specifications into the group?

**Comment by AlasdairGray** [comment]
Please do

**Comment by AlasdairGray** [comment]
@njall is this now complete?
