### ISSUE TITLE
BioSchema Protein example does not use BioSchema:Protein

### ISSUE THREAD

**Issue by JervenBolleman** [BioSchemas/specifications#218]
The context of the Protein bioschema example as of https://github.com/BioSchemas/specifications/commit/4b4164c7e05fe142608e7c353dd40741e7d5e36e#diff-9f02adf3a4b9af68b14034d923b4c66c

Means that there is no useage of bioschema:Protein, just bioschema:BioChemEntity and PRO:PR_000000001. 

```json-ld
{
  "@context": [
    "http://schema.org",
    {
      "@base": "http://schema.org"
    },
    {
      "Protein": {
        "@id": "http://purl.obolibrary.org/obo/PR_000000001"
      }
    } 
  ],
  "@type": ["BioChemEntity", "Protein"],
  "identifier": "P00519"
}
```
Turns into 
```turle
[ <http://schema.org/identifier> <http://schema.org/P00519> .
 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.obolibrary.org/obo/PR_000000001> .
 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/BioChemEntity> .
]
```

Which of course also has the issue with the identifier being interpreted wrongly.

**Comment by AlasdairGray** [comment]
@JervenBolleman The short answer is that there is no bioschemas:Protein, we reuse terms from domain ontologies. So the context file is correct to define Protein to be http://purl.obolibrary.org/obo/PR_000000001. We use this alongside the proposed schema:BioChemEntity to say that this BioChemEntity is a Protein.

**Comment by JervenBolleman** [comment]
Then what is the [bioschema:Protein spec](http://bioschemas.org/devSpecs/Protein/)? it's an additional type there to be PR_000000001 because if it is what you say it is then practically we never say in triples.

```turtle
[] a bioschema:Protein .
```
we will always say

```turtle
[] a pro:PR_000000001 .
```

Which basically is telling yandex, google etc.. that they need to understand PRO and SIO. A big difference from what they have done in schema.org. There they just have one namespace (schema.org) for all concepts and properties instead of multitudes as suggested here. 

In any case this still leaves the identifier issue to be fixed.

Of course the semantics of what is being said here is quite different as well. PRO being an ontology would want us to use subClassOf relations not rdf:type relations.

This turns into issues for PRO not being able to use BioSchemas as that will affect their modelling.
i.e. taking a BioSchema RDF of PRO representation and mixing it with the PRO OWL/RDF representation will lead to issues with punning, OWL full in stead of OWL DL and maybe other side effects. Has this been tested to never be a possible issue?

**Comment by ljgarcia** [comment]
From now on, I will include http://bioschemas.org/context.jsonld rather using a explicit context. @AlasdairGray please let us know whenever the context is ready.

**Comment by ljgarcia** [comment]
@JervenBolleman would you mind to provide some comments for the example below? The idea used there is as follows: 
* UniProtKB dataset provides data records, one protein entry corresponds to one record in this case
* UniProtKB data records have unique PURL identifiers
* UniProtKB data records refer to a specific BioChemEntity, i.e., a Protein (however it gets defined in the Bioschemas context) and it links to it via _mainEntity_
* A Protein in UniProt uses its accession as identification, it does not have a PURL (or any other global unique indentifier that will take you to a web page) on its own
* The record main entity, i.e., the Protein, is related to other entities contained in other data records, e.g., a Protein is associated with a disease, and a disease in UniProt has its own record identified by a PURL identifier
* There are no web pages in UniProt for genes, so no gene information is embedded

```
{
  "@context": [
    "http://schema.org",
    "http://bioschemas.org/context.jsonld"
  ],

  "@type": "DataRecord",
  "@id": "http://purl.uniprot.org/uniprot/P00519",

  "identifier": "http://purl.uniprot.org/uniprot/P00519",

  "isPartOf": {
    "@type": "Dataset",
    "@id": "http://www.uniprot.org/uniprot"
  },

  "dateCreated": "1986-07-21",
  "dateModified": "2017-03-15",

  "distribution": {
    "@type": "DataDownload",
    "url": "http://www.uniprot.org/uniprot/P00519.fasta"
  },

  "url": "http://www.uniprot.org/uniprot/P00519",
  "sameAs": "http://identifiers.org/uniprot/P00519",

  "citation": [{
    "@id": "http://www.identifiers.org/pubmed/10194451",
    "@type": "ScholarlyArticle",
    "headline": "A novel SH2-containing ...",
    "datePublished": "1999-04-15",
    "sameAs": [
      "https://www.ncbi.nlm.nih.gov/pubmed/10194451",
      "http://europepmc.org/abstract/MED/10194451",
      "http://purl.uniprot.org/citations/10194451"
    ]
  },
    {
      "@id": "http://www.identifiers.org/pubmed/9037071",
      "@type": "ScholarlyArticle",
      "headline": "Regulation of DNA ...",
      "datePublished": "1997-02-18",
      "sameAs": [
        "https://www.ncbi.nlm.nih.gov/pubmed/9037071",
        "http://europepmc.org/abstract/MED/9037071",
        "http://purl.uniprot.org/citations/10194451"
      ]
    }
  ],

  "mainEntity": {
    "@type": ["BioChemEntity", "Protein"],

    "identifier": "P00519",

    "name": "ABL1",
    "alternateName": ["ABL", "JTK7"],
    "description": "Function: Non-receptor tyrosine-protein kinase that plays a role...",

    "isContainedIn": {
      "@type": ["BioChemEntity", "Taxon"],
      "mainEntityOfPage": {
        "@type": "DataRecord",
        "@id": "http://purl.uniprot.org/taxonomy/9606"
      }
    },

    "associatedWith": {
      "@type": "MedicalCondition",
      "mainEntityOfPage": {
        "@type": "DataRecord",
        "@id": "http://purl.uniprot.org/diseases/DI-03735"
      }
    },

    "transcribedFrom": {
      "@type": ["BioChemEntity", "Gene"],
      "identifier": "ABL1",
      "name": "ABL1"
    }
  }
}
```

**Comment by JervenBolleman** [comment]
@ljgarcia this is more correct than the current example. But without knowing the context I can't be sure of what the RDF output is and therefore can't say if it is correct. In any case it is a big divergence from how Ensembl, PRO and UniProt approach this right now.

Also UniProt Taxon's are class based not instance based.
The Disease URIs are also not correct strip the DI- please.

isContainedIn gives rise to problems as well. As currently specified it means a secreted Protein stops being a Protein to moment it leaves the cell (issue common to PRO to be honest). 

What the up:organism and related concepts in Ensembl mean is that this Protein is derived from a gene expressed from a genome which is a member of the genomes expressed by a Taxon. Which is a whole lot of fluffy words that need to be replicated and isContainedIn doesn't do the same.  

To summarize the current situation is
```turtle
<https://www.uniprot.org/uniprot/P00519> a schema:webPage
        schema:mainEntity <http://purl.uniprot.org/uniprot/P00519> .
<http://purl.uniprot.org/uniprot/P00519> a up:Protein ;
        up:sequence <http://purl.uniprot.org/isoform/P00519-1>,
                              <http://purl.uniprot.org/isoform/P00519-1> .
<http://purl.uniprot.org/isoform/P00519-1> a up:Sequence .
```

Becomes

```turtle
<https://www.uniprot.org/uniprot/P00519> a schema:webPage
        schema:mainEntity <http://purl.uniprot.org/uniprot/P00519> .
<http://purl.uniprot.org/uniprot/P00519> a bioschema:DataRecord ;
        schema:mainEntity <http://purl.uniprot.org/isoform/P00519-1> .
<http://purl.uniprot.org/isoform/P00519-1> a obo:PR_000000001  .
```

Of course for PRO the issue would be worse in reasoning terms.
```turtle
obo:PR_P00519 rdfs:subClassOf obo:PR_000000001 .
```
becomes
```turtle
obo:PR_P00519 rdf:type obo:PR_000000001 .
```
This is because schema.org has an instance based world view while SIO and PRO are class based ontologies.

I think, the Protein examples need to be worked out in turtle as the JSON-LD context hides to many critical details in an area where there is already enough confusion.

**Comment by ljgarcia** [comment]
Great explanation @JervenBolleman, thanks so much!

Regarding
> Also UniProt Taxon's are class based not instance based.

This is kind of the same that happens with proteins in UniProtKB, is not it? Rather than representing a specific protein existing as a physical object, they represent a class encapsulating such protein in a generic way. Am I following your comment correctly? If so, then having taxon as a BioChemEntity profile, as it happens with Protein, would work. The relation between a protein and a taxon should be a different one though, more on it on below.

Now, regarding 
> What the up:organism and related concepts in Ensembl mean is that this Protein is derived from a gene expressed from a genome which is a member of the genomes expressed by a Taxon. Which is a whole lot of fluffy words that need to be replicated and isContainedIn doesn't do the same.

What we could do then goes like
```
{
  "@type": ["BioChemEntity", "Protein"],
  "derivesFrom": {
    "@type": "BioChemEntity",
    "mainEntityOfPage": {
      "@type": "DataRecord", 
      "@id": "http://purl.uniprot.org/taxonomy/9606"
    }
  }
}
```

About the 
> obo:PR_P00519 rdf:type PR_000000001 .
something to really look at, thanks!

**Comment by ljgarcia** [comment]
@JervenBolleman coming back to containedIn vs derivesFrom. What if the property name is changed to isPartOfEntity, defined as "relation between a part and its whole"?

@frmichel The taxon profile you have defined, that one corresponds to classes rather than instances, right? I mean, the taxon for human corresponds to all "possible" humans rather than a particular human individually. If so, does it make sense for you saying that a protein is-part-of taxon? Please note that a protein is also a class rather to a particular individual instance of a proten. Would be protein derives-from taxon better? Or maybe protein develops-from taxon?

@micheldumontier @deniseome, would you mind to have a look to this thread? Your input would be appreciate it.

Many thanks to all for your comments!

**Comment by frmichel** [comment]
Hi @ljgarcia,

Hum... that's a tough one. Typically about balancing between "pragmatic use of vocabularies" and "beauty of models". ;)

> the taxon for human corresponds to all "possible" humans rather than a particular human individually.

Right. Biologists have endless philosophical discussions as to the definition of a taxon vs. a taxon concept vs. a taxon name etc. (see https://github.com/tdwg/tnc/issues/1). Yet, roughly speaking, a taxon is a group of biologic organisms that share certain properties. The circumscription of taxon is not always clearly defined, and it changes over time along with new evidences.

> If so, does it make sense for you saying that a protein is-part-of taxon?

That would definitely sound awkward. A part of a taxon is a group of individuals, like a species is a subset of a genus. Even a single individual is a part of a taxon.

I would see a protein as possibly a part of an individual, but even here I'm not sure that "is-part-of" is the appropriate relation. I would rather suggest something like "is-a-constituent-of" (that's an hypothetical property).

> Please note that a protein is also a class rather to a particular individual instance of a protein.

Do you mean that the protein term in Bioschemas.org represents a class of somehow similar proteins? 
Even so, that does not make a real difference I guess, with respect to the relationship to a taxon.

> Would be protein derives-from taxon better? Or maybe protein develops-from taxon?

I'm not skilled enough in biology to answer that question. What about "is-a-constituent-of" that I mentioned above, to say that a protein is-a-constituent-of a taxon, i.e. it is a part of the organisms in this taxon.
I can also think of something like a 3-parties relations "has-function-in" denoting the fact that a protein has a certain function in an group of organisms.

My 2 cents...

Franck.

**Comment by micheldumontier** [comment]
there are lots of issues here. Jerven's formulation of the ideal case makes sense to me

     <https://www.uniprot.org/uniprot/P00519> a schema:webPage
        schema:mainEntity <http://purl.uniprot.org/uniprot/P00519> .
     <http://purl.uniprot.org/uniprot/P00519> a up:Protein ;
        up:sequence <http://purl.uniprot.org/isoform/P00519-1> .
     <http://purl.uniprot.org/isoform/P00519-1> a up:Sequence .

however, in his reformulation, 

    <https://www.uniprot.org/uniprot/P00519> a schema:webPage
        schema:mainEntity <http://purl.uniprot.org/uniprot/P00519> .
    <http://purl.uniprot.org/uniprot/P00519> a bioschema:DataRecord ;
        schema:mainEntity <http://purl.uniprot.org/isoform/P00519-1> .
    <http://purl.uniprot.org/isoform/P00519-1> a obo:PR_000000001  .``

i'm not sure i fully agree. i think that a web page, a record, and an entity are different, and have different attributes.  the issue is what Jerven indicates, that typing <http://purl.uniprot.org/uniprot/P00519> with rdf:type to PRO, is technically not correct, because it should be a rdfs:subClassOf relation rather than an rdf:type relation. 

as far as taxonomic relations are concerned, we can imagine that there are instances of a species (e.g. a specific person is an instance of taxon:9606), but when it comes to a class of proteins, the relation is different. what we want to say is that the species human typically express such proteins, and that instances of those proteins can be found in (are located in; are a part of) individuals of the species. modeling class-class relations in rdf is through a simple relation between the two classes, so you can use isPartOf as a simplying relation.

**Comment by JervenBolleman** [comment]
@micheldumontier The ideal case is the existing pure schema.org case on www.uniprot.org since 2014 ;) nothing new there. The reformulation is bioschema:protein (as of draft 0.5).

@ljgarcia Should we split this issue into multiple ones and close this one as it's overbroad by now?

**Comment by AlasdairGray** [comment]
> Should we split this issue into multiple ones and close this one as it's overbroad by now?

@JervenBolleman What would you see as being the separate issues?

**Comment by ljgarcia** [comment]
@JervenBolleman agree, let's going to split it in some issues as follow:

1. [Define a Bioschemas context](https://github.com/BioSchemas/specifications/issues/219)
2. [Find the right relation for partOf/isPartOf at BioChemEntity level](https://github.com/BioSchemas/specifications/issues/221)
3. [Find the right relation between Protein and Organism/Taxon](https://github.com/BioSchemas/specifications/issues/222)

I am not closing this one in case I have missed anything, If so, please feel free to create a new issue and link it back to this one.

Thanks all!

**Comment by AlasdairGray** [comment]
Hopefully the new [proposal](https://lists.w3.org/Archives/Public/public-bioschemas/2018Oct/0007.html) fixes these issues.

**Comment by AlasdairGray** [comment]
All existing examples were deprecated due to the change of approach in Bioschemas. Some new examples were developed during the Biohackathon last week.

In the future we need to version our examples so that it is clear which profile version they correspond to.
