### ISSUE TITLE
isBasisFor/basedOn or derivesInto/derivesFrom

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#220]
@otienoanyango  I think you are using isBasisFor/basedOn to express the relation between a protein and a protein structured. Do you think [derivesInto](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0001000) and [derives into](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0001001) could be used instead?

@4ndr01d3 not sure you use isBasisFor/basedOn somewhere, if so, please have a look to the properties I mentioned above.

isBasisFor does not exist in schema.org and basedOn is reserved for CreativeWork so we need alternatives

Thanks!

**Comment by otienoanyango** [comment]
@ljgarcia Let me discuss this with my team and get back to you tomorrow

**Comment by 4ndr01d3** [comment]
Hey @ljgarcia, we do use those relationships. I'll check if the `derives` versions of it actually apply to us and will let you know.

**Comment by ljgarcia** [comment]
Hi @4ndr01d3 and @otienoanyango 

Please also have a look to [developsFrom](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002202) and [developsInto](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002203) as those could be useful as well, maybe better than derivesFrom/derivesInto

Thanks!

**Comment by ljgarcia** [comment]
Looking closer to [derivesInto](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0001000) and [derives into](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0001001) they will not work. 

See definition for derives from:
> a relation between two distinct material entities, the new entity and the old entity, in which the new entity begins to exist when the old entity ceases to exist

Please have a look instead to developsFrom/developsInto

**Comment by AlasdairGray** [comment]
The outcome of this discussion should be fed into the [proposal](https://lists.w3.org/Archives/Public/public-bioschemas/2018Oct/0007.html) for new types and properties

**Comment by ljgarcia** [comment]
Already solved with the latest specification from the BioHackathon:

Protein relates to a ProteinStrucutre via hasSequenceAnnotation
ProteinStructure relates to Protein via hasAssociatedBioChemEntity

Note: A suggestion to rename ProteinStructure to BioChemStructure has been recorded at the F2F agenda
