### ISSUE TITLE
Find the right relation for partOf/isPartOf at BioChemEntity level

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#221]
Currently we are defining isContainedIn/contains as equivalent to isPartOf/hasPart. The use of "contain" there has raised some confusion. Should we move to isPartOfBioChemEntity/hasPartBioChemEntity?

@CaroleGoble @AlasdairGray @rajido @micheldumontier @frmichel @Kerruba any thoughts?

**Comment by AlasdairGray** [comment]
From my discussions with Dan, the schema.org community are against general meronomy or partonomy relationships. We should express the particular relationship that is being captured.

**Comment by ljgarcia** [comment]
@AlasdairGray yes, that was mentioned during one of the Bioschemas workshops last year. 

What would be your proposal? removing isContainedIn/contains and let profiles to define their own meronomy relations if needed?

What about better defining how we expect that meronomy to be used? isPartOf/hasPar exist for CreativeWork, still it might be odd to use it to express something like MovieClip hasPart Dataset. But saying tha Book hasPart Chapter totally makes sense.

**Comment by AlasdairGray** [comment]
I'm waiting more feedback from Dan, but it would be good for us to have more examples of how the relationships are to be used in different contexts. Ideally if there are different names for these relationships then we could look at adding in more specific meronomy relationships.

**Comment by AlasdairGray** [comment]
The new [proposal](https://lists.w3.org/Archives/Public/public-bioschemas/2018Oct/0007.html) is now available, but we still need to resolve the correct names for some of these relationships

**Comment by AlasdairGray** [comment]
The new proposals are moving forward with `isPartOfBioChemEntity` and `hasBioChemEntityPart`. We may also be proposing more specific relationships where we see the need.
