### ISSUE TITLE
Find the right relation between Protein and Organism/Taxon

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#222]
For some saying that a protein is-part-of taxon sounds odd, [see original comment](https://github.com/BioSchemas/specifications/issues/218#issuecomment-429350564) but for others it sounds ok, [see last paragraph in original comment](https://github.com/BioSchemas/specifications/issues/218#issuecomment-429378292).

Rather than using is-part-of (currently named as isContinedIn at BioChemEntity), we could use and adapt [schema:location](https://schema.org/location). 

Other possibilities reuisng the Relation Ontology would be [derivesInto](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0001000) and [derives into](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0001001)  or maybe [developsFrom](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002202) and [developsInto](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002203)

@JervenBolleman @micheldumontier @AlasdairGray @CaroleGoble @frmichel any thoughts?

In case you are interested, there is a [related discussion regarding the relation between protein and protein annotation, and protein and protein structure](https://github.com/BioSchemas/specifications/issues/220).

**Comment by AlasdairGray** [comment]
> Rather than using is-part-of (currently named as isContinedIn at BioChemEntity), we could use and adapt [schema:location](https://schema.org/location).

Please avoid doing this. We need to respect the existing location property and not morph it into something that loses its meaning.

**Comment by ljgarcia** [comment]
> 
> 
> > Rather than using is-part-of (currently named as isContinedIn at BioChemEntity), we could use and adapt [schema:location](https://schema.org/location).
> 
> Please avoid doing this. We need to respect the existing location property and not morph it into something that loses its meaning.

Thanks for the warning. We will avoid it for the protein profile. 

However, we already do this a bit for [BioChemEntity](http://bioschemas.org/types/BioChemEntity/) which includes more expected types than the original property at schema.org. Should this need to be modified, I suggest creating a new issue.

**Comment by AlasdairGray** [comment]
Yes we will need to update BioChemEntity so as not to overload the location property

**Comment by ljgarcia** [comment]
Looking closer to [derivesInto](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0001000) and [derives into](https://www.ebi.ac.uk/ols/ontologies/ro/properties?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0001001) they will not work. 

See definition for derives from:
> a relation between two distinct material entities, the new entity and the old entity, in which the new entity begins to exist when the old entity ceases to exist

We still have in the run developsFrom/devlopsInto, please have a look.

Another possibility [hasExpression](http://semanticscience.org/resource/SIO_000420)/[isExpressionOf](http://semanticscience.org/resource/SIO_000421.rdf) @micheldumontier those come from SIO, would it make sense to reuse them for protein related to taxon?

**Comment by ljgarcia** [comment]
Or we could go for up:Organism. @JervenBolleman, would it make sense to use that one?

**Comment by JervenBolleman** [comment]
I would rather see a new `bioschema:organism` property, that our [`up:organism`](http://purl.uniprot.org/core/organism) can be a `rdfs:subPropertyOf` of. There are validation related OWL axioms that can trip someone up related to `up:organism`, of course these can be removed and should in any case be replaced with ShACL when we have time.

Today using `up:organism` in a triple infers that the subject of that triple is a `up:Protein` or a `up:Sequence`.

**Comment by AlasdairGray** [comment]
Would `bioschemas:organism` have wider applicability, e.g. in Gene and Sample?

**Comment by micheldumontier** [comment]
in light of the conversation about schema.org preferring specific relations, i'm ok with a new property bioschema:organism, with general utility to associate any biochementity with an organism.

**Comment by JervenBolleman** [comment]
I believe that every property and type added to bioschemas must have the widest possible interpretation of a concept, so yes it should be applicable for Gene, Sample and more.

**Comment by AlasdairGray** [comment]
The new [proposal](https://lists.w3.org/Archives/Public/public-bioschemas/2018Oct/0007.html) includes the use of an `organism` property.

**Comment by AlasdairGray** [comment]
The `organism` property has been renamed to `taxonomicRange`.
