### ISSUE TITLE
DataCatalog, DataRecord, BioChemEntity, DataSet for Alliance of Genome Resources pages

### ISSUE THREAD

**Issue by kyook** [BioSchemas/specifications#224]
The UniProt examples seem to have taken a turn to specify proteins and UniProt pages, which I'm not seeing as directly transferable to MOD pages and especially Alliance pages.  The immediate confusion I come across is how DataCatalog, DataRecord, and  DataSet  are defined.  So I'm stuck, again.

The way I see our pages in this structured language is that 

- [ ] Alliance and MOD sites are DataCatalogs
- [ ] A page in either is a DataRecord for a specific BioChemEntity (for Alliance pages, these are Genes, Disease (medicalCondition), and Phenotype for now; for a MOD it is expanded to Protein, Variation, Expression Pattern, etc.)
- [ ] Within a DataRecord for a BioChemEntity are various DataSets. 
- [ ] A DataSet for an Alliance or MOD BioChemEntity would be something like all GO annotations, or all Disease annotations, or all Phenotype Annotations, etc. 
- [ ] The source for Alliance pages are MOD DataCatalogs but are not exactly the same, so it is not clear how to use the seeAs or seeAlso and it would be best to use something that indicates source, such as basedOn or something even more exact like culminationOf with each MOD URL for that page as values.
    - [ ] Alliance data for a given BioChemEntity are based on carefully determined properties that were deemed important and interoperable among the MODs so they exist in each of the MODs, but not all MOD data are represented in the Alliance view. 
   - [ ] Alliance data for a given BioChemEntity may contain data generated based on ortholog analysis that does get propagated back to the MODs, so does contain novel analysis. 
   -[ ] Further, data the MODs are not necessarily going to be in sync with Alliance data

Ok, I'll stop there as I'm sure I'm setting off a bit of a storm here. I eagerly await clarification...

**Comment by AlasdairGray** [comment]
I'm not familiar with Alliance and MOD, but I understand that they aggregate data from multiple sources. The question I have is are you trying to model this provenance of where you get the data in the schema markup that you are embedding in the page?

It might be easier if we talk through your scenario in a call.

**Comment by AlasdairGray** [comment]
I believe that this issue was resolved face-to-face at the Biohackathon last week
