### ISSUE TITLE
proposal for gene pages from the Alliance of Genome Resources

### ISSUE THREAD

**Issue by nathandunn** [BioSchemas/specifications#225]
Here is a rough proposal we'd come up with for gene display pages at the MODs.   We tried to incorporate the way all of the mods model and display gene pages and associated data, while doing what we hope is google best practices and incorporating existing standards and examples, especially WRT proteins.  

This specific example:

https://gist.github.com/nathandunn/6fefd97f5a5a5578e302b4623e52f990

would be attached JSON-LD data to this gene page: 

https://www.alliancegenome.org/gene/ZFIN:ZDB-GENE-001103-2 

Validation: 

https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fgist.githubusercontent.com%2Fnathandunn%2F6fefd97f5a5a5578e302b4623e52f990%2Fraw%2F0241e03e2548c2c71ab00802b176fec3f176f9c4%2FBioschemas%252520Example%2525203 

Comments:
- Symbol for gene is in the name field
- Name for gene is in alternateName, while symbol is in the name field.
- Version should be AGR dataVersion release

Questions:
- Should species go into “containedIn” or be renamed organism?  How do we handle multiple
-  species and strains?   Is there anything more standard for species that we could use (e.g., Wikipedia)?
- We combined automated and curated descriptions in the description field.   Should this be in multiple fields?
- How do we handle a LOT of data in the JSON-LD?   For example citations, associated diseases, etc.
- Should we add a count for that data with a link to the main page and a few choice (not sure how we determine this) examples or is there a better way?
- We can have direct associations for orthology on the gene page.  But all other data types we will have to somehow have a cutoff for direct annotations and provide the remaining annotations via a  “seeAlso” link for other data type pages (e.g., citations, phenotypes, etc.).   We will ALWAYS provide a “seeAlso”, but we will try to provide a count.  (is there a best-practice here?) Could we use dataset to collect the annotations types (phenotype, disease, literature…)?
- E.g., seeAlso:[“www.alliancegenome.org/gene/ZFIN:ZDB-asdfasdf123/phenotypes”] . . this should refer to a phenotypes page for this gene, that also has the compiled JSON-LD.   As an example: https://zfin.org/search?category=Expression&q=sox9b

**Comment by JervenBolleman** [comment]
Just quickly want to note you are falling into the Microdata additionalType trap. In JSON-LD this is just "@type".

**Comment by nathandunn** [comment]
@JervenBolleman  Are you proposing that we replace `additionalType` with `@type` within our schema? 

I think that sounds reasonable.  

I'm not sure what the "Microdata additionalType trap" is, but it sounds dangerous.

**Comment by JervenBolleman** [comment]
@nathandunn sorry for the exaggeration ;) yes it's exactly what I meant. AdditionalType in schema.org mostly exists for Microdata syntax, JSON-LD has "@type" and RDFa has "typeof" which accepts lists/arrays Microdata does not have this. 

> additionalType | An  additional type for the item, typically used for adding more specific  types from external vocabularies in microdata syntax. This is a  relationship between something and a class that the thing is in. In RDFa  syntax, it is better to use the native RDFa syntax - the 'typeof'  attribute - for multiple types. Schema.org tools may have only weaker  understanding of extra types, in particular those defined externally. 

For info for www.uniprot.org I decided to put all schema.org in RDFa, mostly to avoid doubling page sizes by repeating every literal and id twice or more to have a JSON-LD part.

**Comment by AlasdairGray** [comment]
What is the relationship between this issue and #224?

**Comment by AlasdairGray** [comment]
This example will need to be updated if the [proposal](https://lists.w3.org/Archives/Public/public-bioschemas/2018Oct/0007.html) is accepted by the community.

**Comment by nathandunn** [comment]
@JervenBolleman  Thanks.  I updated [the example](https://gist.github.com/nathandunn/6fefd97f5a5a5578e302b4623e52f990)  to reflect this.  I'm sure there will be more changes, though.

**Comment by nathandunn** [comment]
@AlasdairGray  There is some overlap between #224 and this.  I think, after talking with @kyook that we are replacing everything DataRecord with this as the greater specificity here is more desirable.   

At a higher-level, I'm unsure if an entire MODs should be DataCatalog or a DataSet or something else entirely, but that is definitely something we could follow up on later. .

**Comment by nathandunn** [comment]
@AlasdairGray  no problem updating the proposal with what is here (https://docs.google.com/document/d/1Cw9K25N1l-Lbet1cahJuFtYgNKiF76apGcCqJPSeuZg/edit#) with the exception that I don't think we should use DataRecord.     If there is an example based on this, that would be great.

**Comment by AlasdairGray** [comment]
Can we close this issue based on the outcomes of the Biohackathon?

**Comment by nathandunn** [comment]
Note.  Closing this based on outcome of the biohackathon.   Working on new spec.
