### ISSUE TITLE
Broken link to BioChemEntity

### ISSUE THREAD

**Issue by sillitoe** [BioSchemas/specifications#231]
In the specification documents (eg [ProteinAnnotation](http://bioschemas.org/specifications/ProteinAnnotation)), the link for BioChemEntity currently returns a 404.

Apparently this is a known issue - reporting here to keep track.

**Comment by AlasdairGray** [comment]
The link that is broken is the redirect from http://bioschemas.org/BioChemEntity to http://bioschemas.org/types/BioChemEntity/

**Comment by AlasdairGray** [comment]
Also applies if the forward slash is included at the end of the URL on all types, e.g. http://bioschemas.org/Sample/ should redirect to http://bioschemas.org/types/Sample/.

Note that http://bioschemas.org/Sample correctly redirects to http://bioschemas.org/types/Sample/

**Comment by AlasdairGray** [comment]
Commit https://github.com/BioSchemas/bioschemas.github.io/commit/48029615460ae38aa4a369217ebeb82849d199dc fixed the trailing `/` issue but still have a problem with BioChemEntity.

The problem also exists for LabProtocol, but works fine for Gene, Protein, and Sample.

The issue now seems to be that the redirects do not work for CamelCase types.

**Comment by AlasdairGray** [comment]
Instead of using redirects it seems that we could just have the types collection with a path of the root, i.e. change _config.yml to
```
# Collections
collections:
  types:
    output: true
    permalink: /:path/
```

This worked when I tried it on my local machine.

**Comment by AlasdairGray** [comment]
Seeking help from GitHub Community Forum 
https://github.community/t5/GitHub-Pages/CamelCase-Redirect-not-working/m-p/15386#M1184

**Comment by AlasdairGray** [comment]
Issue was fixed in [pull request 166](https://github.com/BioSchemas/bioschemas.github.io/pull/166). Redirects should have been defined in an array.
