### ISSUE TITLE
updated needed for MolecularEntity documentation of the SMILES property 

### ISSUE THREAD

**Issue by egonw** [BioSchemas/specifications#241]
To explain that the `\` needs to be escaped in at least JSON-LD and Turtle.

**Comment by AlasdairGray** [comment]
Where should this update be made? Is it in the descriptive text of the property in the crosswalk? 

It would be good to have this shown in an example in the crosswalk document.

**Comment by egonw** [comment]
In the descriptive text. I think people should be aware that in some formats they may need to escape the `\` character.

**Comment by AlasdairGray** [comment]
Pull request now approved
