### ISSUE TITLE
move MolecularEntity and ChemicalSubstance into this repo

### ISSUE THREAD

**Issue by egonw** [BioSchemas/specifications#242]
@AlasdairGray, what would be the best place?

Curretn ShEx's:

* https://github.com/elixir-europe/BioHackathon/blob/master/interoperability/Bioschemas/MolecularEntity.shex
* https://github.com/elixir-europe/BioHackathon/blob/master/interoperability/Bioschemas/ChemicalSubstance.shex

**Comment by AlasdairGray** [comment]
For the Protein profile we currently have the ShEx sitting in 
https://github.com/BioSchemas/specifications/tree/master/Protein

So the analogous location for MolecularEntity would be
https://github.com/BioSchemas/specifications/tree/master/MolecularEntity

And for ChemicalSubstance it would be
https://github.com/BioSchemas/specifications/tree/master/ChemicalSubstance
(This folder would need to be created)

**Comment by AlasdairGray** [comment]
These folders should now exist. Please state in the filename the version number, e.g. MolecularEntity-0.1-DRAFT.shex

**Comment by AlasdairGray** [comment]
@egonw did you move these ShEx schemas into the Specification repository?

**Comment by AlasdairGray** [comment]
Files should be moved to the directory https://github.com/BioSchemas/specifications/tree/master/MolecularEntity/examples/0.1-DRAFT

**Comment by egonw** [comment]
PR: https://github.com/BioSchemas/specifications/pull/416
