### ISSUE TITLE
Access for all in TrainingMaterials profile

### ISSUE THREAD

**Issue by philbarker** [BioSchemas/specifications#243]
The training materials profile does not use any properties for flagging (accessibility)[https://www.w3.org/wiki/WebSchemas/Accessibility] issues/enablers. It should. https://schema.org/accessibilitySummary is a good property to include.

**Comment by njall** [comment]
Apologies for the ludicrously long delay.

I've added accessibilitySummary to the latest version. What are your thoughts on other accessibility features such as control, hazard, feature, API? Do you know how well used they typically are?

**Comment by philbarker** [comment]
@njall good to hear from you :)
No, sorry, I don't know how well used the other terms are. You would probably need to do an accessibility audit of the materials and/or have policies for what accessibility features your materials incorporate in order to know what values to use for most of them. If you have those then adding the metadata to encode the outcome would make sense. But this goes beyond metadata and into development policy.

**Comment by AlasdairGray** [comment]
A property has been added to enable this to some extent. For the 1.0 release I think this adequately covers the issue. If/when usage/practice becomes more developed then this can be revisited.
