### ISSUE TITLE
Missing use cases for Gene

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#247]
We do not have any use cases for the Gene profile. Can those who were working on #143 define a basic set of search use cases?

@deniseOme, @micheldumontier, @ljgarcia, @oxgiraldo @nathandunn, @kyook, @andrawaag

**Comment by deniseOme** [comment]
May I have some examples of use cases for other profiles that Gene, so that I have an idea what you are after please?

**Comment by nathandunn** [comment]
@AlasdairGray  we have some examples here: https://github.com/BioSchemas/specifications/tree/master/Gene/examples but I'm not sure if that's what you're looking for.   This is also a small portion of what we have.   I'm sure we could generate more.

**Comment by nathandunn** [comment]
This is based on the current (to my knowledge) gene profile.  I'm sure it will change with the newer spec.

**Comment by AlasdairGray** [comment]
You can find the use cases that have been written for the other profiles linked from the [specifications page](http://bioschemas/specifications), e.g.
- [Protein](http://bioschemas.org/useCases/Proteins/)
- [Taxon](http://bioschemas.org/useCases/Taxon/)
- [Datasets](http://bioschemas.org/useCases/Datasets/)

**Comment by deniseOme** [comment]
Thanks @AlasdairGray. Based on these templates, this is a tentative first draft of [Use Cases for Genes]( https://docs.google.com/document/d/1YI1JaQ5FwM9HJIFrEo7ECj5NwO-h6w9AYbAsPHUrYGE/edit?usp=sharing).

**Comment by AlasdairGray** [comment]
Thanks for that. We'll need to get that deployed on the website.

**Comment by newgene** [comment]
Just added [MyGene.info](https://mygene.info) API as a use case to the google doc above.

**Comment by AlasdairGray** [comment]
Any further edits for the Gene Use Case should be done through the website version

**Comment by AlasdairGray** [comment]
@newgene I have added a profile for you on Bioschemas (commit [ba251dd](https://github.com/BioSchemas/bioschemas.github.io/commit/ba251dd0f560af916a388a8e287807484ba6f07e)) and invited you as a collaborator on the specifications repository.
