### ISSUE TITLE
Need to add multiple profiles on a single page

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#248]
Profiles are starting to be defined over multiple types, e.g. Samples has PropertyValue and CategoryCode and the latest Tool draft has profiles over Person and Organization.

The idea is that where a Person is mentioned in a Tool, then the information provided should conform to the person profile on the same page.

We need some way to use GOWeb to create the multiple profile tables on a single web page. Multiple crosswalks have been created, one for each profile part.

For now, I've manually stitched the resulting HTML together but it is a painful and error prone process.

**Comment by gtsueng** [comment]
I'm marking this issue as closed due to deprecation as GoWeb no longer appears to be maintained/supported
