### ISSUE TITLE
Missing use cases for Tool

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#249]
The tool profile does not have any use cases

**Comment by kcmcleod** [comment]
@AlasdairGray I notice the group leaders for the tools group are: Ricardo, Justin C-C & Leyla. As they all seem to be busy with other things, who can I assign this to?

**Comment by AlasdairGray** [comment]
Fixed with https://github.com/BioSchemas/bioschemas.github.io/pull/374
