### ISSUE TITLE
GOWeb schema.org type not displaying correctly

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#253]
When the crosswalk spreadsheet type column has been set to schema.org, the result of running go-web does not show the properties correctly nor embed the correct link.

Attached is the csv file used as input to go-web (I had to add .txt to the extension to allow it to be uploaded).
[Dataset mapping 0.3-DRAFT - Bioschemas fields.csv.txt](https://github.com/BioSchemas/specifications/files/2619319/Dataset.mapping.0.3-DRAFT.-.Bioschemas.fields.csv.txt)

Here is a screenshot showing the result as external URLs. These should all be schema.org URLs.
![screen shot 2018-11-27 at 10 06 58](https://user-images.githubusercontent.com/1141265/49074252-39fa7c00-f22c-11e8-9130-21b266213359.png)

**Comment by AlasdairGray** [comment]
@ricardoaat am I correct in thinking that you resolved this issue at the BioHackathon in November 2018? If so, please can you close with a link to the released version with the fix.

**Comment by AlasdairGray** [comment]
Using the latest version and the taxon profile 0.4-draft this issue is still occurring.

**Comment by gtsueng** [comment]
I'm marking this issue as closed due to deprecation as GoWeb no longer appears to be maintained/supported
