### ISSUE TITLE
Missing use cases for MolecularEntity

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#256]
MolecularEntity does not have any use cases defined.

**Comment by egonw** [comment]
@AlasdairGray, where does that need to be added? Did you have an example?

**Comment by AlasdairGray** [comment]
On the [specifications page](http://bioschemas.org/specifications/) and the [draft specifications page](http://bioschemas.org/specifications/drafts) you will find links to all the use cases in the third column. 

For example, you could look at the [Proteins Use Case](http://bioschemas.org/useCases/Proteins/)

You can find the files in this [directory](https://github.com/BioSchemas/bioschemas.github.io/blob/master/_useCases/)

**Comment by egonw** [comment]
Thanks! I will look into it.

**Comment by AlasdairGray** [comment]
Use cases still need to be stated in [here](https://github.com/BioSchemas/bioschemas.github.io/blob/master/_useCases/MolecularEntity.html)

**Comment by egonw** [comment]
It's in production in ChEMBL: https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL4116337/

**Comment by AlasdairGray** [comment]
The ChEMBL deployment is of the markup. The use case should identify why someone should provide such markup in their resource. What are the search, discovery, or exchange tasks we are trying to support?

**Comment by AlasdairGray** [comment]
See proposal for use case on #257

**Comment by AlasdairGray** [comment]
Fixed in https://github.com/BioSchemas/bioschemas.github.io/pull/377
