### ISSUE TITLE
Review Standard Specifications Process Document

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#26]
Ask hackathon participants to read and review the [Standard Specifications Process Document](https://docs.google.com/document/d/1eDHBfw6frl9xAjIduLYRwcqUY3jehfzJ-xSKCc1nSsc/edit?usp=sharing). If no complaints or more comments make it available in github and plan specification reviews accordingly.

**Comment by AlasdairGray** [comment]
This has now been captured in the Bioschemas Governance document.
