### ISSUE TITLE
potentialUse

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#260]
The property `potentialUse` has been defined for a `ChemicalSubstance`, see [doc](https://docs.google.com/document/d/1_rO64r4JZgHA-66s_nsvLikUKZJnPJcwQte9BFb0WiU/edit#) for details.

The label `potentialUse` is very generic and could be confused in other domains of schema.org. Can we try to find a more chemical oriented label?

**Comment by AlasdairGray** [comment]
@egonw How does `potentialUse` relate to `https://schema.org/clinicalPharmacology`?

**Comment by egonw** [comment]
For chemistry we have `biologicalRole` and `chemicalRole` for this purpose.

**Comment by AlasdairGray** [comment]
Let's see how the wider Schema.org community respond to this property. I'll close this issue for now.

Could another name in this context be `potentialPharmacologicalUsage`?
