### ISSUE TITLE
Protein Properties

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#262]
Several of the properties defined for `Protein` in the latest [draft doc](https://docs.google.com/document/d/1_rO64r4JZgHA-66s_nsvLikUKZJnPJcwQte9BFb0WiU/edit#) seem to me to be more generic than Protein. Could you verify that the following properties should not be moved up to BioChemEntity, and their definitions generalised?
- [x] hasMolecularFunction
- [x] hasSequenceAnnotation
- [x] isInvolvedInBiologicalProcess
- [x] isLocatedInSubcelluarLocation

**Comment by ljgarcia** [comment]
Yes, all of them would apply to Gene as well, for instance. Moved to BioChemEntity now in the branch. Protein would have no properties now though, but hope that is not a problem.

**Comment by AlasdairGray** [comment]
On 22 Jan 2019, at 12:47, ljgarcia <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes, all of them would apply to Gene as well, for instance. Moved to BioChemEntity now in the branch. Protein would have no properties now though, but hope that is not a problem.

I don’t think that there is a hard and fast rule about when we move properties up to BioChemEntity but we do need to balance between:

- Having types without any properties
- Having too many properties on BioChemEntity

Perhaps we should think about how many of the subtypes the property is applicable to.

________________________________

Heriot-Watt University is The Times & The Sunday Times International University of the Year 2018

Founded in 1821, Heriot-Watt is a leader in ideas and solutions. With campuses and students across the entire globe we span the world, delivering innovation and educational excellence in business, engineering, design and the physical, social and life sciences. This email is generated from the Heriot-Watt University Group, which includes:

  1.  Heriot-Watt University, a Scottish charity registered under number SC000278
  2.  Edinburgh Business School a Charity Registered in Scotland, SC026900. Edinburgh Business School is a company limited by guarantee, registered in Scotland with registered number SC173556 and registered office at Heriot-Watt University Finance Office, Riccarton, Currie, Midlothian, EH14 4AS
  3.  Heriot- Watt Services Limited (Oriam), Scotland's national performance centre for sport. Heriot-Watt Services Limited is a private limited company registered is Scotland with registered number SC271030 and registered office at Research & Enterprise Services Heriot-Watt University, Riccarton, Edinburgh, EH14 4AS.

The contents (including any attachments) are confidential. If you are not the intended recipient of this e-mail, any disclosure, copying, distribution or use of its contents is strictly prohibited, and you should please notify the sender immediately and then delete it (including any attachments) from your system.
