### ISSUE TITLE
Should `boundMolecule` connect to `MolecularEntity`? 

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#264]
The definition of `boundMolecule` in `ProteinStructure` does not include `MolecularEntity` or `ChemicalSubstance` in its range. This seems strange to me.

**Comment by ljgarcia** [comment]
@AlasdairGray you are right, it should be there. Added now to the BioChemEntity. Including this change, right now the range would be BioChemEntity, CategoryCode, ChemicalSubstance and MolecularEntity.
