### ISSUE TITLE
Should sample point to Sample?

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#265]
The `LabProtocol` type defines a property called `sample` that is used to indicate the sample used in the protocol.

First, it is not good practice to have a property have the same name as a type that we are defining. Can we rename the property to `sampleUsed`?

Second, should we not point to the `Sample` type as a permissible range value?

**Comment by ljgarcia** [comment]
Hi @AlasdairGray. You are right, sampleUsed sounds good and yes, Sample should be part of the expected range, sorry I missed that one! "sampleUsed" change now in the BioChemEntity branch. I saw you added Sample already to the expected ranged but now I do not see BioChemEntity (by the way, I did not see that change reflected on the appspot link so maybe a refresh there is necessary). As the definition states "it could be a record describing the sample", I would keep BioChemEntity within the expected ranges. @oxgiraldo any thoughts?

**Comment by ljgarcia** [comment]
Now the range is BioChemEntity, CategoryCode, Sample, Text, and URL, that should work

**Comment by AlasdairGray** [comment]
> I saw you added Sample already to the expected ranged but now I do not see BioChemEntity (by the way, I did not see that change reflected on the appspot link so maybe a refresh there is necessary). 

Sorry, not quite following what you mean here. When I look on appspot I see the last version I deployed last night which has `sample` with `BioChemEntity` as an expected type. I see from your edit in commit [22e66c0](https://github.com/BioSchemas/schemaorg/commit/22e66c09960c12a53b24917437043736460244e2) that you had added `Sample` as an expected type rather than replacing `BioChemEntity`. 

Did you deploy your edits to appspot? I don't see anything in the version history reflecting a change from you.

**Comment by AlasdairGray** [comment]
Issue fixed in commit https://github.com/BioSchemas/schemaorg/commit/616070da918e22c784656712fdeb1baf1d19ded8

**Comment by AlasdairGray** [comment]
This issue needs to be followed through to the LabProtocol profile.

**Comment by ljgarcia** [comment]
"used" in properties addressed by https://github.com/BioSchemas/bioschemas.github.io/pull/307

**Comment by ljgarcia** [comment]
Closing this issue as addressed by the 0.4_DRAFT
