### ISSUE TITLE
Getting Started Gitbook needs to link back to Bioschemas site

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#268]
The Bioschemas logo in the Gitbook should take people back to the Bioschemas website
https://bioschemas.gitbook.io/training-portal/

**Comment by ljgarcia** [comment]
I did not find the way to do that on the logo but did include a Bioschemas link on the headers

**Comment by ljgarcia** [comment]
@AlasdairGray is happy with the link so I am closing this issue
