### ISSUE TITLE
expressedIn definition

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#274]
The new property [expressedIn](http://bio.sdo-bioschemas-227516.appspot.com/expressedIn) needs a descriptive definition

**Comment by ens-ap5** [comment]
Suggested in Bioschemas F2F:

Tissue, organ, biological sample, etc in which activity of this gene has been observed experimentally. For example brain, digestive system.

**Comment by AlasdairGray** [comment]
Should the Range of this property include `BioSample`?
