### ISSUE TITLE
hasHomolog definition

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#275]
The new property [hasHomolog](http://bio.sdo-bioschemas-227516.appspot.com/hasHomolog) needs a descriptive definition.

**Comment by deniseOme** [comment]
A gene that has a ortholog in another species, or paralog in the same species.

Or a gene that has a similar nucleotide sequence (i.e. gene) in other species due to shared common ancestor among the two species (ortholog), or due to a duplication event within a single species (paralog).

**Comment by deniseOme** [comment]
Note there seem to be something else in addition to paralogues and orthologues i.e. xenologous genes.

Worth including `hasXenolog`.

**Comment by AlasdairGray** [comment]
Outcome from F2F Meeting in May 2019

> Useful, but not required for an initial release.
