### ISSUE TITLE
hasOrtholog definition

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#276]
The new property [hasOrtholog](http://bio.sdo-bioschemas-227516.appspot.com/hasOrtholog) needs a descriptive definition.

**Comment by deniseOme** [comment]
@ljgarcia, I'd suggest: a gene that has a homolog in other species where both genes share a common evolutionary ancestor. The nucleotide sequences of the two genes are similar and they may or may not have the same function.

Or a gene that has another gene with similar nucleotide sequence in other species and share the common evolutionary ancestor.

**Comment by deniseOme** [comment]
@AlasdairGray @ljgarcia I think we will need `hasParalog` as well.

**Comment by ens-ap5** [comment]
Too specific - consider using hasHomolog for all ortho/para/xeno/etc

**Comment by AlasdairGray** [comment]
Outcome from F2F meeting in May 2019

> we agreed there is no need for this property, on the grounds that a user looking specifically for orthologs or paralogs will be able to differentiate them by the species that the gene belongs to.
