### ISSUE TITLE
partOfOperon definition

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#277]
The new property [partOfOperon](http://bio.sdo-bioschemas-227516.appspot.com/partOfOperon) needs a descriptive definition

**Comment by deniseOme** [comment]
@ljgarcia, how about this definition?

operon: DNA sequence containing a group of genes, which are all transcribed under the control of the same promoter. In addition to the promoter and the genes to be transcribed, operons also contain a sequence called oppressor, where a repressor protein binds to. Operons are mainly found in prokaryotes but there are examples in some eukaryotes such as _C. elegans_ and _D. melanogaster_.

Do we need a definition for promoter and repressor?

So, `partOfOperon` is part of a DNA sequence containing...

**Comment by ens-ap5** [comment]
To define in a future version.
