### ISSUE TITLE
presentInCollection definition

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#278]
The new property [presentInCollection](http://bio.sdo-bioschemas-227516.appspot.com/presentInCollection) needs a descriptive definition.

**Comment by AlasdairGray** [comment]
From the name, it is very unclear to me what this has to do with genes. Does this mean the record about the gene appears in some database?

**Comment by ljgarcia** [comment]
@deniseome could you please help us with this one and the other under type:Gene? Thanks

**Comment by deniseOme** [comment]
@ljgarcia I have never come across this term before. Can you share some examples please?

Could it be a collection of genes within a family (e.g. bromodomain family, made of BET,  BRD2, BRD3, BRD4 and BRDT)?

More gene families here:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3437568/

**Comment by ens-ap5** [comment]
Shelve until a future version, when we have a better idea how it will be used.

**Comment by folago** [comment]
Not sure what is this about. Closing it for now, reopen if needed.
