### ISSUE TITLE
ProteinStructure definition

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#281]
The new [ProteinStructure type](http://bio.sdo-bioschemas-227516.appspot.com/ProteinStructure) needs a descriptive definition.

**Comment by otienoanyango** [comment]
Currently on leave. Will look at this first week of March when I resume

**Comment by AlasdairGray** [comment]
@ljgarcia can you update the status of this card based on the outcomes of today's meeting and moving to BioChemStructure.

**Comment by ljgarcia** [comment]
Done! We added a description for the renamed type BioChemStructure, already committed to the appspot
