### ISSUE TITLE
SequneceAnnotation typos

### ISSUE THREAD

**Issue by JervenBolleman** [BioSchemas/specifications#287]
There are a few typos in the values e.g. SequneceAnnotation on ProteinStructure

**Comment by egonw** [comment]
@JervenBolleman, where exactly is that? I cannot find the string in this repo...

**Comment by JervenBolleman** [comment]
It's in the demo site that @AlasdairGray shared http://bio.sdo-bioschemas-227516.appspot.com/. Not sure where that code is hosted.

**Comment by AlasdairGray** [comment]
@JervenBolleman can you be more specific about what typos there are or even which subpage you are on? Is this SequenceAnnotation or ProteinStructure?

**Comment by JervenBolleman** [comment]
@AlasdairGray I can't because the page where I found the typo is currently giving a 500 error.

**Comment by AlasdairGray** [comment]
There is a cached copy of the pages at https://bioschemas.org/schema/

**Comment by AlasdairGray** [comment]
I've now fixed the appspot deployment so you should be able to see the most up-to-date version

**Comment by AlasdairGray** [comment]
I believe that the decision of the F2F meeting was to remove the SequenceAnnotation type. At least until we have a clearer set of usage requirements.
