### ISSUE TITLE
replace molecularFormula with chemicalComposition for ChemicalSubstance

### ISSUE THREAD

**Issue by egonw** [BioSchemas/specifications#288]

**Comment by AlasdairGray** [comment]
I see that this has been done in the type, but the profile still has molecularFormula.
(Relates to #346)

**Comment by AlasdairGray** [comment]
Other properties need similar tweaks in the cross-walk spreadsheet.

**Comment by AlasdairGray** [comment]
This has now been done in v0.3-draft [crosswalk](https://docs.google.com/spreadsheets/d/1z1PsEDmDEADzc5NgvPlwEyXxAAA_m3U4QE5jrW8Qly8/edit#gid=1483018794)

Just need to regenerate the profile page using GO Web

**Comment by AlasdairGray** [comment]
New version of draft page available in [PR242](https://github.com/BioSchemas/bioschemas.github.io/pull/242)

**Comment by AlasdairGray** [comment]
Pull request was merged so we can close this issue.
