### ISSUE TITLE
Update software page

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#290]
The [software page](http://bioschemas.org/software/) is out of date. We need to refresh this.

**Comment by kcmcleod** [comment]
@AlasdairGray 

Buzzbang demo is offline so the link should be removed. BUT the actual project is in hibernation, the link to GH repo works YET there is no code only architecture diagrams. Should I:
* delete it
* make a new 'archived project' section at the bottom of the page?

Validata can be deleted? Your new one can be added later in the year?

Markup Builder can also be deleted and replaced with Sean's project in May?

**Comment by AlasdairGray** [comment]
Closed by [PR180](https://github.com/BioSchemas/bioschemas.github.io/pull/180)
