### ISSUE TITLE
Draft profiles not migrated to new format

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#291]
The following profiles need to be migrated to the new spreadsheet and generated with the GoWeb tool:

- [ ] Organization
- [ ] Person
- [ ] Standard

**Comment by kcmcleod** [comment]
# Organization
- [x] in new format: 
    - [link here](https://docs.google.com/spreadsheets/d/1Cy45Llql88NvkqwRw7WD1y8HeVQ4z5_V6MhJh6hhbks)
    - #337 needs resolved
- [x] generated with GoWeb

# Person
- [x] in new format: 
    - [link here](https://docs.google.com/spreadsheets/d/1vliGiKWlHzqXWcGPa15l0PzJbQGXPKxYPq8Mups_or4)
    - #105 still needs resolved
- [x] generated with GoWeb

# Standard
- [x] in new format: 
- [ ] generated with GoWeb

**Comment by kcmcleod** [comment]
There doesn't seem to be a Standard profile to work from?
https://drive.google.com/drive/folders/0Bw_p-HKWUjHoaDRIWlVwUXNJcHM

**Comment by kcmcleod** [comment]
Now working on version 0.3-DRAFT
https://docs.google.com/spreadsheets/d/1wxwz20qA4rgstAsZu-fz-pHhKbHRfSAgh02tCfuYb_c/edit#gid=1261485211
