### ISSUE TITLE
Cross-walk spreadsheets for Course and CourseInstance

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#292]
@njall where are the crosswalk spreadsheets for Course and CourseInstance?

The Course [link](https://docs.google.com/spreadsheets/d/1cQ6mDbsG_cMX2EDAN8xH6-9yMRba8-rErlPeP8HTs8A/edit#gid=0) goes to a spreadsheet that is not of the right form and there is no link for CourseInstance.

This is associated with pull requests
- https://github.com/BioSchemas/bioschemas.github.io/pull/173
- https://github.com/BioSchemas/bioschemas.github.io/pull/174
- https://github.com/BioSchemas/bioschemas.github.io/pull/175

**Comment by njall** [comment]
Thanks @AlasdairGray, 

The "cross-walk" spreadsheets are here (ones versioned `Course Mapping - GOBLET Review #_n_)`:

https://drive.google.com/drive/folders/1MSPkqrwgUX3QwsQY-aaAq8Wnl0swCrhv

I've incorporated @orchid00 patches in version 5
