### ISSUE TITLE
Add Identifiers.org list of schema.org deployments to live deploy page

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#293]
Identifiers.org has a list of services that provide any schema.org metadata 
https://identifiers-org.github.io/docs/metadata_service.html. 

These deployments should also be listed on the Bioschemas [live deploys page](http://bioschemas.org/liveDeploys/)

**Comment by kcmcleod** [comment]
@AlasdairGray the identifiers.org link 404s.

**Comment by AlasdairGray** [comment]
@sarala can you advise where the list is now located?

**Comment by sarala** [comment]
https://docs.identifiers.org/articles/docs/metadata_service.html

**Comment by AlasdairGray** [comment]
@kcmcleod should this issue now be closed?
