### ISSUE TITLE
Recommend usage of @type and @id

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#294]
We need to recommend that `@id` and `@type` are used for all markup.

`@id` provides a base IRI for the resource being described. This is needed for tools consuming the markup.

`@type` allows tools consuming the markup to understand what the resource is about and to identify the profile(s) against which the markup has been provided.

**Comment by ljgarcia** [comment]
I am not sure I understand this task. @type should be the schema/bioschemas type selected to describe an object. As for @id, that is also up to the user, I would say. We could encourage using persistent, global, unique identifiers as @id and recommend using identifiers.org if possible or at least mentioning it on the sameAs property, other than that I am not sure what else could be done here. 

Maybe you have some examples on the kind of recommendations you are expecting? That could help clarify what you mean.

**Comment by kcmcleod** [comment]
Not really a task, more of a proposal/idea that needs to discussed. The background:

I'm trying to use Any23 to scrape the DataCatalog markup from sites in our live deploy list. Currently most do not use **@id**,  thus the RDF generated has blank nodes at the top level for example:
```
_:genid-93a09050d31f41ed8ef5fd290f47130b-55AB4998C101ED8F71C58C727BB4BF6F <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Dataset>
```
We are now injecting an @id based on the URL of the page scraped, eg
```
<https://fairsharing.org/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Dataset>
```
However, this may not be the correct IRI. Better if sites just provide an **@id**?

**Comment by AlasdairGray** [comment]
Using `@id` at the top level allows tools to identify the IRI of the resource that is being marked up. I believe in the schema.org world that that should match the page URL otherwise the search engine crawlers will believe that the page is spam. This is probably at odds with the bioinformatics desire to use permanent URLs like Identifiers.org.

@kcmcleod came across this issue with our initial prototypes of scraping markup. We found that if we do not include an `@id` then we end up with a blank node for the root element. So when we scrape [Ensembl markup](https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fwww.ensembl.org%2F) we get a root IRI, when we scrape most of the other sites, e.g. [BioSamples](https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fwww.ebi.ac.uk%2Fbiosamples%2F), [FAIRsharing](https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Ffairsharing.org%2F), [CATH](https://search.google.com/structured-data/testing-tool#url=http%3A%2F%2Fwww.cathdb.info), etc, we end up with a blank node as the root IRI.

`@id` can also be used to link to other markup on different pages.

**@ljgarcia the action here is to update our training material and profiles so that we state that `@id` needs to be provided.**

**Comment by vdda** [comment]
Completely agree with @id. 
In the following article we have a description about what we can recommend. 
[http://doi.org/10.1629/uksg.457]
In summary : 
 PIDs can be broadly grouped into three main types:
1) identifiers for researchers, such as ORCID iDs, ResearcherIDs and Scopus IDs
2) identifiers for organizations, including GRID (Global Research Identifier Database), Ringgold IDs, ISNIs (International Standard Name Identifiers), LEIs (legal entity identifiers) and the identifiers that will be provided by the recently announced Research Organization Registry2
3) identifiers for research objects and outputs, for example, DOIs (digital object identifiers), Archival Resource Key identifiers (ARKs), handles and IGSNs (International Geo Sample Number).

For training material we are recomending @id (via DOI) Using Zenodo or eudat @njall any comment about this

**Comment by njall** [comment]
I think this is a slightly different discussion @vdda. 

The usage of the @id property here (also, apologies the Github user who has the handle @id for all the spam) is to give an identify to the snippet of JSON-LD for machine-processing purposes. The @id you're referring to is the property https://schema.org/identifier where you can add a link to a permanent identifier to make the accessibility of the resource more robust.

I think they're mutually exclusive properties as (Alasdair said) the @id 

> should match the page URL otherwise the search engine crawlers will believe that the page is spam

And a PID should be an intermediary URL that resolves *to* the URL. 

Hope that clears things up a bit

**Comment by AlasdairGray** [comment]
We need to add some standard text to the profile template that states that the following boilerplate should be used for all markup (the example here is for DataCatalog):
```html
<script type="application/ld+json">
        {
            "@context": "https://schema.org/",
            "@type": "DataCatalog",
            "@id" : "https://www.guidetopharmacology.org",
            "http://purl.org/dc/terms/conformsTo": {
                "@type": "CreativeWork",
                "@id": "https://bioschemas.org/profiles/DataCatalog/0.3-RELEASE-2019_07_01/"
            },
            ...
         }
        </script>
```

These are not really profile properties so I don't think they should be in the table

**Comment by AlasdairGray** [comment]
I have started work on this on branch [standard-properties](https://github.com/BioSchemas/bioschemas.github.io/tree/standard-properties). The following screenshot shows the four rows that are injected into every profile. Thoughts please?
![Screen Shot 2021-06-11 at 16 11 11](https://user-images.githubusercontent.com/1141265/121708808-d5445b80-cacf-11eb-87c3-82467e33ab7f.png)

Property | Expected Type | Description | CD | Controlled Vocabulary | Example
-- | -- | -- | -- | -- | --
Marginality: Minimum.
@context | URL | Used to provide the context (namespaces) for the JSON-LD file. Not needed in other serialisations. | ONE |   |  
@type | Text | Schema.org/Bioschemas class for the resource declared using JSON-LD syntax. For other serialisations please use the appropriate mechanism.While it is permissible to provide multiple types, it is preferred to use a single type. | MANY | Schema.org, Bioschemas  |  
@id | IRI | Used to distinguish the resource being described in JSON-LD. For other serialisations use the appropriate approach. | ONE |   |  
dct:conformsTo | IRI | Used to state the Bioschemas profile that the markup relates to. The versioned URL of the profile must be used.Note that we use a CURIE in the table here but the full URL for Dublin Core terms must be used in the markup, see example. | ONE | Bioschemas profile versioned URL  |

**Comment by ljgarcia** [comment]
I would suggest to clarify on the description that the @ fields correspond
to JSON-LD markup

**Comment by AlasdairGray** [comment]
Redone the work on this on a new branch as the old branch is too distant. 

Work now on [standard-properties-2](https://github.com/BioSchemas/bioschemas.github.io/tree/standard-properties-2).

Need to 
- [x] fix the display of the examples

**Comment by AlasdairGray** [comment]
> Redone the work on this on a new branch as the old branch is too distant.
> 
> Work now on [standard-properties-2](https://github.com/BioSchemas/bioschemas.github.io/tree/standard-properties-2).
> 
> Need to
> 
> * [x]  fix the display of the examples

@bedroesb are you able to look at the _includes/standard-properties.html file and fix the styling issue?

**Comment by bedroesb** [comment]
@AlasdairGray done!

**Comment by AlasdairGray** [comment]
Things to complete for https://github.com/BioSchemas/bioschemas.github.io/pull/474
- [x] Add news item
- [x] Update date of news item when PR accepted
- [x] Update tutorials
  - [x] https://bioschemas.org/tutorials/what_why_bioschemas: add information about minimal properties (may be too detailed)
  - [ ] https://bioschemas.org/tutorials/howto/howto_add_markup: needs to be coordinated with https://github.com/BioSchemas/bioschemas.github.io/pull/447
  - [x] https://bioschemas.org/tutorials/howto/howto_create_new_profile: add statement about standard profiles being automatically added so not included in spreadsheet
  - [x] https://bioschemas.org/tutorials/howto/howto_new_profile_version: add statement about standard profiles being automatically added so not included in spreadsheet

**Comment by AlasdairGray** [comment]
As the rest of this is ready to go, I've pushed the issue about updating the howto_add_markup tutorial to the open PR https://github.com/BioSchemas/bioschemas.github.io/pull/447
