### ISSUE TITLE
Event audience vs topic

### ISSUE THREAD

**Issue by orchid00** [BioSchemas/specifications#295]
https://bioschemas.org/devSpecs/Event/
"audience"
Bioschemas: The scientific background the participants should be from. Please use a term from EDAM: Topic.
"topic"
Bioschemas: The scientific topic the event is about. Please use a term from EDAM: Topic.

These two fields seem the same to me.
What should be the difference?

**Comment by AlasdairGray** [comment]
I have asked a more general question related to this on the mailing list relating to the status of the Event and TrainingMaterial profiles.
https://lists.w3.org/Archives/Public/public-bioschemas/2019Apr/0002.html

**Comment by njall** [comment]
Sorry @AlasdairGray, I don't seem to be getting w3 group messages! I'll investigate why.

So, two two-part answers here.

@orchid00 
1. Topic is a relic. It has now been replaced with 'About' which I'll update soon (been so swamped lately)
2. They are rather different, though there may be a lot of overlap. A topic can be taught differently to different audiences. e.g. One workshop may be teaching R but tailored to an audience of Clinicians, whereas another may be teaching R tailored to Geoscientists. 

@AlasdairGray 
The Course/CourseInstance are a tightly coupled pair to represent training events. 
This means:
1. Event Spec is still very useful for non-training events such as conferences and webinars. 
2. A Training Material is still very relevant as it is not superceded by Course/CourseInstnace

**Comment by AlasdairGray** [comment]
@njall thanks for the response.  That makes sense.

> Event Spec is still very useful for non-training events such as conferences and webinars.

We should review the profile to make it more tailored to non-training events.
