### ISSUE TITLE
Create wiki page for event team

### ISSUE THREAD

**Issue by martin-nc** [BioSchemas/specifications#30]
You could follow this [template](https://docs.google.com/document/d/1WHOLkfE2zAqO73uW3McGHxSJodc_tTruIZdP00w1dIw/edit?usp=sharing)

**Comment by rajido** [comment]
Related to #5

**Comment by frenkxs** [comment]
Hi Rafa, Martin,

 I've created the wiki page for the events team: https://github.com/BioSchemas/bioschemas/wiki/Bioschemas-Events-Group 

I am not sure if we can make it a landing page for the event group. (It now sits in the wiki section). Perhaps we could create a repository within the events group and then upload the page as md file.... 

 Premysl
