### ISSUE TITLE
Agree new Sample Type properties

### ISSUE THREAD

**Issue by stylesm** [BioSchemas/specifications#306]
Proposed new properties (needs a lot of tidying):

* 	identifier
* 	name
* 	description
* 	collector [the Person or Organization who created the sample]
* 	custodian [the Person or Organization who is responsible for the sample]
* 	dateCreated [the date the sample was created]
* 	geographicLocation [the location of origin of the sample] (type:Place)
* 	taxonomicRange [Text or URL or bioschemas:Taxon]
* 	material [https://schema.org/material - A material that something is made from, e.g. heart, stem cell, whole plant, soil…] 
* 	age [how old the object was when sample was created]
* 	phenotype [range Text or URL or schema.org Phenotype]
	associatedDisease [the disease that is represented by the sample e.g. malaria, bowel cancer, coeliac disease, Creutzfeldt–Jakob disease, etc]
* 	gender  = https://schema.org/gender
* 	pedigree
* 	isControl [A boolean (true/false) value. If true, this sample is being use as a normal control, often in combination with another sample]

**Comment by qgroom** [comment]
@dnoesgaard @MortenHofft @MattBlissett this issue might interest you. It is about better specifying the `sample` type in bioschemas. Currently, it is strongly focused on biological samples and inparticular ones from longterm archives, such as museums and herbaria.

**Comment by qgroom** [comment]
See also #299 for an example of use

**Comment by AlasdairGray** [comment]
Rather than defining a new property for `collector` could we reuse [`creditedTo`](https://schema.org/creditedTo), although looking at the description of the property maybe not.

**Comment by qgroom** [comment]
`creditedTo` is probably OK.

**Comment by AlasdairGray** [comment]
I have updated the version of BioSample available on the appspot deployment with the proposal above. This is available at http://bio.sdo-bioschemas-227516.appspot.com/BioSample

Some issues that I came across while doing this were:
- [ ] `BioSample` type definition updated to reflect that it only relates to bio samples. Please review.
- [x] New proposal for `collector` is probably far enough away from the existing [`creditedTo`](https://schema.org/creditedTo) property that we keep it as a separate property
- [x] New proposal for `custodian` property: could the existing [`accountablePerson`](https://schema.org/accountablePerson) be used instead. It might need a tweak of the definition
- [x] Existing [`dateCreated`](https://schema.org/dateCreated) property mentions `CreativeWork` in its description. We probably need that to be updated in the schema.org definition.
- [x] For geographicLocation I have added [`location`](https://schema.org/location) and [`locationCreated`](https://schema.org/locationCreated). 
  - [x] Instead of [`location`](https://schema.org/location) would the more specific [`itemLocation`](https://schema.org/itemLocation) make sense?
  - [x] The definition of [`locationCreated`](https://schema.org/lcoationCreated) mentions `CreativeWork` so would need rephrasing
- [ ] Proposed `phenotype` property needs renaming so that it is not the same as the type (`Phenotype`). We also need a definition.
- [ ] Proposed `pedigree` property needs a definition and also expected types defined.

@tburdett, @mcourtot, @stylesm, @qgroom, @simonjupp: please review to check that this is a valid outcome of last week's face-to-face.

**Comment by qgroom** [comment]
I assume the biosample:gender is the gender of the object that the sample came from.

The definition should perhaps be...

> Gender of the **organism**. While http://schema.org/Male and http://schema.org/Female may be used, text strings are also acceptable for people who do not identify as a binary gender.

- Yes, itemLocation make more sense.
- I'm not sure there should be a phenotype property if there is already a Phenotype type.

**Comment by stylesm** [comment]
@tburdett you may find this useful. The `additionalProperty` prop has been retained which ensures backwards compatibility with anyone using the `Sample` type in prod.

**Comment by stylesm** [comment]
> New proposal for collector is probably far enough away from the existing creditedTo property that we keep it as a separate property

Yes I think there is a difference between someone or some org which collects a sample and who that sample is creditedTo. In the case of archaeology this might be the same person, but a human tissue sample from a biobank isn't really in the same way (sometimes). I don't think it adds much duplication.

> New proposal for custodian property: could the existing accountablePerson be used instead. It might need a tweak of the definition

Possibly. `accountablePerson` has a type of `Person`, but in the case of custodian it would need to be `Person` or `Organization`, since in the human tissue samples case it is usually an organisation who is accountable / has care for the sample. Whether `accountablePerson` can be expanded is another issue as this is specified in multiple types - `LabProtocol` (may not be suitable to change), `CreativeWork` (possiblysuitable to change). It could become `accountableEntity` in the latter case? I feel as though custodian is more descriptive as a prop name, but frankly am not too concerned as long as the value can be a type of `Organization` as well as `Person`.

> Existing dateCreated property mentions CreativeWork in its description. We probably need that to be updated in the schema.org definition.

Possibly. The `dateCreated` prop comes from `CreativeWork`. Assuming `BioChemEntity` doesn't inherit from `CreativeWork`, then happy days I recommend changing it to be more generic. If it should inherit from `CreativeWork`, then I think it can be left as-is.

> For geographicLocation I have added location and locationCreated.
> Instead of location would the more specific itemLocation make sense?

Yes.
> The definition of locationCreated mentions CreativeWork so would need rephrasing

Yes.

> Proposed phenotype property needs renaming so that it is not the same as the type (Phenotype). We also need a definition.

I am not knowledgeable enough on phenotypes to contribute to this.

> Proposed pedigree property needs a definition and also expected types defined.

I am not knowledgeable enough on pedigrees to contribute to this.

**Comment by AlasdairGray** [comment]
Currently schema.org only has two gender classes; [`Male`](https://schema.org/Male) and [`Female`](https://schema.org/Female). Looking at a rare disease use case this does not seem to be sufficient. There they need `Undetermined` and `Foetus (Unknown)` as well.

**Comment by qgroom** [comment]
Plants have additional genders, but it's complicated.

I think there are some well established vocabularies for gender, though human gender is a more complex area for data. 

Foetus would come under a different term for _developmental stage_, rather than gender.

**Comment by AlasdairGray** [comment]
Schema for Sample taken from Validation Implementation Study [presentation](https://docs.google.com/presentation/d/1qZzGGGrhsNTj0_96uOKB_OYjdy9fU-m5tpxQ9kDqUbs/edit#slide=id.g5777a9dc78_4_17) by @mcourtot
```
Sample Schema
- Identifier: string
- Name: string
- Taxon: integer
- Donor Age: integer
- Donor Age Unit: [years, months, weeks, days]
- Tissue: string
- Diseases: Array of strings
```
JSON instance for the above schema
```
{
  "sample_id" : "1234",
  "sample_name" : "Bio rep #1",
  "taxon" : "9606",
  "donor_age" : "22",
  "donor_age_unit" : "years",
  "tissue" : "liver",
  "diseases" : [
    "Type II diabetes"
  ]
}
```

**Comment by AlasdairGray** [comment]
Based on the above example, does it make sense to rename `age` to `donorAge`?

**Comment by AlasdairGray** [comment]
>> New proposal for custodian property: could the existing accountablePerson be used instead. It might need a tweak of the definition

> Possibly. accountablePerson has a type of Person, but in the case of custodian it would need to be Person or Organization, since in the human tissue samples case it is usually an organisation who is accountable / has care for the sample. Whether accountablePerson can be expanded is another issue as this is specified in multiple types - LabProtocol (may not be suitable to change), CreativeWork (possiblysuitable to change). It could become accountableEntity in the latter case? I feel as though custodian is more descriptive as a prop name, but frankly am not too concerned as long as the value can be a type of Organization as well as Person.

I think that we keep it as `custodian` in that case and see what the wider schema.org community think.

**Comment by AlasdairGray** [comment]
> > Proposed phenotype property needs renaming so that it is not the same as the type (Phenotype). We also need a definition.

> I am not knowledgeable enough on phenotypes to contribute to this.

My guess is that the property is to allow us to relate a sample to a phenotype. Would `associatedPhenotype` suffice with this reworking of the `associatedDisease` definition:

`Phenotype associated to this BioSample. Such phenotype can be a Phenotype or a URL. If you want to add an evidence supporting the association, please use PropertyValue.`

**Comment by AlasdairGray** [comment]
If we don't have a working example for `pedigree` then perhaps we should drop this property for now.

**Comment by mcourtot** [comment]
The example above is from early HCA by @simonjupp. Has since been augmented (following slides in same presentation) with ontology support for example.
As discussed above there are many cases in which samples are domain specific. It would make more sense to submit sample as currently implemented and have that be stable. We can then have domain specific extensions to cover plants, biobanks, geo etc. If based on use cases implemented with those extensions we find some properties are generic enough to be pushed up to (bio) samples we then have strong argument to adding them to the top (bio)sample. That allows us to move forward right now without controversy and get the spec stabilized.

**Comment by qgroom** [comment]
> Based on the above example, does it make sense to rename `age` to `donorAge`?

In our discussion we talked about using the term `age`, defined as...

> how old the object was when sample was created

This was meant to cover all sorts of situations and objects, including when the object was a person. A tree or animal does not donate its tissue.

**Comment by AlasdairGray** [comment]
Unfortunately, the term `age` is very generic and I'm not convinced that we'd get the sample specific usage of it into schema.org which is why I'm trying to contextualise it a bit.

**Comment by AlasdairGray** [comment]
@qgroom would `samplingAge` be close enough, with the description that we already have, i.e. `The age of the object when the Sample was created.`

**Comment by qgroom** [comment]
seems like a good solution

**Comment by stylesm** [comment]
Yeah I think that's a good solution.

**Comment by AlasdairGray** [comment]
Material property seems to be problematic as per the discussions on the [mailing list](https://lists.w3.org/Archives/Public/public-bioschemas/2019May/0010.html). We will remove it until we have a concrete example of its usage.

**Comment by AlasdairGray** [comment]
Removing `pedigree` property until we have a concrete example of its usage.

**Comment by AlasdairGray** [comment]
> > > Proposed phenotype property needs renaming so that it is not the same as the type (Phenotype). We also need a definition.
> 
> > I am not knowledgeable enough on phenotypes to contribute to this.
> 
> My guess is that the property is to allow us to relate a sample to a phenotype. Would `associatedPhenotype` suffice with this reworking of the `associatedDisease` definition:
> 
> `Phenotype associated to this BioSample. Such phenotype can be a Phenotype or a URL. If you want to add an evidence supporting the association, please use PropertyValue.`

Removing `phenotype` until we have a concrete example of its usage.

**Comment by cmungall** [comment]
For samplingAge, can we add a note that this should be left blank for non-host associated environmental samples (e.g. soil, seawater). For host-associated environmental samples this would be the age of host.

**Comment by AlasdairGray** [comment]
@cmungall I would suggest such usage notes go in the profile rather than the type definition.

**Comment by AlasdairGray** [comment]
A first set of core properties have been agreed for the initial release to schema.org.
