### ISSUE TITLE
Keywords uses array [Dataset]

### ISSUE THREAD

**Issue by njall** [BioSchemas/specifications#311]
The schema.org description of Keywords is a coma separated field - so its cardinality should be 1

**Comment by AlasdairGray** [comment]
This was changed from a cardinality of one to many in the last release. I'm not sure of the motivation for this. Maybe @sarala can remember.

**Comment by AlasdairGray** [comment]
With the change in schema.org to allow multiple types for this field, in particular to allow controlled vocabulary IRIs, the cardinality should  be maintained as many, but the guidance  updated.

**Comment by AlasdairGray** [comment]
Updated guidance in 0.4-DRAFT
