### ISSUE TITLE
Dataset updates

### ISSUE THREAD

**Issue by njall** [BioSchemas/specifications#312]
The current version of dataset lacks many fields that are used by dataset providers. 

As such, they cannot be Bioschemas compliant. There should be (at least) optional fields for every property used by dataset providers. Maybe consider using the FigShares dataset schema implementation as a base point for what should be included

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fzivahub.uct.ac.za%2Farticles%2FPI-SWERL_measurement_dataset_for_Namib%2F7454210

**Comment by AlasdairGray** [comment]
The Bioschemas profile identifies a minimal set of properties to recommend for consistent markup. The use of additional fields to provide more metadata should not be seen as being excluded. I guess this is an important point when it comes to the validation of the markup of sites against a profile.

**Comment by AlasdairGray** [comment]
Properties added as optional in 0.4-DRAFT
