### ISSUE TITLE
Group leaders are repeated in group members listing

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#316]
The names of group leads should not be repeated again in the group members.

_Originally posted by @AlasdairGray in https://github.com/BioSchemas/specifications/issues/195#issuecomment-400963156_

**Comment by kcmcleod** [comment]
Are the group pages generated manually?

**Comment by AlasdairGray** [comment]
There is YAML markup at the top of every page that includes the details. It used to be that the people profiles were used to generate these pages but I think it is only reliant on the content of the specific group page.

**Comment by kcmcleod** [comment]
Yes, but how are the actual group pages generated? Ricardo planned to produce them based on contents from gSheets; did he finish the tool for that? 
I can manually edit all the group pages now, but if they are overwritten by some tool Ricardo produced then perhaps it is better to look at changing the tool? Or at least making a note that we need to change the tool.

**Comment by kcmcleod** [comment]
closed by https://github.com/BioSchemas/bioschemas.github.io/pull/203
