### ISSUE TITLE
Bioschemas First Release to Schema.org

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#321]
Please use this issue to provide feedback on the 7 types to be included in the Bioschemas first release to Schema.org.

The types that are to be included are:
- [BioChemEntity](http://bio.sdo-bioschemas-227516.appspot.com/BioChemEntity)
- [BioSample](http://bio.sdo-bioschemas-227516.appspot.com/BioSample)
- [ChemicalSubstance](http://bio.sdo-bioschemas-227516.appspot.com/ChemicalSubstance)
- [Gene](http://bio.sdo-bioschemas-227516.appspot.com/Gene)
- [MolecularEntity](http://bio.sdo-bioschemas-227516.appspot.com/MolecularEntity)
- [Protein](http://bio.sdo-bioschemas-227516.appspot.com/Protein)
- [Taxon](http://bio.sdo-bioschemas-227516.appspot.com/Taxon)

(Please note that we have a limited quota on the google cloud platform and you may get a 500 error message when we have exceeded that quota.)

**Comment by stylesm** [comment]
Very happy with `BioChemEntity` and `BioSample`.

We have a couple of fresh live examples which should help with making the case for becoming part of schema.org.

Thanks for all your work on this @AlasdairGray

**Comment by AlasdairGray** [comment]
> We have a couple of fresh live examples which should help with making the case for becoming part of schema.org.

Could you provide some links so that we can add them to the list of [live deployments](https://bioschemas.org/liveDeploys/)

**Comment by AlasdairGray** [comment]
There has been a discussion on the [mailing list](https://lists.w3.org/Archives/Public/public-bioschemas/2019Jun/0011.html) about ChemicalSubstance and MolecularEntity. These are being resolved in #327.

**Comment by AlasdairGray** [comment]
#327 has now been resolved

**Comment by AlasdairGray** [comment]
@ljgarcia @otienoanyango @ens-ap5 @folago What is the difference between the `hasSequence` property (defined on [Gene](https://bioschemas.org/Gene) and [Protein](https://bioschemas.org/Protein)) and `hasRepresentation` (defined on [BioChemEntity](https://bioschemas.org/BioChemEntity))?

**Comment by ljgarcia** [comment]
@alasdairgray, I would say hasRepresentation is a superset of hasSequence. hasSequence was introduced because the sequence was considered important enough to differentiate it from other possible protein representations.

**Comment by AlasdairGray** [comment]
So we should explicitly declare that relationship between hasRepresentation and hasSequence.

hasSequence is very generic and could be confused with a mathematical sequence. Would hasBioPolymerSequence, as used in SIO, work just as well?

http://www.macs.hw.ac.uk/~ajg33

________________________________

**Comment by AlasdairGray** [comment]
@egonw would it make sense to declare `inChI`, `inChIKey`, and `smiles` as sub-properties of `hasRepresentation`?

**Comment by egonw** [comment]
I did some googling for `hasRepresentation`, but from what I can now see, I would answer positively.

**Comment by AlasdairGray** [comment]
Updated types on [appspot](http://bio.sdo-bioschemas-227516.appspot.com/)

**Comment by eldk** [comment]
Hello,

I have used bioschemas.org/Taxon to qualify some legal_awareness dataset for leisure sea fishing in France, fishes, shells ... This is in test since about a year now for all species that are targeted by some legislation.

Have you an idea of the release date of bioschemas to schema.org ?

Thanks,

Eric

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fwww.opalesurfcasting.net%2Fconnaissances%2Ffaune-et-flore%2Fle-saumon-de-l-atlantique-salmo-salar.html

https://search.google.com/test/rich-results?id=EnYla7r4hYxRyh_uyf6XgA

**Comment by AlasdairGray** [comment]
@eldk sorry for the slow response. We are still discussing with Schema.org how best to incorporate the new types. However, the more deployments, and in particular usage of the markup we can demonstrate the better, so thanks for your effort.

**Comment by AlasdairGray** [comment]
As the types are ready, I'm going to close this issue.

**Comment by AlasdairGray** [comment]
It seems that our discussion here on hasRepresentation and its sub-properties did not make it into the version of the types submitted to schema.org.

We'll need to update these types and then propose them as updates to schema.org. I'll create a new issue for this.
