### ISSUE TITLE
SemanticAnnotation: ScholarlyPublication or ScholarlyArticle

### ISSUE THREAD

**Issue by kcmcleod** [BioSchemas/specifications#322]
[Version 0.1 of SemanticAnnotation](https://bioschemas.org/specifications/drafts/SemanticAnnotation/) uses the type ScholarlyPublication for the subjectOf property. There is no such type in Bioschemas or Schema. Should it be ScholarlyArticle?

**Comment by ljgarcia** [comment]
It should be ScholarlyArticle, thanks for reporting!
