### ISSUE TITLE
Improve website documentation for updating profiles

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#325]
This issue has been created in response to a question raised on the mailing list about how best to engage with the community for updating profiles and types. The response given on the web site follows:

Asking questions on the mailing list is a good starting point, as is creating issues on the issue tracker. These discussions should be centred around example markup and usage of the markup.

Once there is some agreement within the specific group then the (simplified) process would be:

- Add properties to the type if required, or even propose a new type. At this point it is probably easiest to directly involve me in that process.
- Revise the profile by:
  - Creating a new copy of the relevant gSheet and increasing the version number by 0.1
  - Making edits in the spreadsheet and tracking these changes as a summary list on the front sheet (we’re still developing the best practice on this)
  - Running the GoWeb tool over the spreadsheet to generate the web version
  - Creating a pull request on the website and communicating the changes to the community 
- Deploy code on sites, or dev sites, so that we can verify that the approach works in practice

There is then the process of moving a draft profile to current, for which we are keen to see live deployments of the markup on sites.

**Comment by kcmcleod** [comment]
@AlasdairGray Not sure I understand the task. Are you asking for the above website text to be extended/upgraded,  are you suggesting we need alternative instructions that require more explicit text, are you are asking for suggestions or ... ?

**Comment by AlasdairGray** [comment]
This issue has been addressed with the publishing of our Governance document and the tutorials that have been added about profile development.
