### ISSUE TITLE
Tracking changes between profile version – GOWeb feature request

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#326]
@ricardoaat I've been experimenting with tracking the revisions when updating profiles. I have at this point done this with some ad hoc additions to the first sheet in the template, e.g. [Dataset](https://docs.google.com/spreadsheets/d/1IUw5tdUvzTs3ogxgBNYTtUrVtlO2Czv6yiavyNfct8w/edit#gid=1483018794).

It would be good to formalise this and have the GOWeb tool capture this in a way that we can display a summary at the end of the profile page. What are your thoughts on the feasibility of this?

The motivation is to help developers who are updating their markup from one version to another and to aid with the reviewing of a new version of a profile.

**Comment by folago** [comment]
Google sheets are versioned and versions can be named, maybe this is already of some help.
However, to see the versions someone needs edits rights and the diff between version or different sheets is not provided.

Alternatively we could snapshot all the spreadsheets every day in CSV format and commit everything in a git repo.
This is probably easy to automate and it would be possible to tag the commits with the version reached of each type/profile. 
I am not sure this is a good solution, it feels a bit too _scattered_ to be solid.

Another alternative could be to experiment with the spreadsheet API and create an od hoc solution for comparing spreadsheets. For example it would be possible to create a diff spreadsheet from two other spreadsheets.

Is any of these solution worth exploring?

**Comment by AlasdairGray** [comment]
I think having separate files for the different versions is a desirable feature. At the moment, we create a new copy of the file each time work commences on a new version, although this is often forgotten. So perhaps having a single master file which we then save versions from is a more rigorous approach.

I think @guicalman was trying to use the gSheets API when he developed his precursor to GOWeb. A major issue with that was the need to login to google to use the tool. So I would prefer to keep using the CSV approach if we can.

I don't think that there is a need to do daily snapshots, the profiles don't change that much, and the amount of change is likely to decrease over time. An alternative could be to manually snapshot the spreadsheet to CSV and save in github. That would have the nice feature of making the CSV files visible and persistent.

**Comment by gtsueng** [comment]
I'm marking this issue as closed due to deprecation as GoWeb no longer appears to be maintained/supported
