### ISSUE TITLE
ChemicalSubstance and MolecularEntity clarifications

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#327]
There has been a discussion on the [mailing list](https://lists.w3.org/Archives/Public/public-bioschemas/2019Jun/0011.html) seeking clarification on the difference between MolecularEntity and ChemicalSubstance. The answer is due to the basis on the ChEBI ontology.

The following changes are required:
- [x] Description of ChemicalSubstance should be replaced with `a ChemicalSubstance which is 'a portion of matter of constant composition, composed of molecular entities of the same type or of different types' (source: ChEBI).`
- [x] In ChemicalSubstance, replace the property `molecularFormula` with `chemicalComposition` and update the description to `The chemical composition describes the identity and relative ratio of the chemical elements that make up the substance.`
- [x] References to molecular entity within the following ChemicalSubstance properties should be replace with BioChemEntity
  - [x] bioChemInteraction
  - [x] bioChemSimilarity
  - [x] biologicalRole
  - [x] chemicalRole
  - [x] potentialUse

@egonw, @JervenBolleman: Are you happy with these changes? Are there others that we need?

**Comment by AlasdairGray** [comment]
> References to molecular entity within the following ChemicalSubstance properties should be replace with BioChemEntity
> * bioChemInteraction

This property already states BioChemEntity

**Comment by AlasdairGray** [comment]
@egonw I've made these corrections to the [ChemicalSubstance](http://sdo-bioschemas-227516.appspot.com/ChemicalSubstance) type. They also required changes to the [MolecularEntity](http://sdo-bioschemas-227516.appspot.com/MolecularEntity) type.

Please can you verify them using the above links to the appspot deployment. If you are happy, then I will manually copy the types over to the Bioschemas website.

BTW, should the MolecularEntity type also cite ChEBI as its source in the same way we have for ChemicalSubstance? Presumably it would be [CHEBI:23367](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A23367).

**Comment by AlasdairGray** [comment]
@egonw pinging you as a reminder of this. Also, could you review the design notes in these two files:
- [ChemicalSubstanceCodingNotes](https://github.com/BioSchemas/schemaorg/blob/Bioschemas-release-1/data/ext/bio/ChemicalSubstanceCodingNotes.md)
- [MolecularEntityCodingNotes](https://github.com/BioSchemas/schemaorg/blob/Bioschemas-release-1/data/ext/bio/MolecularEntityCodingNotes.md)

**Comment by AlasdairGray** [comment]
@JervenBolleman you should also be aware of the resolution to your comment on the [mailing list](https://lists.w3.org/Archives/Public/public-bioschemas/2019Jun/0011.html)

**Comment by egonw** [comment]
The changes look fine. When reading over the appspot deployment, I made two further changes: https://github.com/BioSchemas/schemaorg/commit/0b922a7ae9d82716e187e2ef31d88175bfa1c9ef

**Comment by egonw** [comment]
@AlasdairGray, and regarding the notes, the following points. About `ChemicalSubstance`, the difference with https://schema.org/Substance is that the latter is strictly limited to (subclassing from) `MedicalEntity`, but a `ChemicalSubstance` and `MolecularEntity` in general are not medical tools and many properties of `MedicalEntity` simply do not apply to the two newly proposed concepts.

**Comment by AlasdairGray** [comment]
Thanks @egonw  for the detail about the coding notes. I'll add that in now.
