### ISSUE TITLE
dataset property in DataCatalog v0.2 has cardinality of ONE

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#330]
Between version 0.1 and 0.2 of DataCatalog, the cardinality of the `dataset` property changed from MANY to ONE. This change is not listed in the [set of changes](https://docs.google.com/spreadsheets/d/1mIRsRHdl9bzGQrOEVcMiwvh5ZsCcGNsNfai2sZOBxQ0/edit#gid=1483018794).

I believe this is an error since a DataCatalog is meant to contain a set of Datasets.

Are there any objections to doing a quick update and releasing v0.3 of DataCatalog with the cardinality of MANY?

**Comment by stylesm** [comment]
Agreed.

**Comment by AlasdairGray** [comment]
We have started the process to move the 0.3-DRAFT to recommended.
