### ISSUE TITLE
BioSample samplingAge property should be type DateTime

### ISSUE THREAD

**Issue by stylesm** [BioSchemas/specifications#332]
Currently the samplingAge property of the BioSample type is an Integer, but this is unclear - is this years, months, weeks, days, hours, minutes, seconds, etc?

It should be a DateTime: https://schema.org/DateTime with associated properties utilised.

**Comment by AlasdairGray** [comment]
@stylesm can you provide an example of how a DateTime can be used to express an age?

**Comment by AlasdairGray** [comment]
I can see how DateTime can be used to capture the date and time when a sample was taken (e.g. 2019-08-30T14:44:03z), but not the age of the subject when the sample was taken (e.g. 3 years 4 months and 16 days).
