### ISSUE TITLE
2 links for crosswalk in some profiles

### ISSUE THREAD

**Issue by kcmcleod** [BioSchemas/specifications#333]
Eg, 
`cross_walk_url: https://docs.google.com/spreadsheets/d/1mIRsRHdl9bzGQrOEVcMiwvh5ZsCcGNsNfai2sZOBxQ0/`
and 
`spec_mapping_url: https://docs.google.com/spreadsheets/d/1mIRsRHdl9bzGQrOEVcMiwvh5ZsCcGNsNfai2sZOBxQ0/`

The `spec_mapping_url` should be deleted

**Comment by kcmcleod** [comment]
*Some* of these have 2 links because 1 refers to the [original cross walk sheet](https://docs.google.com/spreadsheets/d/1cQ6mDbsG_cMX2EDAN8xH6-9yMRba8-rErlPeP8HTs8A/edit#gid=0) & the other refers to a [mapping file](https://docs.google.com/spreadsheets/d/1wgpkliR8S6hoxIRtKTogPtFcLAeGWiUn7FhoViMAxng/edit#gid=1261485211). 

The web pages only use the `cross_walk_url` properties, so (where I can) I have put the mapping file in the `cross_walk_url` property and removed the other link. @AlasdairGray - is this the correct approach? I.e., we don't need/want the [original cross walk sheets](https://docs.google.com/spreadsheets/d/1s342mMwfXAGl5uwgTCcwsVLQztxRIDwTi92zEouP33o)?

For list of draft profiles I can't fix yet:
https://github.com/BioSchemas/specifications/issues/334

For a list of profiles I can't fix yet:
https://github.com/BioSchemas/specifications/issues/335

Types mostly do not have a `cross_walk_url` and none seem to have the `spec_mapping_url`

**Comment by kcmcleod** [comment]
Code in https://github.com/BioSchemas/bioschemas.github.io/tree/remove_spec_property_from_profiles

**Comment by AlasdairGray** [comment]
We only want to have a single link in the file.

The crosswalk sheets should include a back link to the previous version but this is not part of the template at the moment.
