### ISSUE TITLE
GOWeb should generate entire profile page

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#339]
Can we make it so that the output from GOWeb is the entire web page, or at the very least all of the YAML part?

Of crucial importance is that the GOWeb tool should output 
- The link to the spreadsheet as this is often not updated
- The status flag of revision or release as this is often incorrectly set

**Comment by folago** [comment]
How are the html files generated from the yaml?
I can see some examples in the GOWeb repo but I am not entirely sure the process can be fully automated with only the csv file.
Maybe we could add a few fields to get all the information?
Including the link to the spreadsheet and correct revision as well?

**Comment by folago** [comment]
I mean I can see that there is a html template for jekyll and a header that is mostly the yaml file produced by GOWeb but the rest of the header is coming from some other place.

**Comment by kcmcleod** [comment]
> Can we make it so that the output from GOWeb is the entire web page, or at the very least all of the YAML part?

Unlikely as where do you get the redirects from?

> How are the html files generated from the yaml?

Essentially the html files have 3 sections:
* header that contains redirects plus metadata like group, use_cases_url
* a spec_info property (the values of this are generated by GoWeb)
* an html snippet that occurs after the YAML is closed

After running GOWeb, replace the *spec_info* in the HTML with the output of GOWeb. 
Then replace the value of *cross_walk_url* with the url to the gSheet used when running GOWeb. 
We now deleting *spec_mapping_url* as it is not used.

> GOWeb but the rest of the header is coming from some other place.

The header is recycled and is not generated every time the spec is updated.
Guillermo's python tools used to generate these every time; so I suspect when we started using GOWeb we copied & pasted these over and have manually edited them since.

**Comment by AlasdairGray** [comment]
> Unlikely as where do you get the redirects from?

Most of the redirects are a common pattern that could be templated. They are to ensure that old URLs do not end up at a 404, but we could just drop that.

Essentially the html files have 3 sections:

> header that contains redirects plus metadata like group, use_cases_url
> a spec_info property (the values of this are generated by GoWeb)
> an html snippet that occurs after the YAML is closed

I think it is essential that we get the crosswalk URL from the output of GOWeb due to the number of times that this is not updated. Likewise the status [release|revision] needs to come from the GOWeb. These could be extra command line parameters, or the template gSheet could be extended to extract these from the front sheet into the sheet that is then published as a CSV for the tool to use. Most of the other properties could also be gained in the same way.

**Comment by ricardoaat** [comment]
Sure, I will work on this
> The link to the spreadsheet as this is often not updated
> The status flag of revision or release as this is often incorrectly set

These two fields should be easy to include, I am thinking of fetching them from the spreadsheets if present. The spreadsheets could then be updated little by little. 

> These could be extra command line parameters, or the template gSheet could be extended to extract these from the front sheet into the sheet that is then published as a CSV for the tool to use.

Could be both, the command line parameter would take precedence over the CSV. 

It should be easy to include the HTML bit as well, but I need to check it first.

**Comment by AlasdairGray** [comment]
That would be great. While you are doing that, can you also think a bit about how we can track the changes between different versions (#326). We have tried some different approaches in [Taxon DRAFT 0.4](https://bioschemas.org/specifications/drafts/Taxon/) and Dataset/DataCatalog. Note that the Dataset and DataCatalog pages do not show the change history.

**Comment by AlasdairGray** [comment]
Use of GOWeb is being deprecated.
