### ISSUE TITLE
Autogenerate tool markup from https://bio.tools/

### ISSUE THREAD

**Issue by kcmcleod** [BioSchemas/specifications#340]
At ISMB, idea from Mateusz & ? to auto generate the tools markup when someone create a description in bio tools.

**Comment by AlasdairGray** [comment]
There are already on going discussions with various people involved in bio.tools to do this. For example, they have been engaging with the latest revisions of the tool profile meaning that the two models are now compatible.

**Comment by matuskalas** [comment]
We're working on this now at EU BIoHackathon 2019, implemented by @albangaignard and @hansioan.

The idea is to provide both a regular "dump" of all bio.tools data in Bioschemas JSON-LD, and also to include such annotation per record in the HTML, in this order.

**Comment by albangaignard** [comment]
Actions already in that direction with @matuskalas, @hansioan : 
- API to generate BioSchemas markup : https://bio.tools/api/jaspar?format=jsonld 
- Embeded JSON-LD in the web pages : https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fbio.tools%2Fjaspar 
- RDF dump : https://github.com/bio-tools/content/tree/master/scripts/bioschemas 
- https://github.com/bio-tools/content/blob/master/doc/bioschemas.md
