### ISSUE TITLE
Add SynBioHub to list of Live Deploys

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#341]
SynBioHub has markup on various pages. This should be included in the Bioschemas Live Deploys page. SynBioHub is associated with ELIXIR-UK.

- [Home page](https://synbiohub.org/) included DataCatalog and Dataset markup. (I've created this [issue](https://github.com/SynBioHub/synbiohub/issues/986) on the GitHub about the errors in the namespaces.)
- Collection overview pages, e.g. [iGEM_2017/Cell13/1](https://synbiohub.org/public/iGEM_2017/Cell13/1), include Dataset markup
- Individual record pages, e.g. [BBa_K165005](https://synbiohub.org/public/igem/BBa_K165005/10), include BioChemEntity markup

@udp @chrisAta can you advice of any other markup that exists on SynBioHub and can you estimate how many pages include markup?

**Comment by kcmcleod** [comment]
> Collection overview pages, e.g. iGEM_2017/Cell13/1, include Dataset markup

This is not BSc compliant as they do not provide an identifier.
Using the homepage as it does.

> Individual record pages, e.g. BBa_K165005, include BioChemEntity markup

This link 404s. If I change it from https://synbiohub.org/public/igem/BBa_K165005/10 to https://synbiohub.org/public/igem/BBa_K165005/1 I get a page with DataRecord, with BCE as the mainEntity.
* I'm adding this as DataRecord 0.2.2-DRAFT; AND,
* adding BCE has version 0.7-RC

**Comment by AlasdairGray** [comment]
We should still add them to the live deploys.

@udp @chrisAta, please see the comments about what needs correcting.

**Comment by kcmcleod** [comment]
> We should still add them to the live deploys.

everything has been added. I've just used the homepage rather than https://synbiohub.org/public/iGEM_2017/Cell13/1 for Dataset

**Comment by jamesamcl** [comment]
Sorry, currently writing up my thesis and haven't had any time to look at this.  It's awesome to see SBH on the live deploys page, and I'll check out the mentioned issues ASAP.

**Comment by AlasdairGray** [comment]
@udp thanks for making the change to the namespace and creating the issues for updating the other markup. Let us know if you need any help in revising the markup. Good luck with the write up.
