### ISSUE TITLE
Funder or funding

### ISSUE THREAD

**Issue by kcmcleod** [BioSchemas/specifications#343]
https://schema.org/Person has funder:
"A person or organization that supports (sponsors) something through some kind of financial contribution."

However bioschema's Person ignores this and adds funding:
"Textual description of current or past funding ths person has acquired"

Do we stick with funding?

**Comment by AlasdairGray** [comment]
I would suspect that `funder` is a newer property. We should use the `funder` property or `sponsor` property from schema.org rather than trying to define a new property.

**Comment by kcmcleod** [comment]
Neither *funder* nor *sponsor*  is not pending, so I'll add them and remove *funding*.
