### ISSUE TITLE
Update profiles for candidate release types

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#346]
Profiles need updating that have not updated since their corresponding type have been updated.

**Comment by ljgarcia** [comment]
Protein update done, see https://github.com/BioSchemas/bioschemas.github.io/pull/225

**Comment by frmichel** [comment]
Taxon profile 0.4-DRAFT is in line with Taxon type 0.3-RC.

Note that Taxon profile 0.5-DRAFT will be discussed in the next round as it requires new type TaxonName.

**Comment by egonw** [comment]
@AlasdairGray, what is the protocol I should follow to do this?

**Comment by AlasdairGray** [comment]
A first draft of a BioSample profile has been created by @kcmcleod and @petrosss based on the suggestion in #323. This should be appearing in the profiles drafts section of the Bioschemas website today.

**Comment by AlasdairGray** [comment]
Issues relating to Gene are given in detail in #353

**Comment by AlasdairGray** [comment]
Issue to resolve in #410
