### ISSUE TITLE
molecularWeight should be Text, not Mass

### ISSUE THREAD

**Issue by egonw** [BioSchemas/specifications#347]
And for the description/comment is should list as form '<Number>' or '<Number> amu' or '<Number> Da'.

IMO, because '0.01 mg' is for a `Quantity`, but a molecular entity does not have a quantity or volume; at best, it describes a single molecule.

@ljgarcia, what do you think? ([Your patch](https://github.com/BioSchemas/schemaorg/commit/3e693f34a365197ca04a243d946603f2a5833a61#diff-a16404afb9987db50b1acc655f8905e4) introduced it, but the change may have come from somewhere else.)

**Comment by ljgarcia** [comment]
It comes from schema.org, for instance https://schema.org/Mass says "Properties that take Mass as values are of the form '<Number> <Mass unit of measure>'. E.g., '7 kg'.". So, I tried to follow the same pattern for temperatures: "<span property="rdfs:comment">Optimal temperature in the form '<Number> <Temperature unit of measure>', for example '8 Celsius', at which this enzyme performs best.</span>"

Other changes moving the domain from Text or Number to Mass were made to be able to capture the number as well the weight unit, which is possible using Mass. This was done for properties molecularWeight and monoisotopicMolecularWeight. 

If it does not work well to the chemical case, please modify it as it fits best.

**Comment by egonw** [comment]
The unit is different, so I'd say it does not work well. Not because it is chemistry, but in that a molecular weight is a mass / amount. The molecular weight of carbon (graphite, diamond) is 12 g / mole of carbon.

Okay, let's change it back to plain text.

**Comment by egonw** [comment]
@AlasdairGray, okay, remind me... where again do I need to change this? I would go for `Text`, allowing it to include a unit (amu or Da). But cannot figure out where :( (again)

Later: oh, never mind. Found it! https://github.com/BioSchemas/schemaorg/tree/Bioschemas-release-1/data/ext/bio

**Comment by AlasdairGray** [comment]
Is there a reason not to use [Number](https://schema.org/Number) as is used by [emissionsCO2](https://auto.schema.org/emissionsCO2)?

**Comment by egonw** [comment]
Oh, in haste I incorrectly assumed that was a plain number, but it actually supports units. Yes, that sounds like a great suggestion. I'll update my pull request. I need to look up the proper example JSON.

**Comment by AlasdairGray** [comment]
MolecularEntity type has been updated with this [pull request](https://github.com/BioSchemas/schemaorg/pull/2).

We now need to make sure that these changes are reflected in the MolecularEntity profile.

**Comment by AlasdairGray** [comment]
> We now need to make sure that these changes are reflected in the MolecularEntity profile.

This is covered in #346

**Comment by AlasdairGray** [comment]
MolecularEntity profile needs to be updated to correspond with this change

**Comment by AlasdairGray** [comment]
Draft profile 0.4-DRAFT fixes this issue
