### ISSUE TITLE
Bug when editing group pages

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#349]
@AlasdairGray @kcmcleod I just realized that the "edit me" button does not work from the group pages. I am trying to update the LabProtocol page https://bioschemas.org/groups/LabProtocols/. When trying the "Edit me" button, I get a GitHub 404 page https://github.com/BioSchemas/bioschemas.github.io/tree/master/https://drive.google.com/drive/folders/0B0fE3oOZIq44TzFwejFEbE9WdXM_groups/LabProtocols.md

I am happy to directly edit the page on the repository, but would not know what the right page to edit it.

Could you please have a look at it? Thanks!

**Comment by kcmcleod** [comment]
@ljgarcia I think I have fixed this. The link was:
```
https://github.com/BioSchemas/bioschemas.github.io/tree/master/https://drive.google.com/drive/folders/0B0fE3oOZIq44TzFwejFEbE9WdXM_groups/LabProtocols.md
```
but should be 
```
https://github.com/BioSchemas/bioschemas.github.io/tree/master/LabProtocols.md
```

This was caused by the 'edit me' link in header.html which was
```
https://github.com/BioSchemas/bioschemas.github.io/tree/master/{{page.folder}}{{page.path}}
```
I removed `{{page.folder}}` so the links now work.

**Comment by ljgarcia** [comment]
Great, thanks!
