### ISSUE TITLE
Check if ims global metadata is relevant for training material bioschema

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#35]
Check if this is relevant ... http://www.imsglobal.org/metadata/mdv1p3/imsmd_bestv1p3.html

**Comment by anenadic** [comment]
I had a look at it, seems relevant. Will revisit.

**Comment by AlasdairGray** [comment]
[TrainingMaterial profile](http://bioschemas.org/specifications/TrainingMaterial/) was published a long time ago.
