### ISSUE TITLE
email may be dubious because of GDPR

### ISSUE THREAD

**Issue by alaninmcr** [BioSchemas/specifications#350]
There are rules about exposing someone's email address without their explicit permission. The profile needs to make this clear

**Comment by AlasdairGray** [comment]
How about for a first version of the implementation (https://github.com/BioSchemas/bioschemas.github.io/pull/229) we have all requests go to enquiries@bioschemas.org? 

We can probably set up a separate email address just for this which could maybe go to @siiraa instead.
