### ISSUE TITLE
gitbook contribution

### ISSUE THREAD

**Issue by abotzki** [BioSchemas/specifications#351]
Hi, I was wondering whether and how it is possible to contribute to the gitbook. I do not seem to find the repository where some pull requests could be submitted.

Thanks a lot.

Best regards, Alex

**Comment by ljgarcia** [comment]
Not sure how this could be done. We used at that time the free version of GitBook and it allowed us to have four users but as far as I remember, we cannot add new users any more (@ricardoaat please correct me if I am wrong). GitBook is meant to be free for open-source and non-profit teams. @ricardoaat contacted them but I do not recall a reply from them.

**Comment by ricardoaat** [comment]
We did actually, we have a full featured GitBook account for BioSchemas

**Comment by ljgarcia** [comment]
@AlasdairGray has now the access to invite collaborators.

**Comment by abotzki** [comment]
hi thanks for your efforts. Niall Beard sent me an invitation and I could login.
