### ISSUE TITLE
Gene Profile 0.5-DRAFT not in sync with Gene type 0.3-RC

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#353]
Need to do a correspondence check between the properties in the profile and those in the latest version of the type.

**Comment by AlasdairGray** [comment]
Issues to resolve:
- [x] Profile has `encodes` rather than `encodesBioChemEntity`
- [x] `additionalProperty` does not appear in the property list of `Gene`
- [x] `associatedDisease` in profile is missing expected type of `PropertyValue`
- [x] External vocabulary terms should include vocabulary name from which it is drawn in the short representation
  - [x] `enablesMF`
  - [x] `involvedInBP`
  - [x] `isTranscribedInto`
  - [x] `isVariantOf`
- [x] What is the difference between `enablesMF` and `hasMolecularFunction`?
- [x] `hasCategoryCode` is not defined in the property list of `Gene`

**Comment by ljgarcia** [comment]
Changes introduced on Gene profile 0.6-DRAFT-2020_04_02 in response to issue
* encodes property updated to encodesBioChemEntity, still recommended
* additionalProperty removed
* associatedDisease range updated
* examples using DefinedTerm now include link to external vocabularies via property inDefinedTermSet (hasMolecularFunction, isInvolvedInBiologicalProcess, taxonomicRange). Note: isTranscribedInto and isVariantOf do not exist on the Gene type so they were removed, isVariantOf was replaced on Gene type by alternativeOf)
* hasCategoryCode property removed

What is the difference between enablesMF and hasMolecularFunction? Same purpose different name. The current name defined on BioChemEntity type is hasMolecularFunction

Additional changes after looking at BioChemEntity and Gene types:
* hasRepresentation moved to optional. There is another property hasBioPolymerSequence for the sequence text. hasRepresentation can be used to link to a page containing the corresponding sequence so both are now optional and people can decide which one suits better to them
* properties directly from Gene type not previously included on the Gene profile were added as optional (expressedIn and hasStatus)

**Comment by AlasdairGray** [comment]
> * Note: isTranscribedInto and isVariantOf do not exist on the Gene type so they were removed, isVariantOf was replaced on Gene type by alternativeOf)

The profile was reusing specific properties from relevant domain ontologies for things that were felt to be too specific for inclusion in Schema.org but still needed for Bioschemas. We also do this in Taxon. I was thinking that we should capture the ontology common name as a namespace for the property, something like `GO:isVariantOf`. Would that make sense?

As we don't currently have a mechanism for capturing the mapping to domain ontologies, perhaps we should do this in an ad hoc way using the BSC Description column in the spreadsheet?

**Comment by ljgarcia** [comment]
The current alternativeOf was taken from SIO.
I think we have discussed before linking bioschemas properties directly to ontology terms. People pointed out reasoning approaches would be tricky. Not sure I am understanding the comment. I thought we had removed all the "external" ontology terms.

**Comment by ljgarcia** [comment]
If we want to include external ontology terms as part of profiles, there might be a way already in place. On the cross-walks, column D is used to specify the type of the link (schema, pending, bioschemas, external), column E is used to add the actual link (URL) to the property. I am not sure how that is picked by GoWeb though. @ricardoaat can you have a look please?

**Comment by AlasdairGray** [comment]
Let's complete this discussion in #378 and not let it stop this profile going through at this stage.
