### ISSUE TITLE
MolecularEntity profile v0.2draft does not correspond with type 0.3-RC

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#354]
Need to ensure that all property names and descriptions correspond

(Sub-issue of #346)

**Comment by AlasdairGray** [comment]
In June @kcmcleod had updated the mapping file for [v0.3-DRAFT](https://docs.google.com/spreadsheets/d/1V69QsIrwNjbqSM9yN1RfsPvCuPEgUWGhIoUUiITLuAc/edit#gid=1483018794) that corrected the property names, but this was never deployed.

To ensure consistency with the type, a new draft version [0.4-DRAFT](https://docs.google.com/spreadsheets/d/1KXcNfvUCQQ0kYswp2w17ZQ_5I7xXiAX-0XtaGauSloU/edit#gid=1483018794) was created from the type definition. The molecular weight issue (#347) was also fixed as well as an incorrect example removed.

**Comment by kcmcleod** [comment]
@AlasdairGray - not clear what the status of this issue is? it reads though you have fixed it, yet the issue is still open
