### ISSUE TITLE
Protein Profile should suggest ontologies

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#355]
Rather than have this as something blocking [PR255](https://github.com/BioSchemas/bioschemas.github.io/pull/225#pullrequestreview-314799249), I've moved it to an issue to be resolved in the future.

Controlled vocabulary column should suggest ontologies to use rather than 'Any suitable disease ontology'. This applies to:

- [ ] associatedDisease
- [ ] taxonomicRange
- [ ] isPartOfBioChemEntity

In fact for `isPartOfBioChemEntity` shouldn't they be linking to other markup?

**Comment by ljgarcia** [comment]
I would be against suggesting any ontology as there are multiple to choose and arguing in favour of one or another could be a matter of personal/group/lab preferences.
UniProt uses OMIM for human diseases, but they do not cover diseases for any other species so not a good choice. UniProt uses the UniProt Taxonomy but them some others will prefer to use the NCBI Taxon. And, as far as I remember, the biodiversity group mentioned at least two more common options for them when it comes to taxa. @frmichel could probably tell you better.
