### ISSUE TITLE
Improve display of available profiles and types on the website

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#356]
Following from the management call yesterday, I have drawn up a few sketches of possible web structures for the profiles and types pages.

The key goals are to make it clearer which profiles are:
- ‘Released’ and should be used
- Active development, these may be improvements on an existing released profile or profiles working towards their first release
- Deprecated, e.g. there has been no active development of the profile

Here are four alternatives for how this could be presented on the webpage
1. Multiple tables on one page
![bs-multi-table](https://user-images.githubusercontent.com/1141265/68754227-378c6000-05fe-11ea-9fa0-5632375dbbe4.jpg)
1. One table with a status column
![bs-big-table](https://user-images.githubusercontent.com/1141265/68754257-4410b880-05fe-11ea-821e-865520cf1c52.jpg)
1. Tabs within a single page
![bs-tabs](https://user-images.githubusercontent.com/1141265/68754296-525ed480-05fe-11ea-9725-b920aaac4a71.jpg)
1. Multiple pages
![bs-menu](https://user-images.githubusercontent.com/1141265/68754323-5db20000-05fe-11ea-9040-afd18758db0d.jpg)

I think that the third option of using tabs on a single page is the neatest and least cluttered approach.

**Comment by ljgarcia** [comment]
+1 for the third option "multiple tabs"

One question: Are released profiles (I think there is an "s" in picture 1) a historical list of the releases or all currently valid released profiles? The latter would mean that we can have more than one profile released per type. If that is not the idea, I propose to rename as "Latest release"

**Comment by AlasdairGray** [comment]
I would think that tables would only contain the latest [release|working-draft|deprecated] version, with each profile containing links to previous version in them (see #357). However, maybe for release versions we should list all releases. This comes down to a question of whether we believe there will be lots of releases or just one or two.

**Comment by ljgarcia** [comment]
I would go only for the latest release, let's see what others say

**Comment by CaroleGoble** [comment]
when it comes down to it, I want to be able to see which is the release I could be adhering to. Having lots of releases for the same profile will be confusing. The releases are for the ADOPTERS of the profile, not the developers of them. the ADOPTERS of the profiles are the ones that can't figure out whats going on. So latest release with links to previous release

**Comment by nsjuty** [comment]
Agree with Carole.
wrt options, I'd go with either #1 (separate tables on a page) or #3 (tabs)
