### ISSUE TITLE
Improve archive of profile (and type) versions

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#357]
Currently the website is only capable of showing the most recent release and draft version of a profile (and type). However, markup exists on the web that has been created against past versions. We should ensure that we archive past versions of profiles (and types).

In the first instance we should retain all new versions of profiles (and types). We may be able to recreate some of the old ones, but I do not think we should spend effort on this.

We should retain the functionality that the unversioned URL of a profile (and type) takes you to the latest version. However, we should mimic the functionality that the W3C have on their standards (see [DCAT 2.0](https://www.w3.org/TR/vocab-dcat/) for example) where you have links to the most recent working draft, latest released version, and previous version of the working draft.

**Comment by ljgarcia** [comment]
We could keep previous versions on the GitHub repo without exposing them on the web site. Whenever latest accepted changes are incompatible with previous versions, we should make clear that in the release as well. We should also think for how long we are going to keep those previous versions, something like "forever", "up to X versions" or "up to X years" should be part of the profile archiving policy.
