### ISSUE TITLE
Google Rich Snippets Tool

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#358]
Consider adding a link to Google's [Rich Snippets Tool](https://search.google.com/test/rich-results) on the Bioschemas live deploy page along side the [Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool).

The rich snippets tool is able to extract content from dynamically generated sites, but does not display the markup if it is not a type that Google have a product for, i.e. for Bioschemas is would only work for Dataset, DataCatalog, Course, CourseInstance, Tools, and maybe some of the scholarly articles since they are based on CreativeWork.

The Structured Data Testing tool always shows the content that it has extracted, but does not work for dynamically generated sites.

**Comment by ljgarcia** [comment]
+ 1 one to add it.
+ 1 to add our own validator at some point as well, something to keep in mind.

**Comment by AlasdairGray** [comment]
Started working on this on branch [live-deploy-improvements](https://github.com/BioSchemas/bioschemas.github.io/tree/live-deploy-improvements)

**Comment by AlasdairGray** [comment]
Fixed in [PR 250](https://github.com/BioSchemas/bioschemas.github.io/pull/250)
