### ISSUE TITLE
Add STRING protein-protein interaction database to list of live deploys

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#359]
STRING protein-protein interaction database (an Elixir Core Resource) has deployed Bioschemas on their ~25mln protein network pages.

We use Dataset Profile for the protein page (as DataRecord seems to be still a Draft Profile).
The Main Entity on the website has Protein Type and has a Taxon as an additionalType.

Example:
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fstring-db.org%2Fnetwork%2F9606.ENSP00000379258

If you can we would be happy to be added to the Live Deploys list.

**Comment by gtsueng** [comment]
Addressed by https://github.com/BioSchemas/bioschemas.github.io/pull/247
