### ISSUE TITLE
citation Property for https://bioschemas.org/specifications/drafts/Workflow/

### ISSUE THREAD

**Issue by alaninmcr** [BioSchemas/specifications#364]
citation seems to have gone missing

Check its meaning and mandation

**Comment by alaninmcr** [comment]
citation was expected to be how to cite this Workflow. Its actual meaning is a citation or reference to another creative work.  So I do not think citation is what is wanted

**Comment by AlasdairGray** [comment]
citation is used for datasets to provide a link to the creative work that is the paper to cite for the dataset.

This follows the guidance from [google](https://developers.google.com/search/docs/data-types/dataset)
