### ISSUE TITLE
sdPublisher and sdLicense for https://bioschemas.org/specifications/drafts/Workflow/

### ISSUE THREAD

**Issue by alaninmcr** [BioSchemas/specifications#367]
At the moment, these properties are not included.

This needs to be checked

**Comment by alaninmcr** [comment]
sdPublisher is in 0.3

Not obvious what sdLicense would add over license

**Comment by AlasdairGray** [comment]
@alaninmcr the motivation for the sd forms of properties is given in this [schema.org issue](https://github.com/schemaorg/schemaorg/issues/1886). The idea is that a description of a dataset is given on a page that is not the owner of the dataset (@danbri is that an accurate summary?)

I agree that the property names and the descriptions of them do not make this clear. I had to read the above linked issue to understand this.
