### ISSUE TITLE
Workflow Group Members

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#369]
The following snippet of code has been added to the [Workflow group page](https://bioschemas.org/groups/Workflow/)
```
members:
    - VictoriaDominguezDelAngel
    - CaroleGoble
    - stain
    - stuzart
    - fbacall
    - longr
```

To make this work, profiles in the _people directory would need to be created for each of `stain`, `stuzart`, `fbacall`, and `longr`. 

I would suggest that you follow the naming convention of `FirstLast.md` when creating these profiles.

**Comment by AlasdairGray** [comment]
@alaninmcr I'm going to let you fix this issue

**Comment by alaninmcr** [comment]
Will do
