### ISSUE TITLE
Consider owner (contac) and depositor.

### ISSUE THREAD

**Issue by alaninmcr** [BioSchemas/specifications#371]
Both of these seem very important

**Comment by alaninmcr** [comment]
Has creator(s), contributor(s) and sdPublisher. I think those may be enough

**Comment by stuzart** [comment]
relates to #395 - I'm happy with keeping just _author_ and _sdPublisher_ CreativeWork also have _provider_ and _producer_ , I don't think an additional attribute helps

**Comment by alaninmcr** [comment]
Don't bother for now
