### ISSUE TITLE
Add funding

### ISSUE THREAD

**Issue by alaninmcr** [BioSchemas/specifications#373]
https://schema.org/FundingScheme

**Comment by AlasdairGray** [comment]
Does funding help someone find or choose between two workflows?

**Comment by alaninmcr** [comment]
Possibly if they are looking for workflows that were produced, for example, with the help of EU funding.

There is also funding for Projects, programmes (however they would be mapped) and even people's participation. We will need to think about how these overlap / conflict

**Comment by AlasdairGray** [comment]
An important mantra in Bioschemas has been to focus on the 6 properties that will give you the most bang for your buck. We are not looking to markup everything about a given resource. 

While funding may end up being optional, we still don't want a huge list of optional properties as well.

**Comment by alaninmcr** [comment]
Is that mantra written down somewhere? I could do with quoting it :-)

**Comment by AlasdairGray** [comment]
It's stated by example on the home page and given on slide 7 of our latest presentation.

**Comment by stuzart** [comment]
CreativeWork has _funder_

**Comment by alaninmcr** [comment]
Not now
