### ISSUE TITLE
Reconcile Workflow with Tool

### ISSUE THREAD

**Issue by alaninmcr** [BioSchemas/specifications#374]
Tool is a SoftwareApplication ; Workflow is a SoftwareSourceCode.

Tool has a far broader remit but Workflow overlaps it.

**Comment by AlasdairGray** [comment]
You should discuss with @matuskalas who is in the process of finalising the tools profile. 

It would also be worth putting a message out to the mailing list.

**Comment by matuskalas** [comment]
Some reconciliation would certainly be good.

_E.g._ we're going to change the attributes for inputs and outputs in Tool to maximise the overlap with Schema.org (still not concluded how, though). The same conclusion could then be applied to Workflow.

On the other hand, we may also consider Workflow and Tool to be somewhat different angles of view or concern, just like SoftwareApplication _vs._ SoftwareSourceCode. Whether these different angles of view are an unnecessary complication in the scope of Bioschemas, or actually really useful, is something to be perhaps considered in the future (when we have more data and example usage cases) ...

I'll be happy to discuss more.

And CC @albangaignard who's been producing Bioschemas Tool data from bio.tools and biii.eu, the latter having also some workflows to be "Bioschematised".

**Comment by alaninmcr** [comment]
We do have a proposal for workflow inputs and outputs that has not been formalized yet (in the spreadsheets).

For example, a workflow input has:

- id
- name
- description
- type (from EDAM Data class)
- format (from EDAM Format class)
- default value

I do not have strong feelings about SoftwareApplication v SoftwareSourceCode. However, some of my colleagues **strongly** feel it should be source code.

I would be interested in workflows that have been Bioschematised :-)

**Comment by albangaignard** [comment]
Fixed in ComputationalTool 0.6-DRAFT
