### ISSUE TITLE
Broken links to profiles on live deploys page

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#376]
The links to profiles on the live deploys pages still point to the old website structure. These need to be updated to the new addresses. We should also add redirects for the addresses that are used here so that they point to the latest version of a profile (not that those that point to types work as the redirects are in place).

Tasks:
- [x] Update links on live deploys page
- [x] Add redirects for the following patterns `/specifications/{profile-name}` -> `/profiles/{profile-name}`
- [x] DataRecord should point to the profile not the type

**Comment by petrospaps** [comment]
This is done, I will review with you on Thursday and push the changes.

**Comment by petrospaps** [comment]
SequenceRange is not working, all the other links work fine

**Comment by AlasdairGray** [comment]
Currently we do not have a SequenceRange profile. In this case we should point to the type rather than the profile until a profile is made.

**Comment by petrospaps** [comment]
This is fixed as well, I have pushed the fix.
