### ISSUE TITLE
Crosswalk vocabulary column

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#378]
@ricardoaat would it be feasible to add an extra column to the crosswalk template that captures details of equivalent vocabulary terms? The content of the column would need to be processed by the GO Web tool and displayed on the generated profile page, so the question is really can you extend the GO Web tool to process such an additional column?

I'm thinking that the content of the column could be a comma separated list of markdown where we would have the following for the dataset name row:  
`[dct:title](http://purl.org/dc/terms/title), [dats:title](http://biocaddie.github.io/dats/dataset_schema.json#title)`   
which would then display 'Equivalent to [dct:title](http://purl.org/dc/terms/title), [dats:title](http://biocaddie.github.io/dats/dataset_schema.json#title)' somewhere on the profile display table.

**Comment by AlasdairGray** [comment]
Discussions taken from #353 

https://github.com/BioSchemas/specifications/issues/353#issuecomment-607831843
> As we don't currently have a mechanism for capturing the mapping to domain ontologies, perhaps we should do this in an ad hoc way using the BSC Description column in the spreadsheet?

Taken from https://github.com/BioSchemas/specifications/issues/353#issuecomment-608011601 
>If we want to include external ontology terms as part of profiles, there might be a way already in place. On the cross-walks, column D is used to specify the type of the link (schema, pending, bioschemas, external), column E is used to add the actual link (URL) to the property. I am not sure how that is picked by GoWeb though. @ricardoaat can you have a look please?

**Comment by gtsueng** [comment]
I'm marking this issue as closed due to deprecation as GoWeb no longer appears to be maintained/supported
