### ISSUE TITLE
Scholarly Publication Use Cases

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#379]
The use cases for the Scholarly Publication working group should be properly published on the Bioschemas website, not in a Google Document.

**Comment by ljgarcia** [comment]
@AlasdairGray 
Should I add those use cases to the specifications folder? If not, where should they be hosted?

**Comment by AlasdairGray** [comment]
Use cases are hosted on the website in the _useCases folder

**Comment by AlasdairGray** [comment]
As noted [here](https://github.com/BioSchemas/bioschemas.github.io/pull/265#issuecomment-706183328) the use case links are not working.

**Comment by AlasdairGray** [comment]
Appropriate redirects are in place and seem to be working
