### ISSUE TITLE
Add people to mailing lists

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#38]

**Comment by rajido** [comment]
Ask @martin-nc for access to the mailing lists and subscribe people we know so far

**Comment by frenkxs** [comment]
Done! (So far I added the people from the groups in GitHub). All the groups are private at the moment, so people outside can't subscribe to them and can't post new messages. I suppose we can change it in the future.

**Comment by rajido** [comment]
Thanks Prem. I think each team lead could manage subscriptions but I think it would be ideally external people could post to the group. I am reassigning this to Martin to see if he agrees and if he could make this change.

**Comment by rajido** [comment]
Actually let me close this issue and open another one with this specific action

**Comment by frenkxs** [comment]
hi Rafa,

you can leave it open for people outside, so that they can post, but I
couldn't find how you could let people sign up for the group. I guess it
must be possible.

Best,

Premysl
