### ISSUE TITLE
Types display template has wrong subheadings

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#380]
The template for the display of types has an error in the subheadings used to link to the latest and previous releases of a type.

As shown in the screenshot, these use the terminology from the profile template. The use of the word 'Profile' should be replaced with 'Type'.
<img width="1440" alt="Screen Shot 2020-02-24 at 12 57 49" src="https://user-images.githubusercontent.com/1141265/75154283-4efedd00-5705-11ea-9cee-6c93235e9c7e.png">

**Comment by petrospaps** [comment]
this is fixed

**Comment by AlasdairGray** [comment]
Can you create a pull request to merge your working branch with the fix back into master and put me as the reviewer?

**Comment by petrospaps** [comment]
I have already pushed the fix a few days ago.
