### ISSUE TITLE
Links from Groups to Types are broken

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#382]
The list of types that a group has developed is not displaying correctly and the links are broken. As shown in the screenshot, the version numbers are missing. The links still go to the old devTypes directory. 

It is likely that the logic that is used for the profiles needs to be copied for the types.

![Screen Shot 2020-02-28 at 14 19 11](https://user-images.githubusercontent.com/1141265/75556080-6f94a300-5a35-11ea-9810-f40ee29d2f95.png)

**Comment by petrospaps** [comment]
Hi Alasdair, this is a more complex problem, the code looks fine, but I think that the problem is that there is not a devType of ChemicalSubstance and MolecularEntity as they are both missing from the folder. We can discuss on our meeting.

**Comment by AlasdairGray** [comment]
The `devType` folder has been removed, in favour of all types being present in the relevant subdirectory of the `types` folder.

The latest version and release of each type is logged in the `data/type_version.yaml` file. I do not think that we need to show all versions of the developed by the group, just the latest release and draft version. This should mean that you only need to process the `type_version.yaml` file, in the same way that the profiles are processed from the `data/profile_version.yaml` file.

**Comment by AlasdairGray** [comment]
Fixed in https://github.com/BioSchemas/bioschemas.github.io/commit/e21c5c6274fc2d3f7182127fba0e2771693c5542
