### ISSUE TITLE
Meaning of the URL

### ISSUE THREAD

**Issue by alaninmcr** [BioSchemas/specifications#388]
Is this the URL in the WFH (hub) or the target URL? Or is this the URL to get metadata?

**Comment by nsjuty** [comment]
identifier for me is a URL to the hub.
'URL' we may have more than 1.
targetURL (for where it is executed)
sourceURL (the original contributor URL, with their own identifier potentially?)
metaURL - if we are allowing one for metadata, though I would think its embedded in identifier (page)
?

**Comment by AlasdairGray** [comment]
As defined by [Schema.org](https://schema.org/url), it is the url of the item.

I'd suggest that you use `@id` in your JSON-LD and not worry about this property.
