### ISSUE TITLE
Meaning of programmingLanguage

### ISSUE THREAD

**Issue by alaninmcr** [BioSchemas/specifications#389]
Is this the programming language under which the workflow is run? or written? Containers? May want to clarify the language

**Comment by nsjuty** [comment]
This should be under which it is run. We could have a simple flag for container = true/false.

**Comment by AlasdairGray** [comment]
It is not clear to me why the programming language would be a criteria that I would be using to find a workflow. I see that there are no use cases defined for the working group. Having use cases will help guide your decision making process for which properties to use and which are needed.

**Comment by stuzart** [comment]
relates to #396

**Comment by alaninmcr** [comment]
It is what the workflow is written in
