### ISSUE TITLE
Number of licenses

### ISSUE THREAD

**Issue by alaninmcr** [BioSchemas/specifications#391]
People may want to list equivalent licenses

**Comment by nsjuty** [comment]
This is quite common, but I am not sure of a resource where equivalence is mapped specifically.
In its absence, we should have dropdown/lists of licenses with which we are familiar, allowing selection of appropriate one

**Comment by AlasdairGray** [comment]
@alaninmcr Can you point to examples where there are many?

**Comment by stuzart** [comment]
I see no harm in making them MANY, and there are software libraries I use that have multiple licenses so I imagine it would be the same for workflows. A workflow may contain _tools_ that have differing but compatible licenses.

**Comment by alaninmcr** [comment]
Minimum many
