### ISSUE TITLE
runtimePlatform

### ISSUE THREAD

**Issue by alaninmcr** [BioSchemas/specifications#396]
From an operational point of view, runtimePlatform is more important than programmingLanguage. It should be recommended.

**Comment by nsjuty** [comment]
I would say both should be mandatory

**Comment by stuzart** [comment]
I'm unclear what this means? Linux, Windows 95, Solaris, or Docker, Singularity, or Java, Go, Python. I considered programmingLanguage to mean the workflow engine, but that was just my interpretation. If both are mandatory then I think it needs clearly documenting.

**Comment by alaninmcr** [comment]
runtimePlatform is what the workflow is known to run on e.g. AWS, Arvados etc. This is distinct from programmingLanguage.

recommended many
