### ISSUE TITLE
author v creator

### ISSUE THREAD

**Issue by alaninmcr** [BioSchemas/specifications#397]
The difference and choice between author and creator should be checked.

**Comment by nsjuty** [comment]
To me the creator is someone who comes up with the concept, while the author is the one(s) who document it.

**Comment by stuzart** [comment]
I used _author_ to describe those that had created the workflow, and _sdPublisher_ for the person that submitted to the repository and made it available. Both of these come from _CreativeWork_.  I don't think there is a need to define creator separately

**Comment by alaninmcr** [comment]
Use creator - minimum many
