### ISSUE TITLE
Rename input / output

### ISSUE THREAD

**Issue by alaninmcr** [BioSchemas/specifications#403]
Should they be renamed inputs and outputs?

**Comment by nsjuty** [comment]
This refers to the table [here](https://docs.google.com/document/d/1v-NPWfVK5hrkoekIoWUMSzk1m8x6yqW6D3waB0QsNJM/edit#heading=h.lsjzsi86onby), right?

To me input could be a 'type' or a 'format', or both. Should we have InputType, InputFormat? etc?

**Comment by stuzart** [comment]
when adding bioschema.org for Workflow to the Workflow Hub, inputs and outputs are the part I had most difficulty with. In the end it was decided to just describe the type (directly as described in CWL), and also include the name / id where available.

**Comment by alaninmcr** [comment]
Discuss with Stian

**Comment by alaninmcr** [comment]
Many pointing to new structure
