### ISSUE TITLE
Taxon profile 0.4-DRAFT is in line with Taxon type 0.3-RC.

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#408]
Taxon profile 0.4-DRAFT is in line with Taxon type 0.3-RC.

Note that Taxon profile 0.5-DRAFT will be discussed in the next round as it requires new type TaxonName.

_Originally posted by @frmichel in https://github.com/BioSchemas/specifications/issues/346#issuecomment-523360173_

**Comment by AlasdairGray** [comment]
Taxon profile uses `hasCategoryCode` which is not present in list of types for `Taxon` type. 

This also occurs in `Gene` (see #353)

**Comment by frmichel** [comment]
Hey guys, I'm not sure if you expect some inputs from me.

I must admit I don't know what this hasCategoryCode property is meant for. Can you explain?

**Comment by AlasdairGray** [comment]
Hi @frmichel I think this is one that we need to work out for a few types/profiles so I expect that we'll just decide on a best practice approach across all of them. (We're doing some tidying up to get all the profiles/types consistent with themselves.)

`hasCategoryCode` is a way of using a code from an existing set of defined codes, specifically ontology terms, so something that we're likely to make a lot of use of in our domains. Here is an example taken from the Schema.org [hasCategroyCode](https://schema.org/hasCategoryCode) page that links to an ontology term for Czech language.
```
[
        {
                "@context": "http://schema.org/"
        },
        {
                "@type": "CategoryCodeSet",
                "@id": "http://id.loc.gov/vocabulary/iso639-2",
                "name": "ISO 639-2: Codes for the Representation of Names of Languages"
                "hasCategoryCode": "http://id.loc.gov/vocabulary/iso639-2/cze"
        },
        {
                "@type": "CategoryCode",
                "@id": "http://id.loc.gov/vocabulary/iso639-2/cze",
                "codeValue": "cze",
                "name": {
                        "en": "Czech",
                        "fr": "tchèque",
                        "de": "Tschechisch"
                },
                "inCodeSet": "http://id.loc.gov/vocabulary/iso639-2"
        }
]
```

**Comment by ljgarcia** [comment]
Hi Franck,

I was about to pick up this issue when I realized there is a 0.5-DRAFT
cross-walk (
https://docs.google.com/spreadsheets/d/1ZZxL6_9VvlDJCXMf_0JnIzyBHExxA6eFIiEDKr6gFqY/).
However, the website indicates 0.4-DRAFT as the latest one. Why was the
0.5-DRAFT cross-walk not pushed to the repo? What is the real latest
release for Taxon profile?

Regards,

**Comment by AlasdairGray** [comment]
@ljgarcia The answer to your question is in the first comment on this issue. The 0.5-DRAFT that is currently in the Drive folder is starting to separate out a new TaxonName type, although this may only be a profile over the CreativeWork type (see #309).

We may need to bump the number of the current working spreadsheet from 0.5-DRAFt to 0.6-DRAFT and insert the change needed for fixing this issue as a 0.5-DRAFT. If we do this, then all changes need to be made across both spreadsheets.

**Comment by ljgarcia** [comment]
I moved DRAFT 0.5 to DRAFT 0.6 and created a DRAFT 0.5 to respond to this issue. Pull request  https://github.com/BioSchemas/bioschemas.github.io/pull/267

**Comment by frmichel** [comment]
Hi @AlasdairGray, I updated the version number in the spreadsheet 0.5-DRAFT.

The hasCategoryCode is still present in spreadsheet 0.6-DRAFT, shouldn't it be removed from here too?

Also, the drafts on https://bioschemas.org/profiles/ still shows Taxon profile 0.4-DRAFT. Maybe not updated yet.

Franck.

**Comment by ljgarcia** [comment]
Hi Franck,

The hasCategoryCode should be removed from 0.6-DRAFT as well, indeed.
Website still showing 0.4 because the pull request has not been reviewed
yet.

Regards,

**Comment by frmichel** [comment]
@ljgarcia, ok done.

**Comment by AlasdairGray** [comment]
Comments added to PR https://github.com/BioSchemas/bioschemas.github.io/pull/267 as a code review.
