### ISSUE TITLE
Protein discrepancy in expected types of taxonomicRange

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#410]
Protein update done, see https://github.com/BioSchemas/bioschemas.github.io/pull/225

_Originally posted by @ljgarcia in https://github.com/BioSchemas/specifications/issues/346#issuecomment-522915076_

Expected types in profile for `taxonomicRange` property do not match those defined on the type.

**Comment by ljgarcia** [comment]
Changes introduced on Protein profile 0.10-DRAFT-2020_04_02 in response to issue 410
* range of taxonomicRange updated

Additional changes after looking at BioChemEntity and Protein types:
* hasRepresentation moved to optional. There is another property hasBioPolymerSequence for the sequence text. hasRepresentation can be used to link to a page containing the corresponding sequence so both are now optional and people can decide which one suits better to them
