### ISSUE TITLE
Broken links to Bioschemas types in expected types column

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#414]
In the profile display, the link in the expected types column contains an extra `/` when linking to Bioschemas types. Also the base url is the Bioschemas site rather than relative (causes problems for test deployments).

**Comment by bedroesb** [comment]
This is solved in https://github.com/BioSchemas/bioschemas.github.io/pull/446

and can be closed I think @AlasdairGray ?
