### ISSUE TITLE
Review and close our own comments in the event spec doc

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#43]
@andyjenkinson, Richard and @rajido to review and solve our own comments. Now the spec is ready for its first release let try to keep the spec as clean of comments as possible. ... [Event spec](https://docs.google.com/document/d/1CzE_EGDp_II7skKCUFzZUQ7ZSkImkwcEPiQJVpX8YNk/edit?usp=sharing)

**Comment by martin-nc** [comment]
Yes, done this, but left just a few that might be of interest to reviewers.
