### ISSUE TITLE
TaxonName - CreativeWork/Thing properties - are all necessary?

### ISSUE THREAD

**Issue by mjy** [BioSchemas/specifications#430]
I'm not completely familiar with how properties are added, so take comments with a grain of salt.  

In my opinion many of the properties current list CreativeWork and a few from Thing are going to be more confusing than helpful for something like a TaxonName concept.  Certainly example values might be useful. Some thoughts off the top of my head: 

* `Thing#AlternateName` - Is this just not another TaxonName#name?
* `Thing#SameAs` - Practically speaking, how would this work? Is there an example?  Is this homonomy?  Is a webpage that describes the etymology of a TaxonName the SameAs the TaxonName?  
* `CreativeWork#author` - We know Authorship for TaxonNames (broad sense) are loaded.  The CreativeWork that includes the TaxonName may have one set of authors, and the TaxonName, I assume another CreativeWork, may have a subset of those authors, for example.   
* `CreativeWork#contributor` - Given comments on `#author` is this necessary? All TaxonName authors are equal, none are somehow different. Though, I suppose someone who is not a `author`, but is listed in the acknowledgements as helping with the Latin formulation, might be a `contributor`.
* `CreativeWork#award` - How, why, what's the purpose?  Is the idea that by including CreativeWork we just add all the properties to TaxonName? Similarly various others (non-inclusive list): `audience`, `accountablePerson`, `aggregateRating`, `alternativeHeadline`, and many more... I get that we can think creatively and try to populate examples, and shouldn't limit ourselves to how things traditionally have been considered, but at the same time one way to define things is by their aggregate properties.  The aggregate properties possible in this definition don't seem to capture what we think of TaxonNames as?   

One thought experiment: when a TaxonName pops into existence, are the `author`(s) of that name thinking of the properties listed here at that time and wishing to communicate these properties in a technical manner? If they don't provide many of these properties, but they are later inferred and added to the graph after the fact, are those inferred values (e.g. 'alternateHeadline') adding meaning, or confusing to our interpretation of the knowledge graph?

**Comment by AlasdairGray** [comment]
@mjy TaxonName has been positioned as a subclass of CreativeWork as this is where it would fit in the Schema.org vocabulary. Other subclasses of CreativeWork include things like Dataset which also do not fit with many of the properties on CreativeWork. This is exactly the reason why one of the aims of the Bioschemas Community is to develop usage profiles over the types, particularly those more embedded within the Schema.org type hierarchy, so that people developing markup can easily see the 6 to 12 properties that are required for marking up their resource.
