### ISSUE TITLE
updates - Course, CourseInstance and TrainingMaterial profiles

### ISSUE THREAD

**Issue by ppalagi** [BioSchemas/specifications#433]
Dear all,

I’m about to update the properties of the Bioschema profiles that are used in the SIB course descriptions to comply with the latest versions of Course and CourseInstance. The last time we have done this was in 2016, quite a lot has changed since then.

Before updating anything, and as suggested by Leyla, I have checked all the properties of the Course, CourseInstance and TrainingMaterial profiles. For these 3 profiles, some of the properties don’t exist in schemas.org and some are still pending. You will find here, 3 Excel files with my comments showing which are missing or pending (in the tabs with my name).

[Course Mapping - Cape Town Review #6.xlsx](https://github.com/BioSchemas/specifications/files/4973517/Course.Mapping.-.Cape.Town.Review.6.xlsx)
[TrainingMaterial - Cape Town Review #6.xlsx](https://github.com/BioSchemas/specifications/files/4973518/TrainingMaterial.-.Cape.Town.Review.6.xlsx)
[CourseInstance Cape Town Review #6.xlsx](https://github.com/BioSchemas/specifications/files/4973519/CourseInstance.Cape.Town.Review.6.xlsx)

Besides, I’m bugged with the **description**, **abstract**, **about** and **keywords** properties in those three profiles. I have tried to show where I’m bugged below - in italic the definitions in Bioschemas (the misspellings are not mine :). 

Sorry for the long message. And if this message should be sent to another list, please let me know.

I would be happy to discuss with anyone about this or help push things forward whenever needed.

Thanks and all the best,

Patricia

--
Patricia Palagi, PhD
SIB Training
SIB | Swiss Institute of Bioinformatics
Quartier Sorge, Bâtiment Amphipôle - 1015 Lausanne - Switzerland
patricia.palagi@sib.swiss - www.sib.swiss

Description: A description of the item. 

    in Course = Minimum, Example: This is a course ran at an institution. It's ran periodically - specific courses can be found through  CourseInstance

    in CourseInstance = Optional - (CourseInstance) description can be used to override (Course) description for varations in specific Course Instances.

    in TrainingMaterial = Recommended, Example: This tutorial will take you through the basic usage of the command line shell. In it, you will discover what a shell is, skills for directory navigation, file manipulation, and how to run tools. To complete this training material you will need to have a shell (linux), powershell (windows), or terminal (mac) ready. You do not need any previous experience to complete the tasks

Abstract: A short, succinct description of the resource. 

    in Course = Optional, Example: This tutorial will take you through the basic usage of the command line shell. In it, you will discover what a shell is, skills for directory navigation, file manipulation, and how to run tools

    in CourseInstance = absent, if in Cours, the

    in TrainingMaterial = Recommended, Example: This tutorial will take you through the basic usage of the command line shell. In it, you will discover what a shell is, skills for directory navigation, file manipulation, and how to run tools

Why I’m bugged: Description and abstract seem redundant. Both give a summary description of the object, but the examples show different things. For a course, if only the Description is given, the information in that field will not be enough to grasp the topic/content of the object which is in fact in the abstract that is optional or in the about (see below, which is also only Recommended). Besides, there is a new term (teaches, pending also) that could be also seen as the abstract and description ([see this blog here](https://blogs.pjjk.net/phil/new-properties-for-learning-resources-in-schema-org/)).

About: The subject matter of the content. 

Use the DefinedTerm type to add a controlled vocabulary term to categorise the course (such as using the [EDAM Topic ontology]

Example:  ""@type"": ""DefinedTerm"", 

  ""@id"": ""http://edamontology.org/topic_3316"",

  ""inDefinedTermSet"": ""http://edamontology.org"",

  ""termCode"": ""topic_3316"",

  ""name"": ""Computer Science"",

    in Course = Recommended. Inverse property: subjectOf.

    in CourseInstance = absent, 

    in TrainingMaterial = Recommended. (and not described as Inverse property: subjectOf)

Keywords: Keywords or tags used to describe this content. Multiple entries in a keywords list are typically delimited by commas. "RNA-Seq, Workshop", 

    in Course = Minimum

    in CourseInstance = absent, 

    in TrainingMaterial = Minimum

 

Why I’m bugged: about and keywords seem redundant in my view, and both should be using EDAM as much as possible.

**Comment by AlasdairGray** [comment]
Let me first address the use of `about` and `keywords`. My guess is that the need for both of these stems from the needs of the search engines to be able to index and make use of the markup. The search engines will not be familiar with the EDAM IRIs which is why the keywords are requested. My guess is that TeSS makes use of the `about` property to enable its faceted search.

**Comment by AlasdairGray** [comment]
@ppalagi great to hear that you are updating the SIB pages to the latest version of the profiles. It would be very helpful if you could update the spreadsheets, particularly with fixing the typos when you see them. Once this is done please let @ljgarcia or myself know and we'll run the machinery required to get them on the website.

**Comment by AlasdairGray** [comment]
Let me first address the use of `about` and `keywords`. My guess is that the need for both of these stems from the needs of the search engines to be able to index and make use of the markup. The search engines will not be familiar with the EDAM IRIs which is why the keywords are requested. My guess is that TeSS makes use of the `about` property to enable its faceted search.

**Comment by AlasdairGray** [comment]
With regard to `abstract` and `description` my best guess would be that they are both used since `abstract` is still in pending but I was not in the discussions to know.

**Comment by mbrazas** [comment]
Description and abstract are both used so that these schemas cover the widest education/training audience. In working group discussion post Cape Town, the logic decided upon is that universities wanting to use the schema would need a place to enter the course code (~description) as well as abstract about what the course is about. Workshops likely would only need abstract, unless they had a coding system as well.

**Comment by vdda** [comment]
Hi,
Here are the draft of the Bioschemas profiles 
[Bioschemas profiles](https://bioschemas.org/profiles/) . 
From my point of view, we must see that all the tabs (groupe, use Cases, cross walk.. etc ) be updated before to have the final  release. I asked for access to the "use Case" tab. do you have access  @mbrazas or @ppalagi  to these ?

**Comment by ppalagi** [comment]
> @ppalagi great to hear that you are updating the SIB pages to the latest version of the profiles. It would be very helpful if you could update the spreadsheets, particularly with fixing the typos when you see them. Once this is done please let @ljgarcia or myself know and we'll run the machinery required to get them on the website.

Thank you, @AlasdairGray. Once we have any updated version of the profiles, we'll let you and @ljgarcia know.

**Comment by philbarker** [comment]
@ppalagi just on the point about [teaches](https://schema.org/teaches) in schema.org, it's not really like abstract or description, or even about; it's for pointing to specific learning objectives. It's essentially the same as `learningOutcome` in https://bioschemas.org/profiles/Course/0.7-DRAFT-2019_11_08/

**Comment by philbarker** [comment]
@mbrazas why use `description` for course codes and not [`courseCode`](https://schema.org/courseCode) ?

**Comment by ppalagi** [comment]
> @ppalagi just on the point about [teaches](https://schema.org/teaches) in schema.org, it's not really like abstract or description, or even about; it's for pointing to specific learning objectives. It's essentially the same as `learningOutcome` in https://bioschemas.org/profiles/Course/0.7-DRAFT-2019_11_08/

I'm not so sure... I interpret the description of [teaches](https://schema.org/teaches) as "in this course, the teacher will teach you x, y and z", or "in the reference term, we will cover x, y and z topics", which in my view are similar to about and description. While `learningOutcome` in https://bioschemas.org/profiles/Course/0.7-DRAFT-2019_11_08/, is centred on the learner: at the end of this term, you should be able to do a, b and c. But this is my interpretation...

**Comment by philbarker** [comment]
@ppalagi I am pretty sure what I meant when I wrote the description for teaches, but it may be open to different interpretations :)

My interpretation: "The item being described[1] is intended to help a person[2] learn the competency[3] or learning outcome[4] defined by the referenced term[5]." 
1, it's about the thing being described, not what the teacher will do.
2, it's about a person learning something.
3, competency is commonly broken down into "knowledge, skills and abilities" so the person learns the same things as referenced bioschemas `learningOutcome`.
4, it can point to a learning outcome, just like bioschemas `learningOutcome`
5, the referenced term is what the property points to (the definition of the competency or learning outcome), it's not the item being described (the course)

The choice of name for the term was influenced by a previous decisions to use "teaches" as an alignment type. There was discussion of learningOutcome, intendedLearningOutcome, learningObjective and all that, but schema tends to favour non-technical terms. Naming things is difficult.

**Comment by ppalagi** [comment]
Hi @philbarker. Thank you! Good to hear from the person who wrote the descriptions :). Now that you have explained, it makes a much better sense for me. Your explanation is worth to be added to the description.

**Comment by mbrazas** [comment]
@philbarker - @ppalagi, @ljgarcia and I have met several times now and have sorted through and resolved the various reasons for selection of our properties. Thanks for your help.

However a couple of questions have arisen in our thorough review of where we are to date with the Course, CourseInstance and TrainingMaterial profiles. 
1) educationLevel - this does not adequately describe the skill level needed by a given Course, as educationLevel does not seem to encompass beginner, intermediate and advanced; rather it covers schooling grade and degrees achieved. Is our interpretation of educationLevel correct? Is there another property that describes skill level or would the introduction of 'skillLevel' as a property be useful?
2) mentions - this property does not seem to be able to emphasize usage of other creative works in a creative work/Training Material. We often have training materials that 'uses' other creative works or profiles (e.g. protein, etc) extensively in the content of the training material. Is there another property that emphasizes usage of other creative works rather than mentions? Or would the introduction of 'uses' as a property be useful here?

**Comment by philbarker** [comment]
@mbrazas happy to help.

1. educationalLevel does encompass beginner, intermediate, advanced or any other way you wish to describe progression through an educational or training context. See the schema.org [definition](https://schema.org/educationalLevel), which explicitly includes this usage.

2. you're right, `mentions` has no particular emphasis. I'm not entirely sure what your use case is, but you may find terms from oerschema.org that are useful, for example relating to [AssociatedMaterial](http://oerschema.org/AssociatedMaterial/) and in particular [ReferencedMaterial](http://oerschema.org/ReferencedMaterial/).  You could use schema.org/hasPart to relate a Course to the ReferencedMaterial

**Comment by AlasdairGray** [comment]
> educationalLevel does encompass beginner, intermediate, advanced or any other way you wish to describe progression through an educational or training context. See the schema.org definition, which explicitly includes this usage.

This is exactly the sort of usage guidance that the profiles are aimed to provide. In the vocabulary column you can limit the terms to the different skill levels that you are looking to be used.

**Comment by mbrazas** [comment]
@AlasdairGray - Can we get a folder for Course and another for CourseInstance added to the Specifications folder in Github please? We are almost ready to compile our examples file.
Thanks.

**Comment by AlasdairGray** [comment]
That's great to hear @mbrazas. Folders have been added.

**Comment by AlasdairGray** [comment]
@ppalagi @mbrazas have all the issues within this thread been resolved, at least for TrainingMaterial?

**Comment by ppalagi** [comment]
yes, they have been resolved in TrainingMaterial, Course and CourseInstance.
