### ISSUE TITLE
LabProtocol appears not to have description

### ISSUE THREAD

**Issue by alaninmcr** [BioSchemas/specifications#436]
The LabProtocol profile does not have a property for description.

**Comment by ljgarcia** [comment]
Hi @alaninmcr, indeed that property was removed in the [0.4 DRAFT](https://bioschemas.org/profiles/LabProtocol/0.4-DRAFT-2020_07_23/). It was used to specify in free text purpose, application, limitation and so but it was replaced by properties targeting all theses elements. Would you suggest to add it back? An alternative to description (depending what you have in mind) could be abstract. What do you think about it?

**Comment by oxgiraldo** [comment]
Hi **@alaninmcr**,
as said **@ljgarcia**, the "description property" was replaced by properties targeting all these elements (purpose, application, limitation, advantages, outcome). Abstracts, when are available in protocols, include some of the elements before mentioned. We decide to include purpose (as minimum requirement); and application, advantages, limitation and outcome (as recommended requirement) as a way to guide the author of a protocol to report this kind of information. On the other hand, the use of these properties makes it easy for users to know if the protocol is suitable for their research.

**Comment by AlasdairGray** [comment]
Thinking of this in the wider context of search engines I think that `description` should be present as it is a useful generic property that can allow the data to be reused in many applications

**Comment by ljgarcia** [comment]
As description is probably more commonly used by search engines, we will go for *description* with the property description provided by schema.org ["A description of the item"](https://schema.org/description). @alaninmcr @AlasdairGray @oxgiraldo would you suggest to add a new Bioschemas property description? if so, what would be the text?

Should we include as well *abstract*? ["An abstract is a short description that summarizes a CreativeWork."](https://schema.org/abstract). Any thoughts? To me, it looks like that having both of them is somehow redundant.

**Comment by oxgiraldo** [comment]
**@alaninmcr @AlasdairGray** , Thank you for your comments. **@ljgarcia**, I suggest to reuse only the property description provided by schema.org "A description of the item".

**Comment by ljgarcia** [comment]
So we will add description property as suggested by @alaninmcr Now, what would be the preference: minimum, recommended or optional? 

@oxgiraldo @AlasdairGray @alaninmcr Do we want to add abstract property as optional as well? Some other specifications (see (TrainingMaterial)[https://bioschemas.org/profiles/TrainingMaterial/0.7-DRAFT-2019_11_08/]) have them both. If abstract is included, I would suggest having it as optional.

**Comment by oxgiraldo** [comment]
Hi **@ljgarcia** as I said before, I suggest to reuse only the property description provided by schema.org "A description of the item"; in addition, I suggest add this property as optional.

**Comment by ljgarcia** [comment]
Perfect, description as described at schema.org will be, we have a plan! thanks!

**Comment by gtsueng** [comment]
This appears to have been addressed by https://github.com/BioSchemas/bioschemas.github.io/pull/320. Unless @oxgiraldo suggests otherwise, it will be closed.
