### ISSUE TITLE
Labprotocol keywords as elements not as a single string

### ISSUE THREAD

**Issue by jjkoehorst** [BioSchemas/specifications#437]
I noticed that keywords is a single string and that the elements are internally separated by a certain separator.

For example:

{
  "@type": "LabProtocol",
  "keywords": "wet lab, disease, chemical"
}

Would it not be more logical that this becomes an array? Such that each keyword can more easily be indexed / searched for?

**Comment by AlasdairGray** [comment]
Unfortunately this is the way it is defined in [schema.org/keywords](https://schema.org/keywords) and so something that we are stuck with.
