### ISSUE TITLE
LabProtocol minimum requirements (title)

### ISSUE THREAD

**Issue by jjkoehorst** [BioSchemas/specifications#438]
The minimum requirements for a lab protocol does not include a title and I was actually wondering what the reasoning behind this could be? 

To me it would make sense to add this to the minimum / obligatory requirements for minimal identification.

**Comment by ljgarcia** [comment]
Hi @jjkoehorst I think you are right. @oxgiraldo any reason why that property was not included? Should we go for it?

**Comment by oxgiraldo** [comment]
Hi **@jjkoehorst**, you are right. The title should be added as minimum requirement. Thank you.

**Comment by gtsueng** [comment]
This appears to have been addressed by https://github.com/BioSchemas/bioschemas.github.io/pull/320. Unless @oxgiraldo suggests otherwise, it will be closed.
