### ISSUE TITLE
Training Group Use Cases

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#439]
> Here are the draft of the Bioschemas profiles [Bioschemas profiles]https://bioschemas.org/profiles/) . 
> From my point of view, we must see that all the tabs (groupe, use Cases, cross walk.. etc ) be updated before to have the final  release. I asked for access to the "use Case" tab. do you have access  @mbrazas or @ppalagi  to these ?

_Originally posted by @vdda in https://github.com/BioSchemas/specifications/issues/433#issuecomment-673518207_

It seems that the use case document has gone astray, perhaps it has been deleted. The best course of action would be to update the [Training Group Use Case](https://bioschemas.org/useCases/TrainingMaterial/) and have all three specifications point to it.

**Comment by mbrazas** [comment]
Sorry I do not have access to grant you access. This is where the logic of having myself and Gabry lead breaks down.
Michelle

--
Michelle D. Brazas, Ph.D.
Senior Program Manager, Adaptive Oncology
Project Manager, Cancer Genome Collaboratory

To learn about our Informatics research resources, click here<http://oicr.on.ca/collaborative-research-resources#hide2>
Ontario Institute for Cancer Research
MaRS Centre
661 University Avenue, Suite 510
Toronto, Ontario, Canada M5G 0A3

Tel: 416-673-8502
Cell: 416-357-6687
FAX: 416-977-7446
Toll-free: 1-866-678-6427 ext. 8502
Email: michelle.brazas@oicr.on.ca<x-msg://1768/michelle.brazas@oicr.on.ca> <http://michelle.brazas@oicr.on.ca<http://michelle.brazas@oicr.on.ca/>>
www.oicr.on.ca<http://www.oicr.on.ca/>

**Comment by AlasdairGray** [comment]
Can we get the content of the file onto the website, the page to edit is at https://github.com/BioSchemas/bioschemas.github.io/blob/master/_useCases/TrainingMaterial.html

**Comment by AlasdairGray** [comment]
Use case already published on the website
