### ISSUE TITLE
LabProtocol element protocolAdvantage description not clear in combination with property

### ISSUE THREAD

**Issue by jjkoehorst** [BioSchemas/specifications#440]
The property protocolAdvantage would suggest that this protocol has some advantage over another protocol and would refer to that. The description however suggests the following:

`Situations where the Protocol has been successfully employed (see more information here)`

This to me does not fit the name of the property perhaps `protocolSuccess` could fit the description better or the description  could be something like `Protocols to which this protocol has an advantage (e.g. better yield, shorter running time)`

**Comment by ljgarcia** [comment]
@jjkoehorst what about keeping the protocolAdvantage property name but changing the description to "Situations where the Protocol has been successfully employed including advantageous elements (e.g. better yield, shorter running time)"
What do you think?

**Comment by AlasdairGray** [comment]
I wonder how this property helps satisfy the search or summarisation [use cases defined](https://bioschemas.org/useCases/LabProtocol/). It seems a very specific property.

**Comment by alaninmcr** [comment]
Trying to list the "situations where the Protocol has been successfully employed" is not useful (IMO). If the LabProtocol is used again, is it expected that the field will somehow be updated?

For use of the LabProtocol, it is equally (or more) important to know where the LabProtocol does **not** work.

**Comment by oxgiraldo** [comment]
**@jjkoehorst**, thanks for your comment. The definition should be improve. What do you think about the following definition "_Situations where the Protocol has advantageous elements compared to other alternatives (e.g. better yield, shorter running time, greater number of samples tested at the same time, etc.)_". Thanks @jjkoehorst and @ljgarcia for the suggestions.

**Comment by oxgiraldo** [comment]
**@AlasdairGray**, the property 'protocolAdvantage' is a recommended requirement not a minimum or obligatory requirement. In other words, where applicable, this information should be included.

**Comment by ljgarcia** [comment]
@alaninmcr, regarding your comment on "equally (or more) important to know where the LabProtocol does not work", there is a property protocolLimitations described as "Situations where the Protocol would be unreliable or otherwise unsuccessful" I think it covers the cases were the protocol does not work, does not it?

**Comment by AlasdairGray** [comment]
> **@AlasdairGray**, the property 'protocolAdvantage' is a recommended requirement not a minimum or obligatory requirement. In other words, where applicable, this information should be included.

That doesn't address my question of how this helps with search for a protocol.

**Comment by ljgarcia** [comment]
@AlasdairGray  A user might be interested in protocols known as being successful or having advantages regarding x or y or z. Having a protocolAdvantage makes this search easier.

**Comment by oxgiraldo** [comment]
**@AlasdairGray**, to filter a search, the user may be looking for a DNA isolation protocol. as filters then the user could further specify that he/she is interested in a protocol suitable for processing both plants and animals tissues. Or, the user may also simply specify that he/she is interested in only DNA isolation protocols for animals tissues and shorter running time.

**Comment by gtsueng** [comment]
This appears to have been addressed by https://github.com/BioSchemas/bioschemas.github.io/pull/320. Unless @oxgiraldo suggests otherwise, it will be closed.
