### ISSUE TITLE
totalTime definition in LabProtocols

### ISSUE THREAD

**Issue by jjkoehorst** [BioSchemas/specifications#441]
Out of curiosity I was wondering if the totalTime indicates the actual minutes / hours the experimentalists is performing tasks for the protocol. Thus when there is a step to incubate a substance for 3 hours this is not taken into account but pipetting preparations which takes ±30min on average in a given step is recored?

**Comment by ljgarcia** [comment]
Hi @jjkoehorst following the schema.org description, totalTime includes preparation time as well; it could be minutes or hours as far as it is expressed as an (ISO duration format)[https://en.wikipedia.org/wiki/ISO_8601]. 
There are two other options that could also be used: (performTime)[https://schema.org/performTime] which does not include preparation time and (prepTime)[https://schema.org/performTime] which corresponds only to preparation time. @oxgiraldo suggestion was having only the totalTime. What would be your thoughts there?

**Comment by oxgiraldo** [comment]
**@jjkoehorst**, totalTime includes the time that an experimentalist requires to execute or carry out a protocol.
For example, if a protocol includes the execution of 3 steps:  1) the incubation of a sample for 3h, 2) pipetting preparations and 3) centrifugation of samples for 30 min. You could say that the totalTime of execution of this protocol is approximately 4 hours.

**Comment by ljgarcia** [comment]
@jjkoehorst any thoughts on this? Is it clearer now? Do you think the description of the property is clear enough? Do you think is there any need to add the other two possible times as optional? Thanks!

**Comment by jjkoehorst** [comment]
I think it’s a good point to include the full duration of the experiment making it clear hoe long the overall experiment lasts.

Within each step it is then possible to define the time duration via


timeRequired | Duration | Approximate or typical time it takes to work with or through this learning resource for the typical intended target audience, e.g. 'PT30M', 'PT1H25M'.
-- | -- | --

As this is slightly different than totalTime

**Comment by oxgiraldo** [comment]
**@jjkoehorst** , here we are representing a protocol not an experiment. An experiment could include one or more protocols, in order to test a hypothesis. A protocol may be used for many different experiments.

Therefore, the property totalTime is used to represent the time required to carry out or execute just one protocol.

**Comment by ljgarcia** [comment]
Hi @jjkoehorst, @oxgiraldo I am adding here the one property about time in CreativeWork and three more coming from HowTo so we all have the full picture. I am also adding the (dis/)advantages I find.

(timeRequired)[https://schema.org/timeRequired]: Approximate or typical time it takes to work with or through this learning resource for the typical intended target audience, e.g. 'PT30M', 'PT1H25M'
* Disadvantage: It seems to target learning resources and it does not seem to use a standard format for time (I imagine PT is performed time but I guess TU for time used could be fine here), also, it is not sure when the required time should start counting (does it include or not preparation time?)

(performTime)[https://schema.org/performTime]: The length of time it takes to perform instructions or a direction (not including time to prepare the supplies), in ISO 8601 duration format.
* Advantage: It is more specific than timeRequired and less ambiguous, it refers to an ISO standard
* Disadvantage: It does not include preparation time (however, it could also be that time with no preparation is what a user wants to know)

(prepTime)[https://schema.org/prepTime]: The length of time it takes to prepare the items to be used in instructions or a direction, in ISO 8601 duration format.
* Advantage: It is more specific than timeRequired and less ambiguous, it refers to an ISO standard
* Disadvantage: It only includes preparation time (however, it could also be that preparation time is what a user wants to know)

(totalTime)[https://schema.org/totalTime]: The total time required to perform instructions or a direction (including time to prepare the supplies), in ISO 8601 duration format.
* Advantage: It is more specific than timeRequired and less ambiguous, it refers to an ISO standard
* Disadvantage: No way to know how long the preparation vs the perform time is

Proposal:
* Let's keep totalTime as recommended
* Let's add performTime and prepTime as optional
* Let's not use timeRequired (it is a bit ambiguous and less specific than the other three) 

Does it sound like a plan?

**Comment by alaninmcr** [comment]
I like that plan. We do not want to get "hung up" on this as we could end up discussing about how the different values relate to each other.

**Comment by oxgiraldo** [comment]
I like too that plan, thanks **@ljgarcia**, **@alaninmcr** and **@jjkoehorst**.

**Comment by jjkoehorst** [comment]
I like this plan too!

**Comment by gtsueng** [comment]
This appears to have been addressed by https://github.com/BioSchemas/bioschemas.github.io/pull/320. Unless @oxgiraldo suggests otherwise, it will be closed.

**Comment by ljgarcia** [comment]
Same here @gtsueng, those issues about LabProtocol that have been addressed can be closed. Thanks
