### ISSUE TITLE
LabProtocol profile base type

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#443]
Currently the LabProtocol profile states that it goes over the Schema.org CreativeWork type rather than the LabProtocol type.

Probably just need to change the metadata in the top of the file.

**Comment by ljgarcia** [comment]
I will add it to the set of changes for next draft.

**Comment by gtsueng** [comment]
This appears to have been addressed by https://github.com/BioSchemas/bioschemas.github.io/pull/320. Unless @oxgiraldo suggests otherwise, it will be closed.

**Comment by ljgarcia** [comment]
also looks good to me @gtsueng, I think we can close it, thanks
