### ISSUE TITLE
Denied access to spreadsheets for various profiles

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#445]
When trying to access the crosswalk spreadsheets for ComputationalWorkflow 0.5-DRAFT, 0.4-DRAFT and Workflow 0.3-DRAFT I get an access denied message. These spreadsheets do not appear in the group's shared google drive [directory](https://drive.google.com/drive/folders/10QSvgnEGFXTeOT8qz4-4xwZgLT5GJrqG).

I've managed to recover a copy of the deleted 0.2-DRAFT spreadsheet, but the link in the website needs to be updated to https://docs.google.com/spreadsheets/d/1AhjSXhJbzw3hT5mdMJ2HjccRfQoSwtjixlyYg33SXOo/edit#gid=1483018794.

**Comment by alaninmcr** [comment]
According to the history of that folder, they were deleted on 31st July by Jael Castro

**Comment by AlasdairGray** [comment]
Hmm...interesting. I've just found the Activity information which is where I'm guessing you got that information @alaninmcr . However I see it as an L Smith who did the removal (see attached screenshot).

Do you know who 'L Smith' might be in your group, or is this a case of internet sabotage? The folders are open for anyone to edit.

![Screen Shot 2020-09-02 at 16 25 42](https://user-images.githubusercontent.com/1141265/92003602-26e9d980-ed39-11ea-8b19-b8bb4a13ee34.png)

**Comment by AlasdairGray** [comment]
This issue is not just affecting ComputationalWorkflow. It is affecting several other profiles including
- Protein: only some spreadsheets, generally older ones
- DataRecord
- Course
- CourseInstance
- Disease
- ...

All files were removed by L. Smith on 31 July.

**Comment by ljgarcia** [comment]
Hi all, 
The one mentioned by @alaninmcr would be my old EBI account but I have not access to it any more and it is supposed not to exist any more (@AlasdairGray just in case, I suggest to block/deny access if possible my old EBI email). We also saw some missing mapping files for the training specs (not sure if related) and for LabProtocols (maybe related, I had recently worked on that one). I recovered the one about LabProtocol with no problem, it was me who created with my current gmail account so not permissions problems. @alaninmcr was it you or Stian who created the workflow ones? The original creator should be able to restore them. Or maybe the owner of the bioschemas GDrive, @AlasdairGray do you know who that be?

**Comment by AlasdairGray** [comment]
I believe that this issue has been resolved.
