### ISSUE TITLE
DataRecord 

### ISSUE THREAD

**Issue by huberrob** [BioSchemas/specifications#450]
Dear BioSchemas team,

According to the draft type DataRecord specs here: https://bioschemas.org/types/DataRecord/0.3-DRAFT-2019_06_20/ this type is derived from 'Dataset' and the only additional property is 'includedInDataset'. 
What are your plans with this draft type? I would recommend to not include this type in the next BioSchemas version. 
Such a relation already can be handled by the standard Dataset property 'isPartOf'. 

Robert

**Comment by AlasdairGray** [comment]
Hi @huberrob, thanks for the message. The idea for a DataRecord type is to distinguish an individual record from the dataset type. Without a DataRecord type, folk tend to use Dataset for individual records which then pollutes registries such as Google's Dataset search with lots of individual records.

While I agree that the relationship can be captured with `isPartOf`, that is a very generic property which doesn't allow us to convey that we have a DataRecord that is included within a specific Dataset. However, it could be that `includedInDataset` should be a sub-property of `isPartOf`. 

`DataRecord` can be seen to be analogous to `DataFeed`.

**Comment by alaninmcr** [comment]
Are you sure you mean "DataRecord can be seen to be analogous to DataFeed"? Isn't it more correct that a DataRecord would be analogous to a DataFeedItem which is a dataFeedElement of a CompleteDataFeed ?

**Comment by huberrob** [comment]
Thanks @AlasdairGray,
so I assume  DataRecord is a entity similar to what we know from the [TDWG ABDC](https://www.tdwg.org/standards/abcd/)  standard where this is called 'Unit' ? Or is this the wrong analogue?  
Robert

**Comment by AlasdairGray** [comment]
> Are you sure you mean "DataRecord can be seen to be analogous to DataFeed"? Isn't it more correct that a DataRecord would be analogous to a DataFeedItem which is a dataFeedElement of a CompleteDataFeed ?

Yes, you are correct. `DataRecord` is analogous to `DataFeedItem`, but with the link being from the `DataRecord` to the `Dataset` as it is anticipated that a `Dataset` will contain many `DataRecords` and it is therefore simpler to include the link from the `DataRecord` to the `Dataset`.

**Comment by AlasdairGray** [comment]
> Thanks @AlasdairGray,
> so I assume DataRecord is a entity similar to what we know from the [TDWG ABDC](https://www.tdwg.org/standards/abcd/) standard where this is called 'Unit' ? Or is this the wrong analogue?

That looks to be correct. The ABDC definition for a `Unit` is:
> A class to join all data referring to a unit such as specimen or observation record.

Here is an example of how we have used `DataRecord` in Bioschemas. [DP00086#DR](https://www.disprot.org/DP00086) is a DisProt Data Record for the protein Cellular tumor antigen p53 identified as DP00086. You can see the resulting markup on the [Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool?url=https://www.disprot.org/DP00086#url=https%3A%2F%2Fwww.disprot.org%2FDP00086).

**Comment by alaninmcr** [comment]
Should look at https://developers.google.com/search/docs/data-types/dataset#tabular

This indicates how tabular datasets should be marked up to show up in Google. It leverages [csvw](http://www.w3.org/ns/csvw#)

**Comment by AlasdairGray** [comment]
A tabular dataset contains multiple rows. A DataRecord would be akin to a single row of the table, although it often pulls in rows from multiple tables.

The DataRecord is meant for the data about a single concept rather than a collection of concepts.

**Comment by AlasdairGray** [comment]
The Bioschemas community have decided that DataRecord introduces an unnecessary complication into the development and use of markup and has consequently deprecated the use of it.
