### ISSUE TITLE
Revision bioschemas/Tools vs spreadsheet 0.5 DRAFT

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#454]
Changes in [ComputationalTool 0.5-DRAFT](https://docs.google.com/spreadsheets/d/1B7Ei57KSY13AFzWNNjvXnvKB5t7PxQAL7lvNOjisQ2o/edit#gid=1483018794) vs [published 0.4_DRAFT](https://bioschemas.org/profiles/Tool/0.4-DRAFT-2019_07_19/)
* Profile name changes from Tool to ComputationalTool
* properties come from SoftwareApplication and SoftwareSourceCode both of them CreativeWork. As ComputationalTool parent type is SoftwareApplication, any property coming from SoftwareSourceCode will require changes in schema.org
* Example link is not valid
* Changelog is not part of the description but on separated rows
  ** outputFormat depracated (removed) and replaced by serviceOutput (note: domain in schema.org is Service so it would require changes in schema.org
* additionalType still in use, its use is discouraged by Bioschemas (double check with @AlasdairGray )
* applicationCategory and applicationSubCategory add URL as range (not present in schema.org but generally a URL or Text are always allowd, double check with @danbri)
* author remains the same but still has a text TODO as Bioschemas description
* contributor remains the same but still has a text TODO as Bioschemas description
* discussionURL remains the same but still has a text TODO as Bioschemas description
* edam:has_input, new property, not in the schema.org space
* funder remains the same but still has a text TODO as Bioschemas description
* hasPart remains the same but still has a text TODO as Bioschemas description
* identifier remains the same but still has a text TODO as Bioschemas description
* provider property has the description as the property name on the spreadsheet

**Comment by ljgarcia** [comment]
@AlasdairGray @CaroleGoble @nsjuty @newgene please find here the assessment for the ComputationalTool. There are still bits that should be solved before moving to 0.5-DRAFT. Who else should I ping about this?

**Comment by AlasdairGray** [comment]
The 0.5-DRAFT spreadsheet is work that was done at the BioHackathon last year in Paris. We should get this up on the website and then use that as the starting point for a 0.6-DRAFT with the issues that you raise above as the starting point.

At that point we should bring in the Tools Working Group, although the membership of that looks to be out of date, so perhaps reaching out to the bio.tools team who worked on this 0.5-DRAFT.

So, my proposal would be to get the 0.5-DRAFT generated and backdate it to 26 November 2019. Then bring in Matus Kalas and Alban Gaignard to address the issues identified above.

**Comment by AlasdairGray** [comment]
We already have a branch with the 0.5-DRAFT on it https://github.com/BioSchemas/bioschemas.github.io/compare/tools-0.5-DRAFT

**Comment by AlasdairGray** [comment]
Branch is very old, it will be safer to delete the branch and recreate the 0.5-DRAFT from the spreadsheet.

**Comment by ljgarcia** [comment]
We should get the draft worked on the BioHacakthon 2019 published.

**Comment by AlasdairGray** [comment]
That is the 0.5-DRAFT ready to publish as [PR341](https://github.com/BioSchemas/bioschemas.github.io/pull/341).

I suggest that we extract the issues that you raised above as separate GitHub issues that should be worked on for a 0.6-DRAFT, and close this issue.

**Comment by albangaignard** [comment]
Fixed in 0.6-DRAFT. One new issue created regarding the `additionalType` property.
