### ISSUE TITLE
Review/comments of Workflow specifications

### ISSUE THREAD

**Issue by dgarijo** [BioSchemas/specifications#456]
Per request of @alaninmcr, I reviewed the following specs, detected a few issues and made some suggestions:

https://bioschemas.org/types/ComputationalWorkflow/0.1-DRAFT-2020_07_21/
- Legend has "CD = Cardinality", but it's never used in this page. Why not remove it?
- In the legend I suggest to start with the color code in the sentence, instead of having it at the end. The sentences are not even, and I was missing the green color code because it's at the end (this is a small detail though).
- I understand that the properties that are listed in this page follow the schema.org example. However, I find it hard to discern which are the properties one should use for describing a workflow, it's up to the reader's interpretation. For example, I don't know if accessMode is really useful, or accessibilityHazard, isBasedOn, isFamilyFriendly... I recommend linking to the workflow profile page, which is more useful; or highlighting with a color or other means the properties that should be used in workflows.
- Why is there no "documentation" associated with a workflow? I see there is publication, but usually workflows are not documented in papers thoroughly. However, they may have wikis, readmes, wikis, etc. where more information about the workflow is described. This is one of the fields that someone reusing the workflow would like to see (e.g., more than funding)

https://bioschemas.org/profiles/ComputationalWorkflow/0.5-DRAFT-2020_07_21/
- I really like the format of this page and the examples. Very nice work.
- Why some properties do not have examples? There are things like "isBasedOn" that I have never seen used in a workflow, so I if there are no examples, I am not sure they will be used.
- The example for `input` reads as type "PropertyValueSpecification" instead of "FormalParameter". 
- The example for `programmingLanguage` is "Text" instead of "ComputerLanguage"
- I think that `producer` is a little confusing in this context. Since producer comes from CreativeWork, it makes sense e.g., in a movie. In a workflow who is the producer? The funding organization? If this is the intended use, please provide an example. 
- The example `targetProduct` is "Text" instead of SoftwareApplication
- The definition of "input" and "output" do not start with a capital letter

https://bioschemas.org/types/FormalParameter/0.1-DRAFT-2020_07_21/
- Legend has "CD = Cardinality", but it's not used in this page.
- Same as above: which properties are needed for FormalParameter? Linking to the profile would be very helpful
- valueRequired definition reads: "Whether the input/output must be specified Whether the property must be filled in to complete the action. Default is false." I think the intended definition is: "Whether the FormalParameter must be specified. Default is false."

https://bioschemas.org/profiles/FormalParameter/0.1-DRAFT-2020_07_21/
- I think adding examples would help enormously here. In particular, for 2 cases: Formal parameter being an input/output file; and formal parameter as an input value .
- Why is `additionalType` of cardinality ONE? As the definition states "typically used for adding more specific types from external vocabularies". It should be possible to have multiple additional types.
- How am I supposed to define input files? (i.e., input values that have been fixed in a workflow) Is it through default value? Having an example would really help here, because I guess the "url"  property could also be used to define this.
- I don't understand what the identifier is supposed to represent for formal parameters. 
- See issue #452 for properties we found very useful in our work. Maybe for a future release.

**Comment by AlasdairGray** [comment]
> * Legend has "CD = Cardinality", but it's never used in this page. Why not remove it?
> * In the legend I suggest to start with the color code in the sentence, instead of having it at the end. The sentences are not even, and I was missing the green color code because it's at the end (this is a small detail though).
> * I understand that the properties that are listed in this page follow the schema.org example. However, I find it hard to discern which are the properties one should use for describing a workflow, it's up to the reader's interpretation. For example, I don't know if accessMode is really useful, or accessibilityHazard, isBasedOn, isFamilyFriendly... I recommend linking to the workflow profile page, which is more useful; or highlighting with a color or other means the properties that should be used in workflows.

These are useful suggestions for improving our standard template for types and profiles.

**Comment by AlasdairGray** [comment]
Tasks:
https://bioschemas.org/types/ComputationalWorkflow/0.1-DRAFT-2020_07_21/
- [x] Link to documentation such as wikis, readmes, wikis, etc. where more information about the workflow is described. This is one of the fields that someone reusing the workflow would like to see (e.g., more than funding)
- [x] Link to FormalParameter type in Expected Types column are not working

https://bioschemas.org/profiles/ComputationalWorkflow/0.5-DRAFT-2020_07_21/
- [ ] Provide examples for all minimal and recommended properties
- [ ] Correct example for `input` 
- [ ] Correct example for `programmingLanguage` 
- [x] Add clarification text for `producer` and example of intended usage
- [ ] Correct example `targetProduct` 
- [ ] Capitalise description of  `input` and `output` properties
  - [ ] Ensure that the descriptions between the profile and the type are consistent

https://bioschemas.org/types/FormalParameter/0.1-DRAFT-2020_07_21/
- [x] `valueRequired` definition should be consistent with Schema.org definition – _further clarification text can be included in the profile_
 
https://bioschemas.org/profiles/FormalParameter/0.1-DRAFT-2020_07_21/
- [x] Provide examples for all minimal and recommended properties
- [x] Respond about `additionalType` cardinality
- [x] Clarify usage of `identifier` property
- [x] Resolve #452

**Comment by AlasdairGray** [comment]
> [x] Link to FormalParameter type in Expected Types column are not working

@alaninmcr I'm curious how you fixed this as I believe it is an issue with the website

**Comment by alaninmcr** [comment]
Yes. I edited the HTML :-) I changed #FormatParameter to /FormalParameter

**Comment by AlasdairGray** [comment]
On which branch have you made that change as I don't see anything on the branch of the [pull request](https://github.com/BioSchemas/bioschemas.github.io/pull/335)

**Comment by alaninmcr** [comment]
Pushed changes for the review.

It was not clear how to specify the changes

**Comment by ljgarcia** [comment]
Hi @alaninmcr @AlasdairGray I am looking at the pending tasks for DRAFT 5 (currently published) and I deselect some of the checkboxes as they are not solved yet (in version 5).

Now, looking at the PR https://github.com/BioSchemas/bioschemas.github.io/pull/335, the pending tasks from DRAFT 5 would look like:

Profile
- [X] Provide examples for all minimal and recommended properties
- [X] Correct example for `input` 
- [X] Correct example for `programmingLanguage` 
- [x] Add clarification text for `producer` and example of intended usage
- [X] Correct example `targetProduct` 
- [X] Capitalise description of  `input` and `output` properties
- [ ] Ensure that the descriptions and ranges between the profile and the type are consistent

So, the last one is missing. I suggest to address it before accepting the PR. For instance, the ranges for ```documentation@type``` are not the same as ```documentation@profile```. This potentially has an impact in examples as well

**Comment by alaninmcr** [comment]
These comments relate to release 5 (I think). Do they still apply to the RELEASE pull request?

**Comment by ljgarcia** [comment]
Yes, they do relate to the PR. What I did was checking those open issues for Profile DRAFT 0.5 and see whether they were addressed by PR Type Release 1. The pending point is the last one: Ensure that the descriptions and ranges between the profile and the type are consistent. For instance, the ranges for ```documentation@type``` are not the same as ```documentation@profile```. This potentially has an impact in examples as well

**Comment by alaninmcr** [comment]
I have fixed the problem with documentation@type links

I have made the contributors the same. There was a bug in _includes/type_start so I copied the code from profile_start

I have (at Carole's request) changed the subtitle for the ComputationalWorkflow profile

All the issues should now be resolved
