### ISSUE TITLE
Need help to provide examples for the training materials spec

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#46]
https://docs.google.com/document/d/1HG2fEjCoDUE4tn1XZ_ZIeWLEFXnI3YtS_FRIIFIbv-s/edit?usp=sharing

**Comment by AlasdairGray** [comment]
[TrainingMaterial profile](http://bioschemas.org/specifications/TrainingMaterial/) was published a long time ago.

Examples are available from https://github.com/BioSchemas/specifications/tree/master/TrainingMaterial/examples/
