### ISSUE TITLE
Is MediaObject the appropriate type for the input and output of a ComputationalTool?

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#465]
In [PR 341](https://github.com/BioSchemas/bioschemas.github.io/pull/341#issuecomment-723016838), @alaninmcr raised the following issue:

> I have great doubts about the ComputationTool / Tool specification. It says that it hasInput and serviceOutput of type MediaObject. This is (in my opinion) very wrong. A MediaObject would be something that satisfies a Tool's input (or output) when the Tool is / has been run. It is not a placeholder to be filled in.

**Comment by matuskalas** [comment]
I fully agree with @alaninmcr's concern. In the previous versions these used to be placeholder to specify what find of data is expected as inputs and outputs, using the EDAM ontology concepts as values.

**Comment by albangaignard** [comment]
I completely agree too, this should describe the nature of the input / output, when the tool is executed and should not refer to a concrete file.

**Comment by hmenager** [comment]
discussed the issue today with @albangaignard and raised similar concern:
- serviceOutput is not the way to specify a "tool result type", which is what we want.
- I would argue that for consistency reason we use similar (but not identical) properties to describe tool inputs and outputs, e.g. using EDAM as suggested by @matuskalas above.

**Comment by albangaignard** [comment]
ComputationalTool profile v0.6-DRAFT now uses FormalParameter type for `input` and `output` properties.
