### ISSUE TITLE
ComputationalTool 0.5-DRAFT uses properties outside of schema.org

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#466]
In [PR 341](https://github.com/BioSchemas/bioschemas.github.io/pull/341#pullrequestreview-524996272), @ljgarcia raised the issue
>  properties outside the scope of schema.org

**Comment by albangaignard** [comment]
This also apply to ComputationalWorkflow profile with input and output properties. (https://schema.org/input cannot be dereferenced )

**Comment by alaninmcr** [comment]
Yes it needs to be fixed for both. Alasdair knows some magic with the URL resolution settings.

**Comment by AlasdairGray** [comment]
Trying to understand what the issue here is. 

In the [CT-0.5-DRAFT](https://bioschemas.org/profiles/ComputationalTool/0.5-DRAFT) `edam:has_input` is correctly displaying as an external property. Are there other properties that should also be showing as external? Are there other properties affected and if so how?

In the [CT-0.6-DRAFT](https://bioschemas.org/profiles/ComputationalTool/0.6-DRAFT) `input` is displaying as a Schema.org property. Should this be a Bioschemas proposed property? Are there other properties in this category?

**Comment by ljgarcia** [comment]
Ideally, there should not be external properties. Is there nothing in schema.org that can be used instead of edam:has_input?

**Comment by AlasdairGray** [comment]
> Ideally, there should not be external properties. Is there nothing in schema.org that can be used instead of edam:has_input?

The 0.6-DRAFT has replaced the EDAM properties with properties that the Bioschemas community are proposing to Schema.org. I was wanting @albangaignard to verify that I'd understood the issue correctly and that there were no other properties that I was missing.

There is a proposed fix for this on branch [issue-466](https://github.com/BioSchemas/bioschemas.github.io/tree/issue-466).

**Comment by albangaignard** [comment]
Thanks. I added this issue for the next milestone : https://github.com/BioSchemas/specifications/milestone/10. 

In addition, there is no more `additionalType` property, which has been replaced by applicationCategory.  For me it's ready for review.
