### ISSUE TITLE
Create SequenceAnnotation profile

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#468]
We have a SequenceAnnotation type and it has been used by DisProt ([DP00086](https://www.disprot.org/DP00086)). We now need to create the profile to correspond to the usage.

**Comment by ljgarcia** [comment]
I tried the markup extracted from the page in the JSON Playground and it gave me an error.
I need an example on how they are using SequenceAnnotation and what the requirements are (if not captured by the example)

**Comment by AlasdairGray** [comment]
Started work on this on branch https://github.com/BioSchemas/bioschemas.github.io/tree/sequence-annotation

- [ ] Need to update GDrive folder name
~~- [ ] Need to update the examples folder name on GitHub~~

**Comment by AlasdairGray** [comment]
@ljgarcia that is the profiles and the proteins group updated on the branch referenced above.

I'm working on updating the Protein type, but doing this a new simplified approach for doing the types. Hopefully it will work.

If you want to start reviewing the profiles that would be great:
- Protein
- SequenceAnnotation
- SequenceRange
ProteinAnnotation has been deprecated in favour of SequenceAnnotation

**Comment by AlasdairGray** [comment]
New type approach is looking promising. the screenshot below is made from a slightly modified version of the JSON-LD representation grabbed from the schema.org site :) Just need to extend the logic to grab the types in the hierarchy.
<img width="700" alt="Screen Shot 2021-06-10 at 17 00 42" src="https://user-images.githubusercontent.com/1141265/121558335-80401100-ca0d-11eb-8e5e-08a958b99207.png">

Changes that are needed to the json-ld are:
- Convert using playground to expanded version
- Remove all `@` signs
- Remove all namespaces from json keys

**Comment by AlasdairGray** [comment]
@ljgarcia I now have the approach working for the Protein type (version 0.4-DRAFT). The source file is https://github.com/BioSchemas/bioschemas.github.io/blob/sequence-annotation/_data/types/Protein.json

Let me know your thoughts on this approach?

**Comment by AlasdairGray** [comment]
This approach for types, while promising has some challenges, e.g. how to deal with parent types changing at different rates and keep things in sync with Schema.org evolutions.

I'm going to separate out this development of a new types process from the updates to the Protein type so that the publishing of the draft profiles and types is not delayed.

**Comment by AlasdairGray** [comment]
@ljgarcia Should the new property `hasSequenceAnnotation` be a property of `BioChemEntity` or should it be defined only on the types that it is pertinent for, i.e. `Gene` and `Protein`?

I think it should be the latter.

**Comment by AlasdairGray** [comment]
Response from Egon via the [mailing list](https://lists.w3.org/Archives/Public/public-bioschemas/2021Jun/0003.html)

> The property does not make sense for all BioChemEntities, particularly not for MolecularEntity or ChemicalSubstance... while schema.org is typically loose, I think this may confuse people.

**Comment by ivanmicetic** [comment]
> @ljgarcia Should the new property `hasSequenceAnnotation` be a property of `BioChemEntity` or should it be defined only on the types that it is pertinent for, i.e. `Gene` and `Protein`?
> 
> I think it should be the latter.

Although `hasSequenceAnnotation` should be present in `Protein` and `Gene`, I would include it also in `BioChemEntity`. `BioChemEntity` can be used to describe things that are assemblies of proteins or clusters of genes or possibly other things. For example a chimera or artificial protein could be modelled as a `BioChemEntity` (with a specific sequence) which has a list (`itemListElement`) of `Protein`s (each with it's own sequence - a fragment of the whole sequence).

**Comment by AlasdairGray** [comment]
- [ ] We need an example of a Gene sequence annotation

**Comment by ljgarcia** [comment]
Start reviewing the profiles that would be great:

- [X] Protein: 04-DRAFT profile includes a new property hasSequenceAnnotation. Looks good to me
- [X] SequenceAnnotation: 0.7-DRAFT profile supercedes ProteinAnnotation profile. Looks good to me except for the property ```hasRepresentation``` which appears red (meaning it comes from schema.org) when it should be green (it comes from Bioschemas and it is defined in BioChemEntity). @AlasdairGray the issues point to ProteinAnnotation, should we change this to SequenceAnnotation?
- [x] SequenceRange: 0.1-DRAFT needs some changes in the examples --rangeEnd has a rangeStart example, rangeStart has a rangeEndExample, endUncertainty and startUncertainty need examples

**Comment by ljgarcia** [comment]
> 
> 
> @ljgarcia Should the new property `hasSequenceAnnotation` be a property of `BioChemEntity` or should it be defined only on the types that it is pertinent for, i.e. `Gene` and `Protein`?
> 
> I think it should be the latter.

Same as @AlasdairGray and @egonw I think it should be the latter but @ivanmicetic has a case for it to be at the BioChemEntity level. As BioChemEntity is not really meant to be used (there is no profile for it), I guess it is ok to add it there. @egonw what would you say?

**Comment by ljgarcia** [comment]
Start reviewing the profiles that would be great:

SequenceAnnotation: 

- [x] update ```hasRepresentation``` which appears red (meaning it comes from schema.org) when it should be green (it comes from Bioschemas and it is defined in BioChemEntity). @AlasdairGray I did not find a reason why the property is displayed in red rather than green, please have a look, thanks
- [x] @AlasdairGray the issues point to ProteinAnnotation, should we change this to SequenceAnnotation?

SequenceRange: 

- [X] rangeEnd has a rangeStart example, 
- [X] rangeStart has a rangeEndExample, 
- [X] endUncertainty and startUncertainty need examples

**Comment by AlasdairGray** [comment]
> > @ljgarcia Should the new property `hasSequenceAnnotation` be a property of `BioChemEntity` or should it be defined only on the types that it is pertinent for, i.e. `Gene` and `Protein`?
> > I think it should be the latter.
> 
> Same as @AlasdairGray and @egonw I think it should be the latter but @ivanmicetic has a case for it to be at the BioChemEntity level. As BioChemEntity is not really meant to be used (there is no profile for it), I guess it is ok to add it there. @egonw what would you say?

@ljgarcia this was discussed at the [community call on Monday](https://docs.google.com/document/d/1kd5F97ogdiPNhLTnkei-RVR8TC8Ohpc5QSPX3KsfDrk/edit#heading=h.98egkfgjx50f) with the decision that we would add the property to BioChemEntity.

**Comment by AlasdairGray** [comment]
Latest set of commits on this branch, ending with commit https://github.com/BioSchemas/bioschemas.github.io/commit/df57889d6f01302be67c908d9159ce989152e330, update the BioChemEntity type to include the hasSequenceAnnotation property. I've updated the Protein and Gene types to inherit this new property.

In doing this, I've started tidying up the types approach so that common elements, e.g. inherited types like BioChemEntity, are shared across definitions. This uses a new `types` folder within the `_includes` folder. I've also defined a type page layout. All of this is a step in the direction of simplifying the types process.

**Comment by AlasdairGray** [comment]
> @AlasdairGray the issues point to ProteinAnnotation, should we change this to SequenceAnnotation?

Good point, updated now

**Comment by AlasdairGray** [comment]
> update hasRepresentation which appears red (meaning it comes from schema.org) when it should be green (it comes from Bioschemas and it is defined in BioChemEntity). @AlasdairGray I did not find a reason why the property is displayed in red rather than green, please have a look, thanks

You are right that they should not be red. They should be blue since they are now (or at least next week) in the pending area.

**Comment by AlasdairGray** [comment]
Outstanding issues:
- [ ] Example for Gene connecting to a sequence annotation (perhaps this can come from Ensembl @ens-ap5 ?)
- [x] Examples for the following properties on SequenceAnnotation
  - [x] sequenceOrientation
  - [x] sequenceValue

**Comment by ljgarcia** [comment]
One more point to solve.

- [ ] Clarify options and improve description of sequenceOrientation

I do not know who could help here. I thought the orientation would refer to 3-5 or 5-3 but the possible values are 1, 0, -1

**Comment by AlasdairGray** [comment]
Outstanding issues relate to the types and have now been moved to a new issue.
