### ISSUE TITLE
How to make the distinction between multiple input / output parameters sharing the same "type" (EDAM data class) ?

### ISSUE THREAD

**Issue by albangaignard** [BioSchemas/specifications#471]
For example if a tool has two inputs typed as "medical images", in an image registration process, it's not possible to distinguish the input parameter specifying the "reference" image and the input parameter specifying the "floating" image. 

The same issue arises when considering reference and "to be aligned" sequences has input parameters for a sequence alignment tool.  

The [FormalParameter](https://bioschemas.org/types/FormalParameter/0.1-DRAFT-2020_07_21/) type introduced in the ComputationalWorkflow profile could be used here to describe the role of computational tools parameters, similarly to [P-Plan Variables](https://www.opmw.org/model/p-plan17092013/#Variable). 

(@matuskalas @alaninmcr @hmenager)

**Comment by matuskalas** [comment]
Indeed, it would be nice to have a way to annotate 2 separate I/O "fields" even if they are the same type of data (_e.g._ the **query** and **target** sequences).

I guess that they may then benefit from some kind of an additional label to really make sense to the viewer/consumer of the annotation...

And in addition: also to distinguish **one I/O "field" annotated with multiple concepts** _versus_ **multiple "fields"**.

**Comment by albangaignard** [comment]
ComputationalTool profile v0.6-DRAFT now use FormalParameter to identify `inputs` and `outputs`.
