### ISSUE TITLE
Develop tutorial layout and include Bioschemas markup

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#479]
The GitBook content has been migrated across to the [tutorials](https://bioschemas.org/tutorials/) part of the website and extended.

We should follow the content of the [How to add schema.org to a GitHub Pages site](https://bioschemas.org/tutorials/howto/howto_add_github) tutorial to develop layouts and embed markup within the tutorial parts of the website.

**Comment by AlasdairGray** [comment]
Starting to work on this on branch [tutorial-layout](https://github.com/BioSchemas/bioschemas.github.io/tree/tutorial-layout).

**Comment by AlasdairGray** [comment]
@ljgarcia can you check:
1. That the latest version of the branch deploys on your machine without needing any additional dependencies deployed
2. You get valid markup on the page http://localhost:4000/tutorials/howto/howto_check_deploy/
You should get 
```json
<script type="application/ld+json">
         {"@context":"https://schema.org/","@type":"LearningResource","about":"Checking that your markup is deployed and retrievable.","audience":[{"@type":"Audience","name":"WebMaster"}],"name":"How to check your Bioschemas deployment","author":["Alasdair Gray"],"contributor":[{"@type":"Person"}],"description":"Check that your markup is deployed on your site and retrievable through common tools.","keywords":["schemaorg","JSON-LD"],"license":"CC-BY 4.0","version":1.0}
      </script>
```

**Comment by AlasdairGray** [comment]
@ljgarcia the tutorial template is now working for two tutorials, with the markup being used to display standard content such as heading, author, description at the top of the page.
- http://localhost:4000/tutorials/howto/howto_check_deploy/
- http://localhost:4000/tutorials/howto/howto_add_github/

I have also added `nextTutorial` and `previousTutorial` blocks of YAML for the navigation blocks between tutorials.

Tasks still remaining which I will leave to you and others are:
- [x] Styling the display of the markup
- [x] Adding markup to the remaining tutorials 
- [x] cleaning them up

**Comment by ljgarcia** [comment]
Thanks @AlasdairGray, looking good!

I am not the best for styling the markup so let's hope for some help in there.
I will add more markup to other pages (hopefully before our community meeting next week)

**Comment by AlasdairGray** [comment]
We should add the progress on this to the community call for Monday and request if anyone else can help with the styling.

**Comment by ljgarcia** [comment]
Additional mark up done. Item added to community call agenda

**Comment by AlasdairGray** [comment]
I've updated the Getting Started menu. It now points to the tutorials on our site and has a sub-menu of some key tutorials.
@ljgarcia  please remove the sub-menu or update the choice of sub-menu items if you prefer different ones.

**Comment by ljgarcia** [comment]
@AlasdairGray I would leave the sub-menu as it is (i.e., with the items you added)
Is this ready to go live?

**Comment by AlasdairGray** [comment]
I believe so. I think that the two open action points should be opened as new issues.

**Comment by ljgarcia** [comment]
Let's create a PR and find a reviewer for it!

**Comment by AlasdairGray** [comment]
[PR](https://github.com/BioSchemas/bioschemas.github.io/pull/380) created

Issued generated for longer term fixes of style and content.
