### ISSUE TITLE
Recommend property to connect markup to profile to which it conforms

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#481]
A property is required to let consuming applications know which Bioschemas Profile it complies with, and specifically which version. This is related to #294 which recommends that `@id` and `@type` are included in the boilerplate template, but wanted to capture in its own issue to ensure that it doesn't get forgotten.

Boilerplate for Bioschemas markup should include a link to the profile against which the markup complies. The [`dcterms:conformsTo`](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/conformsTo/) property has been used for a couple of years now for this purpose and is included in the template markup from the BioschemasGenerator.

**Comment by stain** [comment]
See also #297

**Comment by AlasdairGray** [comment]
The below screenshot shows what is being proposed as part of #294 
![Screen Shot 2021-06-11 at 16 14 56](https://user-images.githubusercontent.com/1141265/121709269-497eff00-cad0-11eb-954d-4dfa8d8ade33.png)
