### ISSUE TITLE
Missing use cases

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#485]
There are no use cases for the chemical profiles, it would be good to add them.

**Comment by egonw** [comment]
Proposal: 

```
Finding information about chemicals is an open challenge. There are plenty of databases
that have been collecting properties in central places, but at the same time there is a long
list of databases and smaller and larger website with essential information about these
chemicals, their properties, their use cases, that are not currently systematically aggregated.
BioSchemas is the door to the long tail of chemical information, opening niche databases
and overviews of chemical information found on websites. The `MolecularEntity` and
`ChemicalSubstance` profiles will allow us to recognize chemical information. The
`ChemicalSubstance` profile, for example, is starting to be adopted by projects from the
NanoSafety Cluster (NSC) and associated with the ELIXIR Toxicology Community being
established. Using website scraping, information about nanomaterials will be collected
and made available in the NSC databases.
```

**Comment by egonw** [comment]
@ljgarcia, @AlasdairGray, sorry I could not find time to provide this earlier. This use case is under active development, tho not particularly going fast either, but not stalled. cc @ammar257ammar

**Comment by ljgarcia** [comment]
Thanks @egonw !
@AlasdairGray looks fine to me, what do you say? Could you please guide Egon on how to add this to the website? Maybe @petrospaps can help?

**Comment by AlasdairGray** [comment]
Draft version available on https://github.com/BioSchemas/bioschemas.github.io/tree/chemistry-use-case

@egonw I've extended what you put above please let us know if you are happy with this

**Comment by egonw** [comment]
Yes, looks good. I made a small typo fix.

**Comment by AlasdairGray** [comment]
Fixed in https://github.com/BioSchemas/bioschemas.github.io/pull/377
