### ISSUE TITLE
Refine styling of tutorial layout

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#487]
Develop a visually appealing style for the Bioschemas tutorials.

_Originally posted by @AlasdairGray in https://github.com/BioSchemas/specifications/issues/479#issuecomment-780410287_

**Comment by ljgarcia** [comment]
I suggest looking for some help from the community. Visual appealing style using markdown and YAML are kind of outside my area of expertise.

**Comment by ljgarcia** [comment]
@AlasdairGray do you have an example in mind?

**Comment by ljgarcia** [comment]
What about:
![image](https://user-images.githubusercontent.com/5427252/117200182-73ffdd00-adeb-11eb-8ea8-b34745e7a8da.png)

Then when scrolling down looks like:
![image](https://user-images.githubusercontent.com/5427252/117200232-8aa63400-adeb-11eb-99b4-b8003e36c144.png)

And on mouse over looks like:
![image](https://user-images.githubusercontent.com/5427252/117200357-b88b7880-adeb-11eb-85a4-900a4c40ac07.png)

And then on mouse out it hides

**Comment by ljgarcia** [comment]
The menu is a div:
```
<div id="toc">
  Contents
  <div id="full">
  <ul>
  <li><a href="#1-prepare-your-working-environment">1. Prepare your working environment</a></li>
  <li><a href="#">2. Create a new profile crosswalk</a></li>
  <li><a href="#">2.1. The Specification Info tab</a></li>
  <li><a href="#">2.2. The Schema.org mapping tab</a></li>
  <li><a href="#">2.3. Publish the Bioschemas fields to the Web</a></li>
  <li><a href="#">3. Get the code for the new draft profile</a></li>
  <li><a href="#">4. Update the website</a></li>
  <li><a href="#">5. Get an overview on your local copy</a></li>
  <li><a href="#">6. Update examples</a></li>
  <li><a href="#">7. Create a Pull Request</a></li>
  </ul>
  </div>
</div>
```

And the hide/show is done with CSS
```
#toc {
    position: fixed;
    right: 1em;
    top: 5em;
    background-color:#FFF;
    box-shadow: 0 0 1em #777777;
    padding: 0.5em;
  }
  
  #toc #full { display: none; } /* Hide the full TOC by default */
  
  #toc:hover #full{
    display: block; /* Show it on hover */
  }
```

**Comment by AlasdairGray** [comment]
During the [community call](https://docs.google.com/document/d/1kd5F97ogdiPNhLTnkei-RVR8TC8Ohpc5QSPX3KsfDrk/edit#heading=h.44fw1tgcq935) on 24 April it was agreed that the styling was generally fine. The key thing that came out was the need for ToC and numbered sections.

@ljgarcia thanks for the suggestion above.

@bedroesb suggested the [jekyll-table-of-contents](https://github.com/ghiculescu/jekyll-table-of-contents) plugin. Do we know if this is compatible with GitHub pages (they don't allow many jekyll plugins)? Can it be used with our site? Bert said that he could help out.

**Comment by bedroesb** [comment]
@AlasdairGray you can just add the javascript to your assets without the use of a gem/plugin. From my experience Github pages works with most gems as long as you declare them in your Gemfile (not needed here). I could make an example if you want. This [TOC](https://rdmkit.elixir-europe.org/marine_metagenomics.html) is generated with it. The levels of headers it picks up is a setting.

**Comment by bedroesb** [comment]
First try can be found at https://github.com/BioSchemas/bioschemas.github.io/pull/411

**Comment by AlasdairGray** [comment]
During the [community call on 24 May](https://docs.google.com/document/d/1kd5F97ogdiPNhLTnkei-RVR8TC8Ohpc5QSPX3KsfDrk/edit#heading=h.5resupdh3177) it was decided that the main issues were 
- [x] Numbering/labelling of sections
- [x] More descriptive titles in drop down menu
- [ ] Issues when viewed on mobile device

**Comment by ljgarcia** [comment]
All items in this comment moved to https://github.com/BioSchemas/specifications/issues/531

Some issues with links which do not look like a link (no hand mouse icon and on click does not navigate). They might be somehow related to the mobile device navigation in the sense that there seems to be some shifting on the pages. If I try to select a text with the mouse, I will end up selecting text from a couple of lines below.

- [ ] https://bioschemas.org/tutorials/markup_examples: Link to previous tutorial What and why schema.org
- [ ] https://bioschemas.org/tutorials/howto/howto_create_new_profile: GitHub issue tracker under section "Before you start", template GSheet under "Starting a new profile"
- [ ] http://127.0.0.1:4000/tutorials/howto/howto_new_profile_version: link to previous tutorial ""how to create a new draft profile", scholarly article under section "Prepare your working environment"
- [ ] http://127.0.0.1:4000/tutorials/howto/howto_add_markup#1-a-pre-markup-brainstorming-activity: "how to select the right profile for your resource" on the first warning box. If I mouse-hover at the beginning of the sentence, there is no hand-mouse icon, if I move to the end of the href, then I get the hand-mouse icon and can click with no problem
- [ ] http://127.0.0.1:4000/tutorials/howto/howto_add_github: "Jekyll templating engine" and "TrainingMaterial profile" under section GitHub pages. GitHub pages documentation under section Rendering your metadata. 
- [ ] http://127.0.0.1:4000/tutorials/howto/howto_check_deploy: link to previous tutorial.

**Comment by AlasdairGray** [comment]
We should look and see if the Jekyll [management of collections ](https://jekyllrb.com/docs/collections/#manually-ordering-documents) will help with the management of ordering tutorials.

**Comment by AlasdairGray** [comment]
@bedroesb I have revised the tutorial layout as per our [discussions](https://docs.google.com/document/d/1V6IlnUFBkPOOa8J22NuIKC7TwhHT5ghbuIpkiebWcKA/edit#) this morning. You can find the work on the [tutorial-restyling](https://github.com/BioSchemas/bioschemas.github.io/tree/tutorial-restyling) branch. It is now ready for you to prettify :)

**Comment by ljgarcia** [comment]
- [x] @AlasdairGray : To generate column container for tutorial
- [x] @bedroesb : To prettify
- [X] @ljgarcia : Review use of audience in existing tutorials and introduce terms agreed in this meeting -- see PR https://github.com/BioSchemas/bioschemas.github.io/pull/441

**Comment by AlasdairGray** [comment]
@bedroesb Just chatted with Leyla about this. She is going to review her comments from 30 June and see if your changes have resolved these.

**Comment by ljgarcia** [comment]
issues on mobile devices remain but those can go into the restyling of the full website. 
New issue about it: https://github.com/BioSchemas/specifications/issues/532

**Comment by ljgarcia** [comment]
> 
> 
> During the [community call on 24 May](https://docs.google.com/document/d/1kd5F97ogdiPNhLTnkei-RVR8TC8Ohpc5QSPX3KsfDrk/edit#heading=h.5resupdh3177) it was decided that the main issues were
> 
>     * [x]  Numbering/labelling of sections
> 
>     * [x]  More descriptive titles in drop down menu
> 
>     * [ ]  Issues when viewed on mobile device

@bedroesb tutorial-restyling branch looks good, please go ahead and create the PR and assign me as reviewer, thanks.

**Comment by ljgarcia** [comment]
Resolved with https://github.com/BioSchemas/bioschemas.github.io/pull/449
