### ISSUE TITLE
Create tutorial on GSheet

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#489]
- [x] How to create a new GSheet for a total new profile --> I would delay this one as we want to update the whole process and this tutorial might not be easy/short
- [x] How to update an existing GSheet for an existing profile --> @AlasdairGray can you or maybe one of your students start this one?

**Comment by AlasdairGray** [comment]
Tutorials have been published
- [How to create a new Bioschemas profile](https://bioschemas.org/tutorials/howto/howto_create_new_profile) completed in [PR413](https://github.com/BioSchemas/bioschemas.github.io/pull/413)
- [How to update a profile](https://bioschemas.org/tutorials/howto/howto_new_profile_version) completed in [PR395](https://github.com/BioSchemas/bioschemas.github.io/pull/395)
