### ISSUE TITLE
Create tutorial on how to create a new draft for an existing profile

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#490]
We want to change the whole process but we still need to support the current way for some months so we need a step by step tutorial for this.
@ljgarcia will start the tutorial and @albangaignard will go through it once ready

**Comment by AlasdairGray** [comment]
This has been completed in [PR395](https://github.com/BioSchemas/bioschemas.github.io/pull/395)
Page is live https://bioschemas.org/tutorials/howto/howto_new_profile_version
