### ISSUE TITLE
Missing cardinality value for properties in Gene profile

### ISSUE THREAD

**Issue by GloC99** [BioSchemas/specifications#492]
In the profile _Gene Version: 0.7-RELEASE_:

- associatedDisease

- taxonomicRange

has no cardinality value.

**Comment by ljgarcia** [comment]
@AlasdairGray Does this change require to move to DRAFT 8 and then to RELEASE 8? Or can I do it directly on RELEASE 7? Or can I go directly to RELEASE 8?

**Comment by ljgarcia** [comment]
@AlasdairGray Please see https://github.com/BioSchemas/bioschemas.github.io/pull/388

**Comment by AlasdairGray** [comment]
@ljgarcia I've been on leave for a bit over a week and am at the E-UK hackathon the last few days of this week.

As this is not just a minor typo I think that this really should go through the proper release process. Have you discussed with anyone else about just doing this as a direct change?

**Comment by ljgarcia** [comment]
PR can be moved to draft, and email sent to the community asking for
comments. I would avoid going back to a draft version, then asking the
community, then moving to release as any page adopting already release 7
will also work for release 8. But I will go with what you decide.

**Comment by ljgarcia** [comment]
@micheldumontier @andyjenkinson 
Hi there, @AlasdairGray realized associatedDisease and taxonomicRange were missing cardinality for the gene profile. I used MANY, following to what is done in the protein profile.
@AlasdairGray considers this a major change while I do not (MANY is the default in any case, we follow what was done for protein). Any thoughts?

**Comment by alaninmcr** [comment]
To be pedantic: it was Yazhuo Cao, a student of Carole's, who realized the problem during her automated checking of Bioschemas profiles.

I agree that many diseases may be associated with a gene. taxonomicRange should also be many as the same gene may have arisen in different taxonomies, or have remained in disparate taxonomic branches.

**Comment by micheldumontier** [comment]
it is definitely the case that dysfunction in one gene (through a variety of mutations, insertions, deletions) or its regulation can lead to or be involved in a number of abnormal clinical phenotypes and disorders.

**Comment by AlasdairGray** [comment]
> (MANY is the default in any case, we follow what was done for protein)

I do not believe that we have a stated default, which is why we need to make a statement here. In fact, in most constraint languages the default position would be ONE.

I agree that for Gene, the correct cardinality is MANY.

**Comment by ljgarcia** [comment]
It looks like everybody in this thread agrees MANY is the way to go.
@AlasdairGray do you want to go for a DRAFT and then for a RELEASE or can we go directly for the RELEASE as proposed in the PR?

**Comment by AlasdairGray** [comment]
Community voted in favour of moving to 1.0-RELEASE

Vote results:
- 16 1.0-RELEASE
- 14 0.8-RELEASE
- 6 0.8-DRAFT
