### ISSUE TITLE
Cardinality contradiction on keywords property on Dataset 0.4-DRAFT

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#501]
The cardinality for `keywords` on [Dataset 0.4-DRAFT](https://bioschemas.org/profiles/Dataset/0.4-DRAFT/) is stated as being 'ONE' but the example is an array of `DefinedTerm`, i.e. 'MANY'.

We should change the cardinality to 'MANY' since the preferred approach is to use `DefinedTerm`s.

This will mean moving to 0.5-DRAFT.

**Comment by egonw** [comment]
@ljgarcia, please add the link to the guidance document with steps I need to perform.

**Comment by ljgarcia** [comment]
@egonw this is the link to the tutorial to update an existing profile: https://bioschemas.org/tutorials/howto/howto_new_profile_version

**Comment by egonw** [comment]
> @egonw this is the link to the tutorial to update an existing profile: https://bioschemas.org/tutorials/howto/howto_new_profile_version

Reading...

**Comment by egonw** [comment]
Spreadsheet for `0.5-DRAFT`: https://docs.google.com/spreadsheets/d/1Nyaebro74ZPQpIYd0oTwfq-RnXtO1dE2KvbSKLDKE1E/edit#gid=1483018794
