### ISSUE TITLE
Tidy up CSS

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#503]
While working on the [tutorials table of contents](https://github.com/BioSchemas/bioschemas.github.io/pull/411#issuecomment-852899687), @bedroesb wrote: 
> @AlasdairGray I did a fix following this tutorial but it still feels a bit hacky, but it works though. I also took the freedom to change all the shadows to the same type used in the frontpage for consistency. I noticed that in mobile mode many things change including the fact that the title disappears and the navigation titles change. For me it is confusing that in the normal website you don't have the word tutorial in the navigation, but you do have it in mobile mode. I could also not follow well the separation between the stylesheet.css and the other scss files. I think if you move everything over to the scss and make more use of the bootstrap classes, the code could be a lot simplified :) Just some thoughts! Sorry if I am commenting things that are already discussed in the past!

The CSS has evolved over the life time of the website and definitely could do with a tidy up. Not aware of anyone else having brought this up.

@bedroesb feel free to make a PR to do this.

**Comment by bedroesb** [comment]
As promised, done in https://github.com/BioSchemas/bioschemas.github.io/pull/446 :)
