### ISSUE TITLE
Live deploys per node tab

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#505]
@AlasdairGray there is something odd with the live deploys per node.
![image](https://user-images.githubusercontent.com/5427252/120821018-5ee6ad00-c555-11eb-90f3-5139389a1148.png)

**Comment by AlasdairGray** [comment]
Yes, it is because there are tables nested within the table. I don't know how to get rid of this effect.

**Comment by bedroesb** [comment]
This is fixed with https://github.com/BioSchemas/bioschemas.github.io/pull/446
