### ISSUE TITLE
Update Markup Example Tutorial

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#507]
The existing [Markup Example Tutorial](https://bioschemas.org/tutorials/markup_examples) is based on a cupcake recipe. This is not very relevant for the life sciences.

@alaninmcr in conjunction with Gloria, as part of addressing #488, has suggested updating the example to marking up a dataset. Part of the discussion in the tutorial would include the discussion of there being over 120 properties for a Dataset and thus the need for Bioschemas profiles.

**Comment by AlasdairGray** [comment]
Discussion from [Community Call on 24 May](https://docs.google.com/document/d/1kd5F97ogdiPNhLTnkei-RVR8TC8Ohpc5QSPX3KsfDrk/edit#heading=h.5resupdh3177):
- Alan looked at live deploys, numerous incorrect ([analysis document](https://docs.google.com/document/d/1_UpLfoE38bu9NxHJ57twZcvUbEX7cnpZ6EnpEMVwc-I/edit?usp=sharing))
- Valid / wrong, no distinction on website
- List is manual - we don’t parse all of those
- Ivan went through to check for sitemaps, took a week (no scraping). We should also remove entries that don’t specify the release used. Or flag it as old?
- Need an automated solution. Many sites don’t specify version
- We should flag resources that don’t state necessary information/compliance
- A. sample pages b. Tell people to assert profile used (AI: ensure that is in tutorials) ‘conformsTo’. Be sure to add it in tutorial, not only to examples
- Validator to test the highest lvl profile complied with if no profile is specified.
- AI: Alasdair: What is ‘The’ validator (is it the one in WP5 D5.3 SIS Bioschemas?)
- AI: (Chris Childs and Alan?) try Gloria’s validator and other community developed ones. encourage people to write a validator.
- Start with validating dataset then data catalog. Report results in a master sheet or similar. Then proceed with other profiles beyond Dataset and Data Catalog.

**Comment by AlasdairGray** [comment]
I would suggest that we separate out two things here:
1. Updating the existing tutorial
2. Clarify what it means to be listed on the live deploy page

For (1) we just need **one** example that is the focus of the tutorial; the analysis shows that there are plenty of candidates.

For (2) I suggest that we create a separate issue and discussion. This could be part of the validation meeting.

**Comment by ljgarcia** [comment]
I do not have enough information to update this tutorial (nor the time right now). Let's discuss it on the next tutorial styling and layout meeting or community meeting.

**Comment by AlasdairGray** [comment]
Tutorial has been updated from Cupcake to an Event with a Biological focus.
