### ISSUE TITLE
 Allow external people to email groups

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#51]
All the groups are private at the moment, so people outside can't subscribe to them and can't post new messages.  Each team lead could manage subscriptions but it would be ideally external people could post to the group. @martin-nc  what do you think? is this something you could change?

**Comment by martin-nc** [comment]
Yes, external people can email the groups now and they can apply to join. That's a conservative choice - we could just let them join. There are also forum pages on Google groups for each Bioschemas group e.g. [Events forum](https://groups.google.com/a/bioschemas.org/forum/#!forum/events).

At the moment a group member gets an email every time someone posts to the group, but we could switch that to digest mode. Also we could turn on moderation if we wanted. I've left everything unmoderated. 

It's perhaps worth mentioning that people need to be signed in to Google to see the 'Join the group' button.

**Comment by rajido** [comment]
Thanks @martin-nc . To me this is done so I am closing this issue. I have added the link to the google apps forum (mailing list) in the [event group page](https://github.com/BioSchemas/bioschemas/wiki/Event-Group).
