### ISSUE TITLE
Recent News Feed

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#513]
The idea is to have a recent news feed on the front of the website which can highlight:
- New versions of specifications
- New live deployments
- etc

As Jekyll is a blogging site it should be possible to do this with the blogging feature.

**Comment by AlasdairGray** [comment]
Starting testing out ideas on branch [news](https://github.com/BioSchemas/bioschemas.github.io/tree/news).

**Comment by AlasdairGray** [comment]
I've made good progress of setting up and configuring the blog feature, see screenshots below.

Issues that need resolving
- [x] Where should the news page be included in the navigation menus
- [x] Fix styling of news cards on right side of news item display (Bert?)
- [ ] Add tag cloud to right side of news index page (optional)
- [x] Make tag cloud for top of tag index page (or some other improvement to their display)
- [x] `Back to top` links on tag index page; only the last one works (Bert?)

@bedroesb are you able to help with the CSS issues here?

@albangaignard thoughts on progress? Can we put this on the site now? Are you able to take over finalising this?

Home page: cards showing 3 most recent news items
![Screen Shot 2021-07-01 at 10 22 19](https://user-images.githubusercontent.com/1141265/124102402-3ec4e380-da58-11eb-8640-c377f501b3ef.png)

News item display page: I don't know why the cards don't show the same way as on the home page
![Screen Shot 2021-07-01 at 10 23 05](https://user-images.githubusercontent.com/1141265/124102605-6caa2800-da58-11eb-8e48-c87aefde4a4b.png)

News index page:
![Screen Shot 2021-07-01 at 10 22 44](https://user-images.githubusercontent.com/1141265/124102756-8cd9e700-da58-11eb-8880-ad99533f1ee3.png)

Tag index page:
![Screen Shot 2021-07-01 at 10 22 57](https://user-images.githubusercontent.com/1141265/124102888-aa0eb580-da58-11eb-88ba-7175d6d0962c.png)

**Comment by AlasdairGray** [comment]
BTW, I based the development around the general [jekyll guidance on posts](https://jekyllrb.com/docs/posts/).

**Comment by bedroesb** [comment]
@AlasdairGray what do you think of linking towards the newspage with a small sentence:

![Screenshot from 2021-07-02 14-07-16](https://user-images.githubusercontent.com/44875756/124276455-1c0ff900-db44-11eb-9440-f90dd1f52ec8.png)

This way the news heading looks nicely the same as the others (green). 

Concerning your points: the news cards make use of the same style as the events, where in general I don't see the style problem? the other one `Back to top links on tag index page; only the last one works (Bert?)` I can't see to replicate this problem?

**Comment by AlasdairGray** [comment]
> Concerning your points: the news cards make use of the same style as the events, where in general I don't see the style problem? the other one `Back to top links on tag index page; only the last one works (Bert?)` I can't see to replicate this problem?

Great that these were only an issue for my local deployment. Now that I've upgraded my OS I don't seem to be having the issue either.

**Comment by bedroesb** [comment]
I made an update for the back to top button here: https://github.com/BioSchemas/bioschemas.github.io/pull/445

**Comment by AlasdairGray** [comment]
@bedroesb I've just reviewed where we are with this (the news) branch. In my review I noticed that the card formatting was not coming through to the display of a news item. I have now fixed that in commit e4160768cbe9e4ec84babe23b501a30b580d97bb, and have also added recent news cards to the news by tags page (3c71d61f02cf4c15ab914ce19e27a88b948ca1bf).

What would be nice is if we can improve the display of the tags on the news page, currently it looks like this
![Screenshot 2021-08-24 at 11 41 02](https://user-images.githubusercontent.com/1141265/130602978-0f0068f5-e695-4f93-8727-ac12338cc907.png)

It would be nice if we could have something more like the following taken from https://codinfox.github.io/dev/2015/03/06/use-tags-and-categories-in-your-jekyll-based-github-pages/
![Screenshot 2021-08-24 at 11 41 55](https://user-images.githubusercontent.com/1141265/130603110-dd5eb7f1-6bad-49f1-98a5-b4f60fc58f0e.png)

**Comment by AlasdairGray** [comment]
We may also want to think about removing the limit on the number of news articles that are shown in the news-tags page. I think this could be done with an includes with parameter option.

**Comment by AlasdairGray** [comment]
In discussion with @ljgarcia and @bedroesb we've decided to put News under the Community menu.

**Comment by AlasdairGray** [comment]
The final two items on this issue are more easily done with the move to Bootstrap 5. We will make a PR for the current state and then prettify the remaining bits.

**Comment by bedroesb** [comment]
@AlasdairGray do you want those tag icons in your tags? I see now I forgot to add them. Besides that, do we still have to do something from this issue?

**Comment by bedroesb** [comment]
I amde a little preview here https://github.com/BioSchemas/bioschemas.github.io/pull/462
