### ISSUE TITLE
ELIXIR-PT example training URL no longer resolves

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#525]
The example page for training markup on the live deploys page no longer works
https://elixir-portugal.org/event/embo-practical-course-tree-building-advanced-concepts-and-practice-phylogenetic-analysis

I've contacted the help address to see if the page has moved. Otherwise we'll need to remove it.

**Comment by AlasdairGray** [comment]
@03c this is a resource that I believe Niall added because it was used by TeSS. Do you have any insight?

**Comment by 03c** [comment]
Just had a quick look and the page has moved: https://elixir-portugal.org/node/53 / https://biodata.pt/node/53

I think the above URLs point to the same site.

It looks to me like it should be removed. We aren't using Bioschemas in TeSS for the ELIXIR Portugal site.

**Comment by AlasdairGray** [comment]
I don't [see](https://validator.schema.org/#url=https%3A%2F%2Fbiodata.pt%2Fnode%2F53) any relevant markup on that page, so I guess we should remove it from the live deploy list.

**Comment by AlasdairGray** [comment]
Removing from live deploy list https://github.com/BioSchemas/bioschemas.github.io/pull/464
