### ISSUE TITLE
Agree properties for capturing input and output

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#526]
We now have two methods for capturing inputs and outputs. The `ComputationalWorkflow` working group have proposed that we add properties for `input` and `output` whereas `ComputationalTool` are suggesting to use `edam:input` and `edam:output`.

We really should have a single method and I believe that these are important enough properties that we propose them for inclusion in Schema.org.

_Originally posted by @AlasdairGray in https://github.com/BioSchemas/specifications/issues/523#issuecomment-880659763_

**Comment by albangaignard** [comment]
ComputationalTool 0.6-DRAFT and ComputationalWorkflow profiles are now aligned : they use the same `input` and `output` properties that point to a FormalParameter.
