### ISSUE TITLE
Mobile device display issues

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#527]
When viewing the site on a mobile device, the page heading is obscured by the navigation bar.
![Screenshot 2021-07-22 at 10 59 32](https://user-images.githubusercontent.com/1141265/126621857-cf0350aa-8063-4007-8450-ffa204dbf1ae.png)

This problem was first noted in https://github.com/BioSchemas/specifications/issues/487#issuecomment-866975681

**Comment by AlasdairGray** [comment]
The problem is that the container with the content is not off-set by the 50px that the navbar takes up. Adding `padding-top: 50px` fixes this but then has issues for the full size site adding an undesirable amount of space at the top. I don't know where to add this padding so that it only affects the mobile display.

**Comment by bedroesb** [comment]
fixed in https://github.com/BioSchemas/bioschemas.github.io/pull/450

**Comment by bedroesb** [comment]
this problem is fixed in https://github.com/BioSchemas/bioschemas.github.io/pull/446
