### ISSUE TITLE
Click/Link issue

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#531]
Some issues with links which do not look like a link (no hand mouse icon and on click does not navigate). They might be somehow related to the mobile device navigation in the sense that there seems to be some shifting on the pages. If I try to select a text with the mouse, I will end up selecting text from a couple of lines below.

- [ ] https://bioschemas.org/tutorials/markup_examples: Link to previous tutorial What and why schema.org
- [ ] https://bioschemas.org/tutorials/howto/howto_create_new_profile: GitHub issue tracker under section "Before you start", template GSheet under "Starting a new profile"
- [ ] http://127.0.0.1:4000/tutorials/howto/howto_new_profile_version: link to previous tutorial ""how to create a new draft profile", scholarly article under section "Prepare your working environment"
- [ ] http://127.0.0.1:4000/tutorials/howto/howto_add_markup#1-a-pre-markup-brainstorming-activity: "how to select the right profile for your resource" on the first warning box. If I mouse-hover at the beginning of the sentence, there is no hand-mouse icon, if I move to the end of the href, then I get the hand-mouse icon and can click with no problem
- [ ] http://127.0.0.1:4000/tutorials/howto/howto_add_github: "Jekyll templating engine" and "TrainingMaterial profile" under section GitHub pages. GitHub pages documentation under section Rendering your metadata. 
- [ ] http://127.0.0.1:4000/tutorials/howto/howto_check_deploy: link to previous tutorial.

**Comment by ljgarcia** [comment]
To understand better the issue, please see the following video.

https://user-images.githubusercontent.com/5427252/130485982-45aaf63f-1d5a-4273-81d7-f2e820d16097.mp4

**Comment by bedroesb** [comment]
Ooh I also noticed that!

It is because of the hacky way we now handle the titles, so if you follow a #sub_title url it does not hide the title behind the top nav bar, like it now happens in mobile mode.

The code causing the problem:

```
h2 {
    margin-top: -3em;
    padding-top: 3.6em;
    display: inline-block;
}
```
The padding of the subtitle basically covers the link.
@AlasdairGray I think it would be worth to consider not to use a sticky header anymore. This way we solve all these issues at once

**Comment by bedroesb** [comment]
fixed in https://github.com/BioSchemas/bioschemas.github.io/pull/450

**Comment by bedroesb** [comment]
This problem is fixed in https://github.com/BioSchemas/bioschemas.github.io/pull/446
