### ISSUE TITLE
Issues on mobile devices

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#532]
There are some issued when browsing on mobile devices. 

- [ ] Title gets cut

![image](https://user-images.githubusercontent.com/5427252/130483199-2aa7a404-e6c4-4151-aa91-491c12f11b09.png)

@AlasdairGray Please add other issues on mobile devices that you are aware of, thanks.

**Comment by bedroesb** [comment]
@ljgarcia I think this issue replicates #527 ?

**Comment by bedroesb** [comment]
fixed in https://github.com/BioSchemas/bioschemas.github.io/pull/450

**Comment by ljgarcia** [comment]
Indeed, closing this issue as duplicated
