### ISSUE TITLE
Image overlaps TOC and metadata boxes

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#533]
See example on the page https://bioschemas.org/tutorials/markup_examples
![image](https://user-images.githubusercontent.com/5427252/130602297-2586267f-60cf-455d-be11-4f9770bb74eb.png)

**Comment by bedroesb** [comment]
This should be fixed in: https://github.com/BioSchemas/bioschemas.github.io/tree/tutorial-restyling. Can you check this?

**Comment by bedroesb** [comment]
@ljgarcia hmm I forgot to replace these pictures with the new code snippets. I will make a new PR to master this afternoon
