### ISSUE TITLE
creator profile has it can have MANY, and an example of that is welcome

### ISSUE THREAD

**Issue by egonw** [BioSchemas/specifications#535]
The profile info at https://bioschemas.org/profiles/Dataset/0.3-RELEASE-2019_06_14/:

![image](https://user-images.githubusercontent.com/26721/132390057-3831556f-514b-4394-af0b-4cc6bdabb6fb.png)

And the error at https://validator.schema.org/#url=https%3A%2F%2Fnanocommons.github.io%2Fdatasets%2F:

![image](https://user-images.githubusercontent.com/26721/132390162-8f6cd356-3cc5-42ce-bfc7-340fcf3beb4b.png)

The JSON-LD from https://nanocommons.github.io/datasets/ :

```json
  {
    "@context": "https://schema.org/",
    "@type": "Dataset",
    "http://purl.org/dc/terms/conformsTo": { "@type": "CreativeWork", "@id": "https://bioschemas.org/profiles/Dataset/0.4-DRAFT" },
    "identifier": "10.5281/zenodo.4986068",
    "name": "BAM reference data: XPS raw data of Al-coated titania nanoparticles (JRCNM62001a and JRCNM62002a)",
    "description": "Data linked to Radnik, J. Kersting, R., Hagenhoff, B., Bennet, F., Ciornii, D.; Nymark, P., Grafström R. and Hodoroaba, V.-D. Nanomaterials 2021, 11, 639. https://doi.org/10.3390/nano11030639.",
    "license": "https://creativecommons.org/licenses/by/4.0/legalcode",
    "url": "https://zenodo.org/record/4986068",
    "creator": [
      {
        "@type": "Organization",
        "name": "NanoSolveIT"
      },
      {
        "@type": "Organization",
        "name": "NANORIGO"
      },
    ],
    "datePublished": "2021-06-18"
  }
```

**Comment by egonw** [comment]
The problem was not that the list did not get accepted, but that the trailing comma in the list; I changed the topic of the issue accordingly, which is now a feature request for a list example in the documentation.

**Comment by egonw** [comment]
(which I hope to add myself soon... if I can find the time)

**Comment by AlasdairGray** [comment]
@egonw did you complete this when you were preparing the 0.5-DRAFT?
