### ISSUE TITLE
Add PathVisio to live deploys

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#545]
From https://github.com/BioSchemas/bioschemas.github.io/pull/468#issuecomment-951067278

> And proposed annotation for PathVisio: [PathVisio/pathvisio.github.io#9](https://github.com/PathVisio/pathvisio.github.io/pull/9)

We don't have an entry in our live deploys page for PathVisio. @egonw could you add one?

**Comment by egonw** [comment]
@AlasdairGray, the PR I created was merged this morning. I'll now make a PR for the Live Deploy

**Comment by egonw** [comment]
PR: https://github.com/BioSchemas/bioschemas.github.io/pull/508

**Comment by gtsueng** [comment]
Addressed by https://github.com/BioSchemas/bioschemas.github.io/pull/508
