### ISSUE TITLE
Tutorials need to cover string sequences containing special characters

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#548]
Strings containing special characters like `"` and `\` need to be dealt with by escaping in JSON-LD, e.g. `\"` and `\\`. While this is mentioned in the [`smiles`](https://schema.org/smiles) property thanks to https://github.com/BioSchemas/specifications/issues/241, it is not being picked up by developers, see https://github.com/MassBank/MassBank-web/issues/316#issuecomment-958766083. Also this issue is not exclusively found in the `smiles` property but appears in description fields and other text fields.

The suggestion I'm making is that we should cover this in our tutorials and training material.

**Comment by ljgarcia** [comment]
@AlasdairGray do you propose a new tutorial covering this or adding a reminder to escape special characters in those tutorials dealing with the spreadsheet? I imagine special characters must be escaped there so GO-Web gets them right in the YAML. But then it would be YAML escaping and not JSON-LD escaping, right?

**Comment by AlasdairGray** [comment]
@ljgarcia this is about markup deployed on sites, not about developing Bioschemas profiles and types.

We need to add a section to the [How to mark up your own resource with Bioschemas](https://bioschemas.org/tutorials/howto/howto_add_markup) tutorial about dealing with special characters when using JSON-LD as the markup language.

We may also want to add a sentence or two to the [How to select the right profile for your resource](https://bioschemas.org/tutorials/howto/howto_right_profile) tutorial if we have a section on when you would choose the MolecularEntity profile since SMILES strings contain these special characters.

**Comment by ljgarcia** [comment]
I personally think that the particularities of JSON-LD are outside the scope but I have added a couple of lines in this regard in PR https://github.com/BioSchemas/bioschemas.github.io/pull/447

If someone has a good reference for special characters in JSON-LD, please let me know
