### ISSUE TITLE
Read seed profiles into DDE

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#550]

**Comment by AlasdairGray** [comment]
DDE has been populated with initial versions of profiles
https://discovery.biothings.io/view/bioschemas/

**Comment by AlasdairGray** [comment]
@gtsueng I don't see all the profiles on the DDE page, e.g. [TaxonName](https://bioschemas.org/profiles/TaxonName/) is missing. We have 21 out of 36 profiles, although 3 of the 36 profiles are [deprecated](https://bioschemas.org/profiles#nav-deprecated).

**Comment by AlasdairGray** [comment]
@gtsueng Can DDE capture the date that a profile is saved out to GitHub? I don't see this in the current JSON files.

**Comment by gtsueng** [comment]
@AlasdairGray this is not a function that is currently supported by the DDE. The DDE should not have a problem ingesting profiles with "schema:dateModified" in the class definition, but these will have to be set manually at this point in time.
