### ISSUE TITLE
What to use in place of schema:additionalType?

### ISSUE THREAD

**Issue by marco-brandizi** [BioSchemas/specifications#560]
This is a follow-up of #538. Since it seems `schema:additionalType` is deprecated within bioschemas, I'd like to have a guideline/recommendation on what to use when I want to link to ontology term URIs in a generic way, and I'd like to know what the bioschemas community would recommend to avoid the problems that `additionalType` has (I've notified schema.org of that with this new ticket: schemaorg/schemaorg#2986).

My first option would be `dc:type`. Or, I would choose to use dc:type until they possibly change `additionalType`.

**Comment by AlasdairGray** [comment]
@marco-brandizi there isn't a generic answer to your issue, it depends on the specific use case of the markup that you are developing.

Looking at the issues you have raised, it seems that you are trying to markup a biological sample. In that case, I'd recommend the use the [BioSample](https://bioschemas.org/BioSample) type that the Bioschemas community have been developing and connect that to the ontology term.

The example that you give would then look something like the following, assuming that the sample is a seed and the property is the size of the seed:
```turtle
ex:sample987 a bs:BioSample;
    name "Seed"
    additionalProperty ex:prop1234.

ex:prop1234 rdf:type schema:PropertyValue;
  schema:propertyID <https://cropontology.org/rdf/CO_335:0000799>;
  schema:value 0.98 .
```

**Comment by marco-brandizi** [comment]
@AlasdairGray, yes, I'm already linking BioSample to PropertyValue, however, using propertyID with ontology terms doesn't seem good, cause I might have more than one annotating term for the same pair of name/value string pair, and the PropertyValue ID is a different concept wrt something that enriches it with ontological qualifiers.

Thanks anyway for the clarification.
