### ISSUE TITLE
Add Damalos as Scholarly Article live deploy

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#561]
Quote from how to add markup tutorial:
> For websites without a production pipeline behind, those where you manually edit the HTML yourself, you will have to add the markup by hand. For instance, if you organize a half-day workshop with less than 10 accepted papers, you could add the corresponding markup by hand. This is the case for the Research Objects Management for Linked Open Science Workshop which includes bibliographic markup for the submissions on 2020. The workshop web page is based on GitHub pages and the markup for the publications was manually added at the end of the corresponding MarkDown document.

We should add these pages to our live deploy list.

**Comment by ljgarcia** [comment]
Solved in https://github.com/BioSchemas/bioschemas.github.io/pull/492
