### ISSUE TITLE
Add applicationSubCategory and featureList properties to ComputationalWorkflow

### ISSUE THREAD

**Issue by stuzart** [BioSchemas/specifications#564]
To allow the ability to describe a workflow using EDAM topics (applicationSubCategory) and operations (featureList). This mirrors the [ComputationalTool](https://bioschemas.org/profiles/ComputationalTool/0.5-DRAFT) profile, and would be good to keep them aligned.

Unlike ComputationalTool, I don't think we'd want to restrict these properties to EDAM for the Controlled Vocab, as there will be workflows that aren't Bioinformatics specific, so just keep it as URL as the Expected Type. This is perhaps something that needs discussing with ComputationalTool in the future.

The properties should be recommended

**Comment by alaninmcr** [comment]
Done in draft 1.1
