### ISSUE TITLE
Add schema:sameAs property for all profiles

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#567]
Consumers of markup need to be able to reconcile the identity of the individuals contained in the markup. This will enable them to interconnect the data harvested from multiple sites, and is essential for constructing knowledge graphs such as the OpenAIRE Research Graph.

The easiest way to achieve this is for the data providers to include some `schema:sameAs` links to leading databases in their area, e.g. for the Protein profile we could recommend that `schema:sameAs` links are provided to UniProt.

I am proposing that we make `schema:sameAs` a Minimal property for all profiles.

**Comment by stain** [comment]
What is the meaning of "minimal property" - do you mean an optional? Obviously we can't require all entities to always have a second identifier.

**Comment by alaninmcr** [comment]
Doesn't this mean that all objects with profiles would need to be the sameAs something else? I do not understand how this could work, How would novel objects be annotated given they are not the sameAs something?

**Comment by alaninmcr** [comment]
@stain A minimal property is one **that is required**. The suggestion would mean that every object that conforms to a bioschemas profile must also be known to some other system.

**Comment by AlasdairGray** [comment]
This was discussed at the [Bioschemas Community call on 28 February](https://docs.google.com/document/d/1kd5F97ogdiPNhLTnkei-RVR8TC8Ohpc5QSPX3KsfDrk/edit#heading=h.jhtz1vyq1xm2).

Several examples were given, e.g. Workflow, ComputationalTool, nanomaterials, where it would not make sense for `schema:sameAs` to be 'Minimal', as there would be no candidate to map to.

It was agreed that it would be desirable to capture such cross-references where they exist.

Should `schema:sameAs` be made 'Recommended' for all profiles or do we need to do it on a profile by profile basis?

**Comment by alaninmcr** [comment]
Recommended makes more sense - perhaps with a statement that it should be specified when/if there is an equivalent object in the wider world.

**Comment by ljgarcia** [comment]
Not related to the ```sameAs``` addition but to the GitHub actions that generated the corresponding PRs from 687 to 711. 
Summary of requested changes for the GitHub actions @sahar-frikha @gtsueng

- [] Fix hierarchy, right now it appears empty
- [] Fix link to examples, it should always point to the jsonld subfolder for the corresponding specification
- [] Remove redirection from previous version
