### ISSUE TITLE
Script to convert JSON-Schema to something Jekyll can render

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#568]
Conversion script has been created. Latest update discussed in https://github.com/BioSchemas/bioschemas.github.io/pull/516#issuecomment-1041935391

> I believe that is the functionality of the conversion script in place. It reads in a DDE generated `.json` file from the [Specifications repo](https://github.com/BioSchemas/Specifications), replaces the json-ld and json-schema keys (that jekyll can't process), and then writes the resulting `.json` file to the `_data/schemas` directory.
>
> What is left to do for the script:
> - Use input arguments to control which profile is converted and test with more than [ComputationalTool v1.0](https://github.com/BioSchemas/specifications/blob/master/ComputationalTool/jsonld/ComputationalTool_v1.0-RELEASE.json)
> - Move to the [DDE repo](https://github.com/BioSchemas/bioschemas-dde)
> - Set up GitHub actions chaining with the DDE conversion script
>
> The task for this repo is to decide how we display the new schemas. In this test branch you can try out the ComputationalTool. The test file renders to [localhost:4000/CompTool.html](http://localhost:4000/CompTool.html).

**Comment by AlasdairGray** [comment]
- Conversion script moved to [DDE repo](https://github.com/BioSchemas/bioschemas-dde) (located in `python` folder) and uses same configuration file for which profiles to convert
- Generated schemas are placed in a `schema` directory and then need to be hand copied across to website repo

_In the future we will look at automating these processes (#569) but first we want to ensure that the steps work._

**Comment by AlasdairGray** [comment]
Processing the JSON-Schema representation using Jekyll is going to be difficult and ugly. 

After discussions on https://github.com/BioSchemas/bioschemas.github.io/pull/516#issuecomment-1048695219 it has been decided to generate the YAML representation using the python script. Initial work for this has begun on branch https://github.com/BioSchemas/bioschemas-dde/tree/schema-to-yaml

**Comment by AlasdairGray** [comment]
The conversion script needs to:
- [ ] Extract profile metadata
  - [x] name
  - [x] description
  - [ ] changes
  - [x] group
  - [x] base type
  - [x] status (release|draft|deprecated)
  - [x] version
  - [x] previous version
  - [x] previous release
- [ ] Profile table from `$validation` section of JSON file
  - [ ] Property
    - [ ] Link to schema.org
    - [ ] Link to pending.schema.org
    - [ ] Link to bioschemas/dde
    - [ ] Link to external property
  - [ ] Expected type
    - [ ] oneOf
    - [ ] anyOf
    - [ ] Link to schema.org
    - [ ] Link to pending.schema.org
    - [ ] Link to bioschemas/dde
    - [ ] Link to external property
  - [ ] Description
    - [ ] Embedded hyperlinks
  - [ ] Cardinality
    - [ ] One
    - [ ] Many
  - [ ] Controlled vocabulary
  - [ ] Example
- [ ] Fix redirects within the Bioschemas website

Note that not all of the above may be possible with the DDE JSON, e.g. examples are not included in the JSON.

**Comment by sahar-frikha** [comment]
We, @albangaignard and I, had a testing session for the [Workflow](https://github.com/BioSchemas/specifications/blob/git-actions-test/.github/workflows/generateHTMLProfile.yml) and the [Python Script](https://github.com/BioSchemas/specifications/blob/git-actions-test/.github/workflows/conversion.py) written for the profile generation automation. We tested on the [TAXON/0.7-DRAFT](https://github.com/BioSchemas/specifications/blob/git-actions-test/Taxon/jsonld/Taxon_v0.7-DRAFT.json), and here are some of the first outcomes:

1. The profile **Spec/Metadata**:

- **Jekyll Side:** Issue with CSS styling in the rendered jekyll web page.  
- **Jekyll Side:** The profile I generate don’t appear in the /profiles page in the website.
- **DDE Side, Question for @AlasdairGray:** The header of each YAML was added manually.  Now when we generate the HTML profiles, we must find a way to inject automatically this content.
- **Jekyll Side Blocker:** The Examples Button doesn't exists.
- **Python Script:** What are the default values if we don't find the property in the JSON-LD (Example: Version field). When to skip and when to raise a/an warning/exception?

2. The profile's properties:

- **DDE Side:** The examples in the properties doesn't exists.
- **DDE Side:** The type field is always empty, as a result all properties are considered schemas classes. (Some should be in green, when it’s a Bioschemas property).
- **Jekyll Side:** Some properties descriptions are different such as for name (Jekyll can't fetch the schemas spec and Bioschemas spec correctly. how to fix that?).
- **Python Script:** Expected Types such as _Taxonname_ should be _TaxonName_, but didn't know how to do so.
- **Python Script:** vernacularName should be replaced by dwc:vernacularName instead. But what's the general case? @AlasdairGray, What's the formula?

PS: If you wanted compare your self, this is the [profile](https://bioschemas.org/profiles/Taxon/0.7-DRAFT) existing in the website and you can download the [auto generated profile](https://github.com/BioSchemas/specifications/blob/git-actions-test/Profiles/Taxon_v0/Bioschemas%20-%200.7%20Draft.html).

**Comment by AlasdairGray** [comment]
@sahar-frikha has now completed the work on this issue with the implementation of a GitHub action that takes the output of DDE and converts it into the format needed for rendering profiles on the bioschemas website.

The work is captured in the [github.com/Bioschemas/Specifications](https://github.com/BioSchemas/specifications/) repo and specifically in pull https://github.com/BioSchemas/specifications/pull/603
