### ISSUE TITLE
Profiles with current and former leaders does not show them as contributors

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#586]
https://bioschemas.org/profiles/TrainingMaterial/1.0-RELEASE#nav-contributors does not display the current leads as there is no element ```lead``` on the page but ```current-leads``` and ```former-leads```

**Comment by ljgarcia** [comment]
@bedroesb @albangaignard @ivanmicetic could you please have a look at it? I tried to find a solution but other than too many conditionals repeating the body for g.lead and g.current-leads did not find a way. And the page gets overcomplicated in that way. There should be (hopefully) a way in liquid to do something like ```leaders = g.lead or g.current-leads['person']``` and similar for members.

**Comment by AlasdairGray** [comment]
Fixed in https://github.com/BioSchemas/bioschemas.github.io/pull/564
