### ISSUE TITLE
Add Manchester Validator to list of available software

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#587]
Please add a description for the Manchester Validator to this [YAML](https://github.com/BioSchemas/bioschemas.github.io/blob/master/_data/software.yaml) file.

It will then appear on the [software page](https://bioschemas.org/developer/software).

**Comment by gtsueng** [comment]
Appears to have been addressed by https://github.com/BioSchemas/bioschemas.github.io/pull/692
