### ISSUE TITLE
Add FAIR-Checker to software page

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#588]
Please add a description for the FAIR-Checker to this [YAML](https://github.com/BioSchemas/bioschemas.github.io/blob/master/_data/software.yaml) file.

It will then appear on the [software page](https://bioschemas.org/developer/software).

**Comment by albangaignard** [comment]
Thanks, it's done in the following PR: https://github.com/BioSchemas/bioschemas.github.io/pull/570
