### ISSUE TITLE
Write down and make clear the benefits of BioSchemas

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#59]

**Comment by frenkxs** [comment]
The first draft is at: https://docs.google.com/document/d/105q2fBaTrW46-h9I9vdyElEMYUoHosch795rTo-5u10/edit

**Comment by gtsueng** [comment]
While the wording is not the same, much of the elements in the draft are currently covered in the description on the website. Given the date of this issue and the overlap in the points made in the draft document and website description, this issue will be closed unless @rajido or @frenkxs chime in on additional changes needed to the current description on the Bioschemas website by January 15th, 2022.
