### ISSUE TITLE
Request to extend Expected Types for property `measurementTechnique` with Type `DefinedTerm`

### ISSUE THREAD

**Issue by meier-rene** [BioSchemas/specifications#594]
Hi,
[we](https://www.nfdi4chem.de/) try to promote the usage of proper metadata on web resources of research data/scientific data. For the annotation of repositories/libraries we found the types `Dataset` and `DataCatalog` to be useful. In many domains of scientific data the communities have created controlled vocabulary and/or ontologies to precisely describe the nature of the data. To our understanding, the right type to refer to a controlled vocabulary term would be the `DefinedTerm` type. In the `Dataset` type and in the `PropertyValue` type there is a property `measurementTechnique` that has the expected types `Text` or `URL`. We ask to also allow the type `DefinedTerm` as a valid expected type for [measurementTechnique](https://schema.org/measurementTechnique) property. This would allow us to precisely refer to the used `measurementTechnique` if it is included in one of our ontologies.

An example: Let us consider I want to annotate a `Dataset` which includes a measurement with a liquid chromatography. At the moment I could do the following at the moment:
```json
{
  "@context": "https://schema.org/",
  "@type": "Dataset",
  "@id": "https://massbank.eu/MassBank/RecordDisplay?id=NA003756",
...
  "variableMeasured": {
    "@type": "PropertyValue",
    "measurementTechnique": [
      "http://purl.obolibrary.org/obo/CHMO_0001004",
      "liquid chromatography"
    ],
    "value": 10.422,
    "unitText": "minute"
  }
}
```

With `measurementTechnique` using the `DefinedTerm` type, it would be totally clear that we refer to an ontology and it could look like this:

```json
{
  "@context": "https://schema.org/",
  "@type": "Dataset",
  "@id": "https://massbank.eu/MassBank/RecordDisplay?id=NA003756",
...
  "variableMeasured": {
    "@type": "PropertyValue",
    "measurementTechnique": {
      "@type": "DefinedTerm",
      "@id": "http://purl.obolibrary.org/obo/CHMO_0001004",
      "inDefinedTermSet": {
        "@type":"DefinedTermSet",
        "@id":"http://purl.obolibrary.org/obo/chmo.owl",
        "name": "Chemical Methods Ontology"
      },
      "termCode": "CHMO:0001004",
      "name": "liquid chromatography"
    },
    "value": 10.422,
    "unitText": "minute"
  }
}
```

This would identify the `measurmentTechnique` without any ambiguity. 

Please could the `measurementTechnique` property be extended to include `DefinedTerm` as an expected type.

Kind Regards,
Rene

@sneumann, @uly55e5

**Comment by AlasdairGray** [comment]
@sneumann, @uly55e5 I have updated your text above to correct some aspects. In particular, the Schema.org community have no notion of profile, so these have all been changed to type.

However, I think your examples are incorrect. You have embedded the `measurementTechnique` property within the `PropertyValue` but I think it should be a property applied directly to the dataset according to the Schema.org specification. So something like
```json
{
  "@context": "https://schema.org/",
  "@type": "Dataset",
  "@id": "https://massbank.eu/MassBank/RecordDisplay?id=NA003756",
...
  "variableMeasured": {
    "@type": "PropertyValue",
    "value": 10.422,
    "unitText": "minute"
  },
  "measurementTechnique": {
      "@type": "DefinedTerm",
      "@id": "http://purl.obolibrary.org/obo/CHMO_0001004",
      "inDefinedTermSet": {
        "@type":"DefinedTermSet",
        "@id":"http://purl.obolibrary.org/obo/chmo.owl",
        "name": "Chemical Methods Ontology"
      },
      "termCode": "CHMO:0001004",
      "name": "liquid chromatography"
    }
}
```

Although I do see that your approach will allow the alignment between a variable and how it was measured.

**Comment by meier-rene** [comment]
Thank you for your comment. You have identified my motivation for putting the _measurmentTechnique_ inside of the `PropertyValue` correctly. This makes clear that this particular value was measured with this particular method. 

Of course its also possible to define the _measurementTechnique_ as property of the `Dataset`. The advantage of having the _measurementTechnique_ inside of the  _variableMeasured_ property is, you can define several different _variableMeasured_ with its respective _measurementTechnique_. I can imagine many cases, where a `Dataset` would have many different experimental determined values. I don't know how to define this properly in a different way than the one I chose. But both arrangements are legal to my understanding, because _variableMeasured_ can be of **Type** `PropertyValue`which has a property _measurmentTechnique_.

But this issue is not about the place where to define the _measurmentTechnique_, but about the **Type** used to define the _measurmentTechnique_. We ask for `DefinedTerm` as additional **Type** of _measurmentTechnique_, which is currently limited to `Text` and `URL`.

Legend:
_Italic_ properties of a type
`code style` a Type

**Comment by meier-rene** [comment]
Hi all,
I want to ask if there has been any progress on this? Is there anything we can do to get this flying?

I would like to summarize our proposal to make clear what we need/want:
We need to refer to ontology terms as value of the property [_measurementTechnique_](https://schema.org/measurementTechnique). The natural Type for this would be `DefinedTerm`. Thats why we ask to add `DefinedTerm` along with `Text` and `URL` as expected values for _measurementTechnique_.

Are there any objections?

Kind Regards, Rene

**Comment by gtsueng** [comment]
related issue at schema.org: https://github.com/schemaorg/schemaorg/issues/2734

**Comment by sneumann** [comment]
Another related issue is https://github.com/schemaorg/schemaorg/issues/3250

**Comment by gtsueng** [comment]
@meier-rene We have rekindled this discussion at schema.org (where it belongs). Please share your insight on the matter at https://github.com/schemaorg/schemaorg/issues/3250.

**Comment by ljgarcia** [comment]
Closing this issue as DefinedTerm in now in the range of measurementTechnique see:
* https://schema.org/docs/releases.html
* https://schema.org/DefinedTerm
