### ISSUE TITLE
Edit jsonld version 0.6-DRAFT for Dataset

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#624]
Hi @gtsueng I am going through the GitHub actions PRs and making any modifications needed.

For Dataset there are two modifications needed in the jsonld:
- [x] The right version should be 1.1-DRAFT. As the current release is 1.0-RELEASE, any new draft should refer to this release by incrementing the decimal. You created the version as 0.6-DRAFT so I had to updated it on the website to be 1.1-DRAFT. We need the right one at https://github.com/BioSchemas/specifications/blob/master/Dataset/jsonld
- [x] The inclusion of DefinedTerm for variableMeasure and MeasurementTechnique needs further discussion and using it will break the Data Structured Validation tool so I remove it. I think you added it only for variableMeasured. This should be reflected in the jsonld

Note: Changes have been made outside the DDE-GitHub actions so we can process the current PRs without triggering new PRs for minor adjustments. Hope this is not too much of a hassle on the DDE side.

Thanks

**Comment by ljgarcia** [comment]
@gtsueng I did not find the jsonld for 1.1-DRAFT version of TrainingMaterial. Please have a look. Thanks

**Comment by ljgarcia** [comment]
And, please also check Taxon 0.7-DRAFT profile, it already existed so I reverted the modifications but now I think those modifications were there to add some of the links to DDE. Please have a look. Thanks

**Comment by gtsueng** [comment]
Thanks for catching all that, @ljgarcia -- I've updated the jsonld files in the repo, and will do a manual refresh of the versions kept in the DDE

**Comment by gtsueng** [comment]
@ljgarcia The requested changes have been updated to the DDE. Once Taxon v0.8-DRAFT is updated on the website (ie- [pull request #721](https://github.com/BioSchemas/bioschemas.github.io/pull/721) is merged), we can close this issue.

**Comment by ljgarcia** [comment]
Taxon 0.8 is now live, closing this issue
