### ISSUE TITLE
Broken links in profile pages

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#626]
Hi @bedroesb could you please have a look to the following issues on profile pages?
- [ ] The group appears empty on the "links" tab
- [ ] Also on the "links" tab, there is a link to draft/release version it looks like ```You can read the draft version of this specification here``` or ```You can read the draft version of this specification here``` with a link on here that would go, for instance, to https://bioschemas.org/Dataset but that address does not exist. The one that exist is https://bioschemas.org/profiles/Dataset. If you want to distinguish latest draft from latest profile you would need to get the info from the profiles YAML that only relying on redirection.

Thanks.

**Comment by bedroesb** [comment]
@ljgarcia https://github.com/BioSchemas/bioschemas.github.io/pull/719 whoud fix these issues!

**Comment by ljgarcia** [comment]
Thanks @bedroesb closing this issue as the PR has been merged.
