### ISSUE TITLE
Event specification - existing properties

### ISSUE THREAD

**Issue by frenkxs** [BioSchemas/specifications#63]
The existing properties are already part of event specification on [schema.org/event](http://schema.org/event). Post any comments about the use of the properties within BioSchemas.org. 

You'll find the full event specification, including the existing event properties, new properties proposed by BioSchema, and the guidelines how to use these in the [Specification document](https://docs.google.com/document/d/12O8gsOuH2qHKpis6vTHxXExraNH5XZEnoilwNgWWgaQ/edit?usp=sharing). (You can post your comment directly in the document.)

**Comment by rajido** [comment]
@frenkxs is this soething we could close or we should mentioned in the website or include in the [open consultation](https://github.com/BioSchemas/bioschemas/wiki/BioSchemas-Open-consultation)?
