### ISSUE TITLE
Dataset Profile - hasPart property expects the type "trip"

### ISSUE THREAD

**Issue by NRayya** [BioSchemas/specifications#647]
The dataset profile has the property hasPart which accepts two types, one of them is "trip", if I am not mistaken the intended type is "thing" and not trip. 

We already have a use-case for  hasPart->thing and we appreciate adding it.

<img width="893" alt="image" src="https://github.com/BioSchemas/specifications/assets/82588017/30a27d4a-9998-4a52-9b1a-5bf43f020d5d">

**Comment by gtsueng** [comment]
Thanks for catching that --  will fix it ASAP
