### ISSUE TITLE
Fix description for sameAs

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#650]
@nsjuty could you please double check the description for the ```sameAs``` property in the profiles?

I noticed that ```sameAs``` in https://bioschemas.org/profiles/TrainingMaterial/1.1-DRAFT has a description "URL of additional sources for the dataset" but the official schema.org description is "URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website", see https://schema.org/sameAs

@gtsueng once @nsjuty has done the analysis, could you please let us know whether the update should go through DDE?

Thanks both

**Comment by gtsueng** [comment]
It's been fixed in the json file and DDE, the pull request to fix it on the website is here: https://github.com/BioSchemas/bioschemas.github.io/pull/779
