### ISSUE TITLE
PropertyValue for LabProtocol type properties

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/specifications#667]
The components of an ISA protocol can be mapped to `labEquipment`, `reagent` and `computationalTool` and for that we need PropertyValue as a possible range.

I have looked at `labEquipment` and `reagent`, and it makes sense to add `PropertyValue` as a possible range. They already take `DefinedTerm` as possible value and a `PropertyValue` is kind of similar but for cases where the `DefinedTerm` is not possible. 

I can do it for `computationalTool` as well but not sure how it would work. Do you have an example?

For `bioSample` the preferred way would be using a `bioschemas:BioSample` but as it also takes `DefinedTerm` I can also add `PropertyValue` if you need it. We also have `sample` that takes `Thing` as anything can be a sample of something. We can add `DefinedTerm` and `PropertyValue` to allow more specific information, I think it would make sense.

So, from the following list, please let me know where you need `PropertyValue`:
* labEquipment
* bioSample
* sample
* reagent
* computationalTool --for this one an example would be nice as I still do not fully understand how a `PropertyValue` would be used here

Thanks!

**Comment by HLWeil** [comment]
IMO, the big advantage of a PropertyValue in this context is, that you can use it as a structured Key-Value Pair. It basically contextualizes the value you insert. I would suggest to extend the range of those fields, which could be used to describe entities that should be used as necessary tools in the protocol:
- labEquipment
- reagent
- computationalTool 

 The contextualization could then be used to describe the purpose or task this entity fulfills.

As an example for a computational tool, you could use `STAR` as the tool for `aligning gene sequences`:

```json
        {
            "@type": "PropertyValue",
            "name": "Sequence Alignment Software Name",
            "value": "STAR",
            "propertyID": "http://purl.obolibrary.org/obo/NCIT_C175896"
        }
```

**Comment by ljgarcia** [comment]
Done, see https://github.com/BioSchemas/specifications/pull/668

**Comment by ljgarcia** [comment]
Closing as done
