### ISSUE TITLE
Create HTML Templates

### ISSUE THREAD

**Issue by njall** [BioSchemas/specifications#67]
It might be useful to have a blank template for each Bioschema class that people can downloaded, filled in, and copy and paste into their websites. It could be hosted and downloadable from the bioschemas.org website and would encourage people to get involved.

**Comment by rajido** [comment]
@robertopreste created a [template](https://docs.google.com/document/d/1VEXhXI7aWJz5djrRl7bKNKBWlElPWNqYexsUAxS0Npc) which is now linked form the [website](http://bioschemas.org/specifications/index.html). I mentioned @robertopreste it should also include the intro and the example section not just the table section. Something he said he will fix.

**Comment by robertopreste** [comment]
I just updated the [template](https://docs.google.com/document/d/1VEXhXI7aWJz5djrRl7bKNKBWlElPWNqYexsUAxS0Npc), so it should be easier now to build a new specification from that. Let me know if you need me to edit anything.

**Comment by rajido** [comment]
Thanks! I changed background for minimum fields from red to a dark green
