### ISSUE TITLE
Allow users to join all mailing list

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#68]
Maybe we could allow people to request membership for the "[all](https://groups.google.com/a/bioschemas.org/forum/#!forum/all)" mailing list the same way we do for "[community](https://groups.google.com/a/bioschemas.org/forum/#!forum/community)"? and update the [join us](http://bioschemas.org/howtojoin/index.html) page including the all mailing list.

**Comment by robertopreste** [comment]
Should be OK now. Please have a look and let me know if anything needs to be fixed.
