### ISSUE TITLE
Complete authors/contributors in the specification

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#7]
We could start adding names to the specifications of existing contributors

**Comment by rajido** [comment]
We can come up with authors in the group/team pages and the specification. I suggest to have authors in one place. ie group pages and once the aversion of the spec is published bring the author names.

**Comment by rajido** [comment]
We are trying to capture contributions in just one place. We have created an [spreadsheet](http://tinyurl.com/bioschemas-contributors) that help us to keep track of contributions and update our shared folder, mailing list, etc.

**Comment by ricardoaat** [comment]
this was addressed by @kcmcleod and the specifications have a list of contributors. Now it's needed to update those list for which i will create another issue.
