### ISSUE TITLE
Group tab seems redundant

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#70]
This info seems to be better displayed in the home ([Groups ...](http://bioschemas.org/index.html)). Maybe we do not need the [Groups tab](http://bioschemas.org/groups/index.html)?

**Comment by robertopreste** [comment]
The Groups tab exists to show all the details and specifications without having to look at GitHub, which I think is the point in having a specific Bioschemas website with all the project information available in it. What do you think?
