### ISSUE TITLE
Resurrect monthly meetings

### ISSUE THREAD

**Issue by rajido** [BioSchemas/specifications#74]
The number of groups and contributors is growing in Bioschemas and it is not feasible anymore to have just one meeting with everybody discussing the nitty-gritty of every specification. I did talked to @martin-nc and @robertopreste and we agreed it would be easier each group proposes a date for a regular TC, even it they just take 20'. Ideally the chair(s) of each group should announce meetings dates and make the minutes available in the [meetings wiki page](https://github.com/BioSchemas/bioschemas/wiki/Meetings-and-minutes).

We thought the @BioSchemas/community group which will also meet once per month should have a rep from every other group to provide update/highlights from every group.

@robertopreste can help us to set up doodle polls to find out when it would be convenient for each group to meet. @robertopreste can also create a google calendar that we could embed in the website.

**Comment by AlasdairGray** [comment]
There is now a monthly community call
