### ISSUE TITLE
Contributors spreadsheet link broken

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#77]
The link to contributors spreadsheet on http://bioschemas.org/groups/index.html#join_a_group is broken. Getting the following error message

> Sorry, unable to open the file at present.
> 
> Please check the address and try again.

**Comment by robertopreste** [comment]
Hello @AlasdairGray, thanks for pointing this out. We are currently working to solve this issue. Will be fixed asap.

**Comment by AlasdairGray** [comment]
It would be worth checking all the links on the page, as the other spreadsheet link is broken as well.

**Comment by AlasdairGray** [comment]
These are now working for me.
