### ISSUE TITLE
Shared folders broken links

### ISSUE THREAD

**Issue by AlasdairGray** [BioSchemas/specifications#78]
Some of the shared folders links on http://bioschemas.org/groups/index.html are broken. Certainly applies to Data and Tools.

**Comment by gtsueng** [comment]
@AlasdairGray  All specification communities have working shared folder links. Only non-specification communities (technical, validation) are missing shared folder links--but work within these communities are expected to happen over GitHub anyway. If it is desirable to have a shared folder for these groups, please create a new issue.
