### ISSUE TITLE
new group - chemical entity

### ISSUE THREAD

**Issue by mnowotka** [BioSchemas/specifications#81]
We would like to create a new group in order to focus on descibing chemicals. We hope to finish an intial draft during the hackaton.

**Comment by mnowotka** [comment]
trying to mention @agaulton, @adekker2 to keep things going.

**Comment by mnowotka** [comment]
and @josharman :)

**Comment by mnowotka** [comment]
Initila document based on ProteinStructure: https://docs.google.com/document/d/1ynXhOxW3kpuEkKGDzV8JNrYc0Ro4wxYEravxl_3Ll-k/edit?usp=sharing

**Comment by kcmcleod** [comment]
Same as #101 ?

**Comment by mnowotka** [comment]
You just made a cricular dependency between #81 and #101 but since 81 < 101 it's 101 that should be marked as duplicate and closed.

**Comment by AlasdairGray** [comment]
Group has been created
http://bioschemas.org/groups/Chemicals/
