### ISSUE TITLE
Change 'Extends <schema.org Type>' in _Bioschemas mapping template_ 		

### ISSUE THREAD

**Issue by agbeltran** [BioSchemas/specifications#82]
The [_Bioschemas mapping template_](https://docs.google.com/spreadsheets/d/1OMBiB8SXiRe1b3Cl91IuNlHbJ9_UXHg8B-GY0MYRSaY/edit#gid=1261485211) used by the map2model tool uses 'Extends <schema.org Type>' to indicate the schema.org entity being used in the specification, where the profile is defined. However, usually, we are not extending the entity so I suggest changing 'Extends' to 'Uses' or 'Refers' or something similar.

**Comment by kcmcleod** [comment]
mapping template no longer used, so no need to fix.
